src/index.tsx

This fix stops location change when a prompt is triggered but dismissed and then state changes.

Fix Prompt

---

docs/src/pages/docs/api.md
docs/src/pages/overview.md

Fixes several typos in the markdown doc files

Markdown typo fixes

---

docs/src/pages/guides/memory-and-hash-routing.md

Update Doc - Hash Routing section

---

packages/react-location-jsurl/src/index.tsx

This is my first open-source contribution. so, I'm very nervous.
This PR is to fix #81 #80 issues. I also tested with the Kitchen Sink example and it was working well.

fix: make jsurl package stringify function work as expected

---

docs/src/pages/docs/api.md
docs/src/pages/guides/route-elements.md
docs/src/pages/guides/route-loaders.md
docs/src/pages/guides/routes.md

Thanks for the new lib. I'm having fun trying it out! Hope you find these helpful.

Updates typos, grammar, etc

---

docs/src/pages/guides/routes.md

Nice work on the library! Found some typos while reading.

fix: typos

---

packages/react-location/src/index.tsx

Adds an unloader function to the route configuration. This is useful when your loader function is triggering requests through a stateful request library that has its own caching mechanism (Relay, Apollo, etc.) and you want to clean their caches when eager prefetch's aren't needed.
Docs site should probably be updated with the new api.

Feat: Unloader function for hooking into `cleanMatchCache`

---

docs/src/pages/guides/routes.md

Remove duplicated "truly" word in the _Routes Paths_ description.

Routes guide polishing

---

docs/src/pages/guides/custom-search-param-serialization.md

Using the same order in the code helps me understand it faster.

Change order of function to match order in (1) 'parseSearch' (2) 'stringifySearch'

---

docs/guide/custom-search-param-serialization.md

Same as https://github.com/TanStack/router/pull/332 but for alpha branch.

Docs: Change order of function to match order in (1) 'parseSearch' (2) 'stringifySearch'

---

docs/guide/custom-search-param-serialization.md

Same as https://github.com/TanStack/router/pull/331 but for alpha branch.

Docs: Fix Zipson example

---

docs/quick-start.md

Import was confusing as I was expecting to see some data-fetching or example of using with axios in this quick example

Remove unused import in first example

---

packages/react-location/src/qss.ts

keep url query like "?code=001".

fix: qss.ts toValue function

---

docs/comparison.md

docs: update comparison.md

---

docs/quick-start.md

I know most people should be able to figure this out, but better safe than sorry. :)
Also, sorry if I did this wrong, I'm EXTREMELY new to OSS. I didn't mean to make a whole dang pull request...

Added missing Link import

---

examples/react/basic-ssr-streaming/README.md
examples/react/basic-ssr/README.md
examples/react/basic/README.md
examples/react/kitchen-sink-multi-file/README.md
examples/react/kitchen-sink-single-file/README.md
examples/react/kitchen-sink-ssr/README.md
examples/react/with-react-query/README.md
examples/react/with-trpc-react-query/README.md
examples/react/with-trpc/README.md

Thank you for providing me with a good library!
The yarn start command seems to be used in duplicate.
Separated npm and yarn commands.

fix: npm start command

---

docs/quick-start.md

📝 docs(Quick Start): update Root config guide

---

docs/devtools.md

Example is missing the router prop

Add missing router prop to DevTools

---

.github/ISSUE_TEMPLATE/bug_report.yml
examples/react/quickstart/.gitignore
examples/react/quickstart/README.md
examples/react/quickstart/index.html
examples/react/quickstart/package.json
examples/react/quickstart/src/main.tsx
examples/react/quickstart/tsconfig.dev.json
examples/react/quickstart/tsconfig.json
examples/react/quickstart/vite.config.js

use examples in repo to setup stackblitz

chore: Add link to pre-configured stackblitz project for bug report

---

docs/api/react/Link.md
docs/api/react/MatchRoute.md
docs/api/react/Outlet.md
docs/api/react/Prompt.md
docs/api/react/Route.md
docs/api/react/RouterProvider.md
docs/api/react/createReactRouter.md
docs/api/react/createRouteConfig.md
docs/api/react/lazy.md
docs/api/react/useAction.md
docs/api/react/useLinkProps.md
docs/api/react/useLoaderData.md
docs/api/react/useMatch.md
docs/api/react/useMatchRoute.md
docs/api/react/useNavigate.md
docs/api/react/useParams.md
docs/api/react/usePrompt.md
docs/api/react/useRoute.md
docs/api/react/useRouter.md
docs/api/react/useRouterStore.md
docs/api/react/useSearch.md
docs/config.json

I started adding everything under API, but I assume the long-term plan is to split it into sections:
- Core API
- Framework specific API i.e. React API

Docs: Add API docs

---

docs/guide/router.md
docs/quick-start.md

I feel like there should be some remarks of declaration merging to use type inference, as I had a few hours wondering and troubleshooting why neither my params nor my paths were correctly typed.
Feel free to reject the PR though if the way it's done is about to change soon.

docs: add declaration merging

---

docs/guide/layout-routes.md

Simple example with different layouts for authenticated and unauthenticated routes

Adds example of layout routes

---

docs/comparison.md

Revert "docs: update nextjs link"

---

docs/guide/type-safety.md

docs: update type-safety.md

---

packages/router/src/routeMatch.ts
packages/router/src/router.ts

This PR amends route error handling behaviour as follows:
Throwing a `redirect` in any of:
- `beforeLoad`
- `validateSearch`
- `onLoad`
- `onBeforeLoadError`
- `onValidateSearchError`
- `onLoadError`
- `onError`
will cause the router to navigate immediately unless preloading. If preloading, the router will bail early but won't navigate.
If anything other than a `redirect` is thrown in `beforeLoad`, `validateSearch` or `onLoad` it will be handled by the corresponding handler (i.e. `onBeforeLoadError` `onValidateSearchError`, or `onLoadError`). If there is no corresponding handler, it will be handled by `onError`. If there is no `onError`, it will be handled by the `errorComponent`.
If a `beforeLoad` error handler returns, the original error is logged in the console. If the handler throws …

Allow redirects in route functions and update error handling

---

docs/comparison.md

- Add next-js website link
- Fix react-router links

docs: update links on comparison page

---

docs/installation.md

Fixes link to the react adapter

Fix link to React adapter installation

---

packages/router/src/react.tsx

Revert "fix: Link children types"

---

docs/comparison.md

fix: comparison.md file

---

docs/api/react/lazy.md
docs/guide/code-splitting.md
packages/router/__tests__/TestComponent.tsx
packages/router/__tests__/createRoutes.test.ts
packages/router/src/react.tsx

Add named imports to lazy wrapper.

feat: named imports

---

docs/guide/route-paths.md

There was a code error on route-paths.md, section [Dynamic Segments](https://tanstack.com/router/v1/docs/guide/route-paths#dynamic-segments), involving the routes tree creation

docs: fix code error in route-paths.md

---

packages/actions/src/index.ts

Hello,
Per our discussion on Discord I tried to fix action payload types to differentiate between functions with and without arguments. I'm not 100% sure about my solution (especially the payload part) but wanted to give it a try so feel free to point out errors 😃 It correctly infers both payload in submit fn and in submissions.
Example with parametrized fn:
Example with fn without parameters:

fix: stricter actions payload type

---

docs/config.json

https://tanstack.com/router/v1/docs/examples/react/basic-srr?file=src%2Fentry-server.tsx

Fix broken SSR example links

---

docs/api/router-cli.md
docs/devtools.md
docs/guide/authenticated-routes.md
docs/guide/code-splitting.md
docs/guide/data-loading.md
docs/guide/data-mutations.md
docs/guide/navigation-blocking.md
docs/guide/route-matching.md
docs/guide/route-paths.md
docs/guide/routes.md
docs/guide/search-params.md
docs/guide/ssr-and-streaming.md
docs/guide/type-safety.md

Hey, here are some docs typo fixes :) 
Using the power of Grammarly's VS Code extension + manual review.

[docs] Typos fixes

---

packages/router-core/src/router.ts

Fixed the issue where location state is ignored during navigation.

Add state to location nextOpts

---

packages/router-core/src/router.ts

fix: remove errant console log for resetScroll

---

packages/react-cross-context/package.json
packages/react-cross-context/src/Context.ts
packages/react-cross-context/src/index.ts
packages/react-router-server/package.json
packages/react-router-server/src/client.tsx
packages/react-router-server/src/server.tsx
pnpm-lock.yaml
scripts/config.ts

fix: ssr render error

---

examples/react/basic-file-based/src/routeTree.gen.ts
examples/react/kitchen-sink-file-based/src/routeTree.gen.ts
examples/react/kitchen-sink-react-query-file-based/src/routeTree.gen.ts
packages/router-cli/src/generator.ts

fix: use correct id in generator

---

docs/api/router-cli.md
examples/react/kitchen-sink-react-query-file-based/src/routes/_auth.profile.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/_auth.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/_layout.layout-a.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/_layout.layout-b.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/_layout.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.index.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.invoices.$invoiceId.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.invoices.index.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.invoices.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.users.index.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.users.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.users.user.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/expensive/index.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/index.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/login.tsx
examples/react/kitchen-sink-react-query-file-based/tsr.config.json
packages/router-cli/src/config.ts
packages/router-cli/src/generator.ts

feat(route-cli): make quote style configurable

---

docs/api/router/ToOptionsType.md
packages/react-router/src/router.ts

fix: clear hash if not set

---

packages/router-devtools/src/utils.ts

fix(devtools): try catch around JSON.stringify

---

packages/react-router/src/router.ts

fix: location masking forgets path parameters

---

docs/guide/navigation.md
docs/guide/search-params.md
docs/guide/type-safety.md
examples/react/kitchen-sink-file-based/src/routes/dashboard.invoices.$invoiceId.tsx
examples/react/kitchen-sink-file-based/src/routes/dashboard.users.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.invoices.$invoiceId.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.users.tsx
examples/react/kitchen-sink-react-query/src/main.tsx
examples/react/kitchen-sink/src/main.tsx
examples/react/with-trpc/client/main.tsx

update docs and examples to use `route.fullPath` instead of `route.id` as `from`

---

docs/guide/file-based-routing.md

Hey,
Just noticed this while going through the documentation.
Thanks for the router, I absolutely love it!
Great work @Tanner-Scadden

Fix broken URL in the docs (file-base-routing.md)

---

packages/react-router/src/router.ts

fix: correctly handle basepath="/"

---

docs/config.json
docs/migrate-from-react-router.md

Basic description of api's and steps to migrate from React Router to Tanstack Router

Added basic migrate from react router checklist

---

packages/react-router/src/route.ts

fix: do not strip away / from index route id

---

packages/router-generator/src/generator.ts

Fixes [ #1058](https://github.com/TanStack/router/issues/1058)

Strip out the routeFilePrefix in the routePath when gathering routes

---

packages/react-router/src/router.ts

fix: catch synchronous exceptions in loader

---

package.json
pnpm-lock.yaml

Update example dependencies when publishing (https://github.com/TanStack/config/pull/35)

chore: Update @tanstack/config to 0.4.0

---

package.json
pnpm-lock.yaml

https://github.com/TanStack/config/commit/a574887548f9d711fcf9769fb0da3c7bbdd4e5e2

ci: Fix TanStack Config publish ERR_PNPM_OUTDATED_LOCKFILE

---

packages/react-router/src/Matches.tsx

Fixes https://github.com/TanStack/router/issues/1112

fix: fix state selector that causes multiple unnecessary renders on navigation

---

packages/router-generator/src/generator.ts

Hey sorry @tannerlinsley @schiller-manuel here is the fix for my `addExtensions` option, my PR #1160 did not work as intended.

fix: get file extension

---

nx.json
packages/router-generator/src/generator.ts

https://nx.dev/ci/recipes/security/access-tokens

ci: Add read-only Nx cloud access token

---

docs/framework/react/guide/navigation.md

There was a little typo I found and fixed :-)

Fix navigation.md typo

---

packages/react-router/src/router.ts

https://github.com/TanStack/router/issues/1273

fix(router): resolvePathWithBase without dest.to

---

docs/framework/react/api/router/useMatchHook.md

docs: fix useMatchHook api description

---

packages/react-router/src/RouterProvider.tsx

Fix formatting issue caused by #1293

(prettier) react-router - fix formatting issue on router provider

---

packages/react-router/src/awaited.tsx

We're currently stringifying the data using the transformer, but not parsing it back

fix: use transformer to parse data

---

packages/react-router/src/link.tsx
packages/react-router/src/utils.ts
packages/react-router/tests/utils.test.ts

discussion:
- https://github.com/TanStack/router/discussions/1364

fix: trailing slash shouldn't fail the path matching

---

packages/router-vite-plugin/vite.config.ts

fix: do not include tests in package

---

README.md

fix(router-vite-plugin): trigger release

---

packages/react-router/tests/fileRoute.test-d.tsx
packages/react-router/tests/route.test-d.tsx

- add type tests for code based routes
- add basic type tests for file based routes

tests: add fileRoute and route type tests

---

packages/router-vite-plugin/src/index.ts

fix: do not invoke generator again while it is still running

---

package.json
packages/router-devtools/package.json
pnpm-lock.yaml

`project`
Bump:
* `vite` - `5.2.8`
* `vitest` - `1.5.0`
`@tanstack/router-devtools`
Remove: `vite`

build: upgrade core dependencies for the build pipeline

---

examples/react/vinxi-basic-ssr-streaming/app/server.tsx

Pulls the changes from this [commit](https://github.com/TanStack/tanstack.com/commit/404f227d525623df08394563ab2a2e878bb7fb5b#diff-bc9af47a028b7b908900a79f480a5529a66fc68678ce5cfa6b64ec10f7b5e652R39) in the Tanstack/tanstack.com repo into the *vinxi-basic-ssr-streaming* example.

docs(examples): update vinxi-basic-ssr-streaming with the changes from the TanStack.com repo

---

packages/react-router/src/router.ts

fix(react-router): viewTransition property not being respected during navigation on `<Link>` and `useNavigate()`

---

packages/react-router/src/router.ts
packages/react-router/tests/link.test.tsx

Revert "fix: take from into account when building urls"

---

docs/framework/react/guide/router-context.md

More or less, took the documentation in the Authenticated Routes guide about the usage of hooks/context, and documented for how it'd be done using Router Context in its guide.

docs: about the usage of hooks in the "Router Context" guide

---

packages/react-router/README.md
packages/router-cli/README.md
packages/router-devtools/README.md
packages/router-vite-plugin/README.md
packages/start/README.md

For:
* `@tanstack/react-router`
* `@tanstack/router-cli`
* `@tanstack/router-devtools`
* `@tanstack/router-vite-plugin`
* `@tanstack/start`

docs: add README files for the user-facing packages

---

docs/framework/react/api/router/RouteOptionsType.md
docs/framework/react/api/router/RouterOptionsType.md
packages/react-router/src/CatchBoundary.tsx
packages/react-router/src/Matches.tsx
packages/react-router/src/not-found.tsx
packages/react-router/src/route.ts
packages/react-router/src/router.ts

to catch errors thrown by ErrorBoundaries

feat: onCatch callback on routes and defaultOnCatch for router

---

packages/react-router/src/index.tsx

type(react-router): export the `TrailingSlashOption` type

---

packages/react-router/src/router.ts
packages/react-router/tests/link.test.tsx

beforeLoad wasn't rendering the errorComponent. Added unit tests to cover this case.

fix: should render error component when beforeLoad throws an error

---

examples/react/kitchen-sink-file-based/src/routes/__root.tsx
examples/react/kitchen-sink-file-based/src/routes/_auth.tsx
examples/react/kitchen-sink-file-based/src/routes/_layout.tsx
examples/react/kitchen-sink-file-based/src/routes/dashboard.index.tsx
examples/react/kitchen-sink-file-based/src/routes/dashboard.invoices.$invoiceId.tsx
examples/react/kitchen-sink-file-based/src/routes/dashboard.invoices.index.tsx
examples/react/kitchen-sink-file-based/src/routes/dashboard.invoices.tsx
examples/react/kitchen-sink-file-based/src/routes/dashboard.users.index.tsx
examples/react/kitchen-sink-file-based/src/routes/dashboard.users.tsx
examples/react/kitchen-sink-file-based/src/routes/index.tsx
examples/react/kitchen-sink-file-based/src/utils/mockTodos.ts
examples/react/kitchen-sink-react-query-file-based/src/routes/__root.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/_auth.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/_layout.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.index.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.invoices.$invoiceId.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.invoices.index.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.invoices.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.users.index.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.users.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.users.user.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/index.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/login.tsx
examples/react/kitchen-sink-react-query-file-based/src/utils/mockTodos.ts
examples/react/kitchen-sink-react-query/src/mockTodos.ts
examples/react/kitchen-sink/src/main.tsx
examples/react/kitchen-sink/src/mockTodos.ts

Just some housekeeping for the kitchen sink examples that have become a bit messy over time.

docs(examples): cleanup the "kitchen-sink*" examples

---

packages/router-generator/src/generator.ts

fix: do not assign path to virtual routes for route groups

---

package.json
pnpm-lock.yaml

Importantly, fixes compatibility with TS 5.5

chore: Update @tanstack/config

---

packages/react-router/src/router.ts
packages/react-router/tests/index.test.tsx
packages/react-router/tests/link.test.tsx

fix(react-router): redirect with relative path

---

.github/workflows/ci.yml
.github/workflows/pr.yml
.gitignore
.npmrc
nx.json
package.json
pnpm-lock.yaml

- Update pnpm from v8 to v9
- Update Nx from v17 to v18

ci: Update workspace dependencies

---

docs/framework/react/guide/code-splitting.md
docs/framework/react/guide/file-based-routing.md
docs/framework/react/guide/routing-concepts.md
docs/framework/react/migrate-from-react-location.md
docs/framework/react/quick-start.md

docs: update the documentation on the `@tanstack/router-plugin` package

---

packages/start/src/server/transformStreamWithRouter.ts

style(start): prefer `node:` prefixed imports for node packages

---

package.json
packages/history/package.json
packages/react-cross-context/package.json
packages/react-router-with-query/package.json
packages/react-router/package.json
packages/router-cli/package.json
packages/router-devtools/package.json
packages/router-generator/package.json
packages/router-plugin/package.json
packages/router-vite-plugin/package.json
packages/start-vite-plugin/package.json
packages/start/package.json

- Main change is making sure each package has a valid "repository" field as defined here: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository
- Sorted other package fields for consistency and readability
- Necessary for pkg-pr-new support

fix: Update package.json fields

---

.github/workflows/preview.yml

Powered by https://github.com/stackblitz-labs/pkg.pr.new

ci: Add preview workflow

---

packages/history/package.json
packages/history/src/index.ts
packages/history/tests/createMemoryHistory.test.ts

fix(history): fix bugs in push and back of createMemoryHistory

---

examples/react/start-basic-counter/package.json
examples/react/start-basic-react-query/package.json
examples/react/start-basic-rsc/package.json
examples/react/start-basic/package.json
examples/react/start-trellaux/package.json
examples/react/wip-with-bling/package.json
package.json
packages/react-router/package.json
pnpm-lock.yaml

- @tanstack/react-store to v0.5.4
- @tanstack/config to v0.9.2
- Also syncs prettier version in examples

fix(deps): update @tanstack/react-store

---

docs/framework/react/api/router/FileRouteClass.md
docs/framework/react/api/router/NotFoundRouteClass.md
docs/framework/react/api/router/RootRouteClass.md
docs/framework/react/api/router/RouteApiClass.md
docs/framework/react/api/router/RouteClass.md
docs/framework/react/api/router/RouterClass.md
docs/framework/react/api/router/lazyRouteComponentFunction.md
docs/framework/react/api/router/rootRouteWithContextFunction.md
docs/framework/react/api/router/useChildMatchesHook.md
docs/framework/react/api/router/useMatchesHook.md
docs/framework/react/api/router/useParentMatchesHook.md
docs/framework/react/api/router/useRouterStateHook.md
docs/framework/react/decisions-on-dx.md
docs/framework/react/guide/authenticated-routes.md
docs/framework/react/guide/code-based-routing.md
docs/framework/react/guide/code-splitting.md
docs/framework/react/guide/creating-a-router.md
docs/framework/react/guide/custom-search-param-serialization.md
docs/framework/react/guide/deferred-data-loading.md
docs/framework/react/guide/external-data-loading.md
docs/framework/react/guide/file-based-routing.md
docs/framework/react/guide/outlets.md
docs/framework/react/guide/route-masking.md
docs/framework/react/guide/router-context.md
docs/framework/react/guide/search-params.md
docs/framework/react/guide/server-functions.md
docs/framework/react/migrate-from-react-location.md
docs/framework/react/quick-start.md

Do not merge till https://github.com/TanStack/tanstack.com/pull/249 has been merged into tanstack.com.

docs: use gfm alerts in the documentation

---

package.json
pnpm-lock.yaml

Hopefully fixes error in this workflow: https://github.com/TanStack/router/actions/runs/9885470864/job/27303552109

ci: update @tanstack/config

---

docs/framework/react/guide/data-loading.md

Updating the loader parameters in the data loading documentation to reflect what's currently in main

docs: update the list of parameters available in the `loader` in the "data loading" guide

---

packages/react-router/tests/routeContext.test.tsx

test(react-router): correct use `act` in `routeContext.test.tsx`

---

docs/framework/react/guide/data-loading.md
docs/framework/react/guide/deferred-data-loading.md

Fixing only minor typos in the router data loading docs.

Fix minor typo in data loading docs

---

packages/react-router/src/path.ts
packages/react-router/tests/path.test.ts

fix: correctly resolve paths when basepath is set

---

packages/react-router/src/Match.tsx

fix(react-router): memoize Match, MatchInner as well as route components to prevent unnecessary re-renders

---

docs/framework/react/guide/tanstack-start.md

Also opted to change the `// ...` into a normal comment to avoid confusion.

docs: fixed missing comma in Start Vinxi scripts

---

packages/react-router/src/Match.tsx
packages/react-router/tests/loaders.test.tsx

fix(react-router): update match in effect instead of during render

---

packages/react-router/src/Match.tsx

fixes #2106
this reverts https://github.com/TanStack/router/pull/2075 since the effect was not executed properly. To avoid the infinite loop of #2053, the `minPendingPromise` is read via `router.getState` since `match` property was not up-to-date

fix(react-router): fix minPendingMs

---

packages/history/src/index.ts
packages/react-router/tests/routeContext.test.tsx

[experimental] fix: safer history patching

---

package.json
pnpm-lock.yaml

fix: upgrade @tanstack/config to generate correct d.ts files

---

docs/config.json
docs/framework/react/start/api-routes.md

Docs for the API Routes feat in #2185.

docs(start): API routes

---

docs/framework/react/start/databases.md

Added a dark mode Convex logo while retaining the light version, depending on the user's theme.

Added dark mode Convex logo

---

packages/history/src/index.ts
packages/react-router/src/router.ts
packages/react-router/tests/routeContext.test.tsx
packages/react-router/tests/useNavigate.test.tsx

fix: make stacked navigations use latest search params

---

docs/framework/react/overview.md

removed "Prefetching" in the doc, it was duplicated.

docs(react): remove duplicated line in overview.md

---

docs/framework/react/start/getting-started.md

with module `Preserve`:
with module `ESNext`:

docs(start): fix tsconfig

---

packages/react-router/src/path.ts
packages/react-router/tests/router.test.tsx

fix(react-router): do not decode already escaped URL path segments

---

packages/react-router/src/router.ts
packages/react-router/tests/blocker.test.tsx

fix(react-router): ignore blockers for redirects

---

docs/framework/react/overview.md

This PR corrects a minor typo to improve clarity in the documentation.

docs(react): Fix typo

---

packages/router-generator/src/config.ts
packages/router-generator/src/generator.ts

fix(router-generator): do not allow "_" as a `routeFIleIgnorePrefix`

---

.github/renovate.json
package.json
pnpm-lock.yaml

ci(deps): fix typescript55 version

---

packages/react-router/src/route.ts
packages/react-router/tests/routeApi.test-d.tsx

I missed this in the original PR

perf(react-router): apply language service performance to `getRouteApi`

---

packages/router-plugin/src/core/code-splitter/compilers.ts

fix(router-plugin): do not minify code in compiler

---

docs/framework/react/guide/file-based-routing.md

docs(router): broken links on the file-based routing guide

---

docs/framework/react/start/getting-started.md
examples/react/start-basic-auth/app/client.tsx
examples/react/start-basic-auth/app/ssr.tsx
examples/react/start-basic-react-query/app/client.tsx
examples/react/start-basic-react-query/app/routes/__root.tsx
examples/react/start-basic-react-query/app/ssr.tsx
examples/react/start-basic-rsc/app/client.tsx
examples/react/start-basic-rsc/app/ssr.tsx
examples/react/start-basic/app/client.tsx
examples/react/start-basic/app/routes/__root.tsx
examples/react/start-basic/app/ssr.tsx
examples/react/start-clerk-basic/app/client.tsx
examples/react/start-clerk-basic/app/ssr.tsx
examples/react/start-convex-trellaux/app/client.tsx
examples/react/start-convex-trellaux/app/routes/__root.tsx
examples/react/start-convex-trellaux/app/ssr.tsx
examples/react/start-counter/app/client.tsx
examples/react/start-counter/app/ssr.tsx
examples/react/start-supabase-basic/app/client.tsx
examples/react/start-supabase-basic/app/ssr.tsx
examples/react/start-trellaux/app/client.tsx
examples/react/start-trellaux/app/routes/__root.tsx
examples/react/start-trellaux/app/ssr.tsx

docs: Fixed type errors with importing assets with Vite

---

docs/framework/react/guide/custom-link.md

docs: fix mui button docs

---

packages/start/src/client/serialization.tsx

fix(start): correctly hydrate match context w.r.t parent context

---

packages/start/src/config/index.ts

fix(start): extend api router schema to allow vite plugins

---

packages/react-router/src/not-found.tsx
packages/react-router/tests/link.test.tsx

fix(react-router): do not unnecessarily render notFoundComponent

---

docs/framework/react/guide/file-based-routing.md
docs/framework/react/guide/route-trees.md

from https://github.com/TanStack/router/discussions/1102#discussioncomment-10889493

docs: less disruptive file-based routing guide regarding virtual routes

---

packages/start-vite-plugin/package.json
packages/start-vite-plugin/src/compilers.ts
packages/start-vite-plugin/src/index.ts
packages/start/src/config/index.ts
pnpm-lock.yaml

fix(start): eliminate dead code after vinxi's transform for `createServerFn`

---

e2e/react-router/basic-file-based/src/routeTree.gen.ts
e2e/react-router/basic-file-based/src/routes/(another-group)/onlyrouteinside.tsx
e2e/react-router/basic-file-based/src/routes/(group)/_layout.insidelayout.tsx
e2e/react-router/basic-file-based/src/routes/(group)/inside.tsx
e2e/react-router/basic-file-based/src/routes/(group)/subfolder/inside.tsx
e2e/react-router/basic-file-based/src/routes/__root.tsx
e2e/react-router/basic-file-based/tests/app.spec.ts
packages/router-generator/src/generator.ts
packages/router-generator/tests/generator/append-and-prepend/routeTree.snapshot.ts
packages/router-generator/tests/generator/custom-tokens/routeTree.snapshot.ts
packages/router-generator/tests/generator/file-modification/routeTree.snapshot.ts
packages/router-generator/tests/generator/flat/routeTree.snapshot.ts
packages/router-generator/tests/generator/nested-layouts/routeTree.snapshot.ts
packages/router-generator/tests/generator/nested/routeTree.snapshot.ts
packages/router-generator/tests/generator/no-manifest/routeTree.snapshot.ts
packages/router-generator/tests/generator/route-groups/routeTree.snapshot.ts
packages/router-generator/tests/generator/single-level/routeTree.snapshot.ts
packages/router-generator/tests/generator/types-disabled/routeTree.gen.js
packages/router-generator/tests/generator/types-disabled/routeTree.snapshot.js
packages/router-generator/tests/generator/virtual-inside-nested/routeTree.snapshot.ts
packages/router-generator/tests/generator/virtual/routeTree.snapshot.ts

fix(router-generator): correctly generate ids for single routes inside route groups

---

packages/start/src/client/serialization.tsx

fix(start): make router context available in match context after hydration

---

packages/start/src/server-handler/index.tsx

fix(start): server function returns status code 500 in case of unhandled error

---

packages/react-router/package.json
packages/react-router/src/router.ts
packages/react-router/tests/link.test.tsx
packages/react-router/tests/router.test.tsx
pnpm-lock.yaml

this will make search middlewares correctly execute upon redirect

fix(react-router): run search middlewares also on entering matches

---

packages/react-router/src/router.ts
packages/react-router/tests/redirect.test.tsx

fix(react-router): handle redirects in loaders after invalidate

---

packages/react-router/src/router.ts
packages/react-router/tests/loaders.test.tsx

fix(react-router): resolve loadPromise when beforeLoad throws

---

packages/react-router/src/router.ts

fix(react-router): do not reference `RegisteredRouter` in `Router` itself

---

packages/start/src/config/index.ts

fix(start): use user's ssr.noExternal config

---

docs/framework/react/start/getting-started.md

1-Merge two import statements in one
2-Use `type` keyword to explicitly mark as type import (https://biomejs.dev/linter/rules/use-import-type/) 3- Mark props as Readonly

docs(start): update root route in the getting-started.md

---

packages/start/src/config/index.ts

https://discord.com/channels/719702312431386674/1238170697650405547/1304458906684096602

feat(start): configurable public router

---

packages/react-router/src/matchContext.tsx
packages/react-router/src/router.ts
packages/react-router/src/useMatch.tsx

fix(react-router): fix re-rendering when loaderDeps change

---

docs/framework/react/guide/authenticated-routes.md

docs(router): usage of imports for auth on authentication guide

---

packages/start/src/client/createServerFn.ts
packages/start/src/client/tests/createServerFn.test-d.tsx

fix: https://discord.com/channels/719702312431386674/1309307399995392132/1309307399995392132

fix(start): createServerFn method suggestion

---

packages/create-router/package.json
pnpm-lock.yaml

Revert "chore(deps): update dependency @inquirer/prompts to v7"

---

packages/react-router/src/index.tsx

refactor(react-router): expose `CheckFromPath`

---

packages/start/src/config/index.ts

fix(start): set default deployment preset to `node-server`

---

packages/create-router/src/utils/copyTemplateFiles.ts

fix(create-router): await directory copy operation when copying template

---

docs/framework/react/devtools.md

add installation instructions for npm, pnpm, yarn, and bun

docs(devtools): update installation instructions

---

packages/start/src/config/index.ts
packages/start/src/config/schema.ts

fix(start): pass through vite react plugin config options

---

packages/react-router/src/Transitioner.tsx

fix(react-router): fix transitions

---

packages/router-generator/src/filesystem/virtual/getRouteNodes.ts

fix(router-generator): do not register tsx import, instead use its API

---

docs/framework/react/guide/file-based-routing.md

docs: Update file-based-routing.md

---

docs/framework/react/guide/custom-link.md

Add an example on how to create a typesafe custom link using UI library **Mantine**

docs: add custom link example for mantine

---

packages/create-start/package.json
pnpm-lock.yaml

Some dependencies need to be moved from dev-dependencies to dependencies

fix(create-start): create-start deps

---

packages/react-router/package.json
packages/react-router/src/link.tsx
packages/react-router/src/routeInfo.ts
packages/react-router/tests/link.test-d.tsx
packages/react-router/tests/route.test-d.tsx
packages/router-generator/package.json
packages/router-generator/tests/generator/nested/tests.test-d.ts
pnpm-lock.yaml

fix: fix types for relative routing

---

e2e/react-router/basic-file-based/src/routeTree.gen.ts
e2e/react-router/basic-file-based/src/routes/redirect/preload/first.tsx
e2e/react-router/basic-file-based/src/routes/redirect/preload/second.tsx
e2e/react-router/basic-file-based/src/routes/redirect/preload/third.tsx
e2e/react-router/basic-file-based/tests/redirect.spec.ts
packages/react-router/src/router.ts

fix(react-router): properly handle redirects when thrown during parallel preload

---

docs/framework/react/start/learn-the-basics.md

small typo i came across in the docs

docs: learn-the-basics.md

---

e2e/start/basic/app/routeTree.gen.ts
e2e/start/basic/app/routes/stream.tsx
e2e/start/basic/tests/base.spec.ts
packages/react-router/src/ScriptOnce.tsx
packages/react-router/src/router.ts
packages/start/src/server/defaultRenderHandler.tsx

fix: order of injected scripts

---

scripts/publish.js

build: publish `directive-functions-plugin` & `server-functions-plugin`

---

packages/react-router/src/ScriptOnce.tsx
packages/start-client/src/Meta.tsx
packages/start-router-manifest/src/index.ts

fix(start): fix script initialization order

---

docs/framework/react/start/build-from-scratch.md

Adding a little more information and fixing the issue of the missing dependency.
Fixes the issue reported on X: https://x.com/bawsacharry/status/1882818181359890508

docst(start): Update build-from-scratch.md

---

docs/framework/react/start/static-prerendering.md

Added a section to Static Prerendering docs on how to prerender dynamic routes with Nitro
- Synced with @tannerlinsley over [Discord](https://discord.com/channels/719702312431386674/1332190778767966282/1332372843819700398)

docs(start): Update static-prerendering.md to include dynamic prerendering

---

docs/framework/react/start/api-routes.md
docs/framework/react/start/middleware.md

Small fixes for the API and middleware documentation.

docs(start): small fixes to clean up issues in documentation

---

e2e/start/basic/app/routes/isomorphic-fns.tsx
e2e/start/basic/tests/server-functions.spec.ts
packages/start-plugin/src/compilers.ts

fix(start-plugin): invoke server implementation of createIsomorphicFn during SSR

---

e2e/react-router/basic-file-based/tests/redirect.spec.ts
e2e/start/basic/app/routeTree.gen.ts
e2e/start/basic/app/routes/not-found/index.tsx
e2e/start/basic/app/routes/not-found/route.tsx
e2e/start/basic/app/routes/not-found/via-beforeLoad.tsx
e2e/start/basic/app/routes/not-found/via-loader.tsx
e2e/start/basic/tests/fixture.ts
e2e/start/basic/tests/not-found.spec.ts
e2e/start/basic/tests/redirect.spec.ts
e2e/start/basic/tests/search-params.spec.ts

the actual fix was accidentally included in https://github.com/TanStack/router/pull/3269

tests: notFound handling in notFound when SSRing

---

e2e/start/basic/app/routes/stream.tsx
packages/start-client/src/ssr-client.tsx
packages/start-server/src/ssr-server.ts
packages/start-server/src/tsrScript.ts

fix(start): fix stream handling during SSR

---

docs/start/framework/react/build-from-scratch.md
docs/start/framework/react/learn-the-basics.md

`scrollRestoration: true` was being passed in to the incorrect method call.

docs(start): fix createRouter call

---

packages/start-server/src/transformStreamWithRouter.ts

fix(start): fix stream handling on cloudflare

---

packages/directive-functions-plugin/src/compilers.ts
packages/router-plugin/src/core/code-splitter/compilers.ts
packages/router-plugin/tests/code-splitter/snapshots/development/importAttribute.tsx
packages/router-plugin/tests/code-splitter/snapshots/development/importAttribute@split.tsx
packages/router-plugin/tests/code-splitter/snapshots/production/importAttribute.tsx
packages/router-plugin/tests/code-splitter/snapshots/production/importAttribute@split.tsx
packages/router-plugin/tests/code-splitter/test-files/importAttribute.tsx
packages/router-utils/src/ast.ts

fix(router-plugin): fix handling of import attributes

---

docs/router/framework/react/guide/custom-search-param-serialization.md

docs(router): warning on serialization with Base64

---

packages/router-plugin/src/core/code-splitter/compilers.ts
packages/router-plugin/tests/code-splitter/snapshots/development/conditional-properties.tsx
packages/router-plugin/tests/code-splitter/snapshots/development/conditional-properties@split.tsx
packages/router-plugin/tests/code-splitter/snapshots/production/conditional-properties.tsx
packages/router-plugin/tests/code-splitter/snapshots/production/conditional-properties@split.tsx
packages/router-plugin/tests/code-splitter/test-files/conditional-properties.tsx

fix(router-plugin): handle "ConditionalExpression" when code-splitting

---

packages/router-devtools/package.json
pnpm-lock.yaml

fix(router-devtools): peer dep for csstype for goober

---

packages/start-router-manifest/src/index.ts

fix(start): fix HMR preamble issue

---

docs/router/framework/react/guide/tanstack-start.md

One more doc fix for `createRootRoute`.

fix: doc fix for createRootRoute

---

packages/react-router/src/router.ts
packages/react-router/tests/router.test.tsx
packages/solid-router/src/router.ts
packages/solid-router/tests/Scripts.test.tsx
packages/solid-router/tests/router.test.tsx

fix(react-router, solid-router): do not strip search params if search validation fails

---

.github/labeler.yml
packages/solid-cross-context/eslint.config.js
packages/solid-cross-context/package.json
packages/solid-cross-context/src/Context.ts
packages/solid-cross-context/src/index.ts
packages/solid-cross-context/tsconfig.json
packages/solid-cross-context/vite.config.ts
pnpm-lock.yaml
scripts/publish.js

Port of:
- [react-cross-context](https://github.com/TanStack/router/tree/main/packages/react-cross-context)
Necessary for the solid versions of:
- start-client
- start-server

feat(solid-cross-context): add package

---

CONTRIBUTING.md

a small addition to contributing.
I faced lack of `pnpm exec playwright install` myself when trying to improve types.

CONTRIBUTING.md: added missing `pnpm exec playwright install`

---

examples/react/start-convex-trellaux/README.md

Fix spelling of "deployment" in the Start Convex Trellaux readme 😊

chore(examples): spelling error on Start Convex Trellaux

---

docs/router/framework/react/routing/installation-with-router-cli.md
docs/router/framework/solid/routing/installation-with-router-cli.md
docs/router/framework/solid/routing/installation-with-vite.md

docs(solid-router): missing steps for `tsconfig.json`

---

packages/react-start-client/src/ssr-client.tsx

fix(react-start-client): execute `head` and `scripts` after custom hydration

---

docs/router/framework/react/api/router/RouteOptionsType.md
docs/router/framework/react/api/router/RouterOptionsType.md
docs/router/framework/react/api/router/useBlockerHook.md

Just some typos and a clarification in the docs.

Documentation proofreading

---

packages/router-devtools/src/BaseTanStackRouterDevtoolsPanel.tsx
packages/router-devtools/src/Explorer.tsx
packages/router-devtools/src/TanStackRouterDevtools.tsx
packages/router-devtools/src/TanStackRouterDevtoolsPanel.tsx
packages/router-devtools/src/context.ts
packages/router-devtools/src/theme.tsx
packages/router-devtools/src/useStyles.tsx
packages/router-devtools/src/utils.ts

Reverts #3631  - it's relying on peer Deps of react v18 or v19, so it might be a problem if we use v19-only features.
There is work underway that'll uncouple this - but it's not in yet

refactor(router-devtools): Revert #3631 to ensure backwards compat with react 18

---

docs/start/framework/react/server-functions.md

Added clear description add the top that server functions cannot be called from API Routes.

Update server-functions.md docs

---

packages/react-router/src/Match.tsx

fix(react-router): ensure resetScroll works with strict mode on

---

packages/react-router/src/useNavigate.tsx
packages/react-router/tests/useNavigate.test.tsx
packages/solid-router/src/useNavigate.tsx
packages/solid-router/tests/useNavigate.test.tsx

fix: use default from in `useNavigate`

---

packages/react-router/src/link.tsx
packages/solid-router/src/link.tsx

fix: rebuild link if matches change

---

packages/react-router/src/fileRoute.ts
packages/react-router/src/route.ts
packages/react-router/tests/useNavigate.test.tsx
packages/solid-router/src/fileRoute.ts
packages/solid-router/src/route.ts
packages/solid-router/tests/useNavigate.test.tsx

fix: use `fullPath` as `from` in Route/RouteApi `useNavigate`

---

packages/react-start-client/src/StartClient.tsx
packages/react-start-client/src/ssr-client.tsx
packages/react-start-config/package.json
packages/react-start-config/src/index.ts
packages/react-start-server/src/StartServer.tsx
packages/react-start-server/src/createRequestHandler.ts
packages/react-start-server/src/createStartHandler.ts
packages/react-start-server/src/handlerCallback.ts
packages/react-start-server/src/ssr-server.ts
packages/react-start-server/src/transformStreamWithRouter.ts
packages/react-start-server/src/tsrScript.ts
packages/solid-start-client/src/StartClient.tsx
packages/solid-start-client/src/ssr-client.tsx
packages/solid-start-config/package.json
packages/solid-start-config/src/index.ts
packages/solid-start-server/src/StartServer.tsx
packages/solid-start-server/src/createRequestHandler.ts
packages/solid-start-server/src/createStartHandler.ts
packages/solid-start-server/src/handlerCallback.ts
packages/solid-start-server/src/ssr-server.ts
packages/solid-start-server/src/transformStreamWithRouter.ts
packages/solid-start-server/src/tsrScript.ts
pnpm-lock.yaml

Update start package imports after much router code has been moved to the agnostic router-core package.

chore(react-start,solid-start): update imports to use router-core

---

packages/react-router-devtools/package.json
packages/solid-router-devtools/package.json
pnpm-lock.yaml

Attempt to close
- https://github.com/TanStack/router/issues/3719

fix(solid-router-devtools,react-router-devtools): add core package and solid-js as deps

---

packages/react-router/package.json

fix(react-router): pin version of router-core

---

docs/router/framework/react/guide/scroll-restoration.md

Based on https://github.com/TanStack/router/pull/3191#issuecomment-2717415282

docs: Add example for virtualization for the whole window.

---

packages/react-router-devtools/package.json
packages/solid-router-devtools/package.json

Fixes duplicate dependency (both in dependencies and peerDependencies).
Closes #3755

fix(react-router-devtools): remove router devtools duplicate peer dependency

---

docs/router/framework/react/quick-start.md
docs/router/framework/solid/quick-start.md

Closes https://github.com/TanStack/router/issues/3756

fix(router-docs): update notes on devtools in quickstart guide

---

docs/router/framework/react/guide/external-data-loading.md

docs: typo in the "external-data-loading" guide

---

packages/solid-router/src/lazyRouteComponent.tsx

I think this should fix the nav flicker some people have brought up. This also seems to fix the view transitions issue
Basically a tweak of this pr https://github.com/TanStack/router/pull/3589/files

fix(solid-router): nav flickering and view transitions

---

docs/start/framework/react/build-from-scratch.md

From this thread on discord - https://discord.com/channels/719702312431386674/1352334129643126784

docs(start): move router configuration note to the top

---

docs/router/framework/react/quick-start.md
docs/router/framework/solid/quick-start.md

I ran into errors trying to use the npm and yarn commands listed here, so I looked at https://github.com/TanStack/create-tsrouter-app and it appears you should use npx with the `--package-manager` option to specify npm/yarn/etc.
I see the doc was updated in https://github.com/TanStack/router/pull/3759/files#diff-32b91344fa0565552fb394a3166cbdebd81afa9d02ffec1ed2c1d055ebad46a9, I assume that was the old way to create a project but feel free to edit or close this PR if there's a better way to document this, thanks.

docs: fix create-tsrouter-app command

---

docs/start/framework/solid/overview.md

addressing https://github.com/TanStack/router/pull/3864#discussion_r2015283936

chore(docs): fix escaping of brackets in solid overview page

---

packages/directive-functions-plugin/package.json
packages/react-start-plugin/package.json
packages/router-plugin/package.json
packages/router-plugin/tests/code-splitter/snapshots/react/1-default/development/random-number@component.tsx
packages/router-plugin/tests/code-splitter/snapshots/react/1-default/production/random-number@component.tsx
packages/router-plugin/tests/code-splitter/snapshots/react/2-components-combined-loader-separate/development/random-number@component---errorComponent---notFoundComponent---pendingComponent.tsx
packages/router-plugin/tests/code-splitter/snapshots/react/2-components-combined-loader-separate/production/random-number@component---errorComponent---notFoundComponent---pendingComponent.tsx
packages/router-plugin/tests/code-splitter/snapshots/react/3-all-combined-errorComponent-separate/development/random-number@component---loader---notFoundComponent---pendingComponent.tsx
packages/router-plugin/tests/code-splitter/snapshots/react/3-all-combined-errorComponent-separate/production/random-number@component---loader---notFoundComponent---pendingComponent.tsx
pnpm-lock.yaml

fix: bump babel-dead-code-elimination

---

examples/react/start-basic-auth/src/routes/_authed.tsx
examples/react/start-basic-auth/src/routes/signup.tsx
examples/react/start-supabase-basic/src/routes/_authed.tsx
examples/react/start-supabase-basic/src/routes/signup.tsx

fix: start auth examples send credentials in GET

---

docs/router/framework/react/devtools.md

Edits the way devtools are installed

docs: devtools installation

---

docs/router/framework/react/quick-start.md
docs/router/framework/react/routing/installation-with-vite.md

start a new project without using start-kit or copy vite config from doc, and stuck with vite plugin order issue for hours 😂
better living a note in doc

add comment for vite plugin order 

---

packages/router-plugin/src/core/router-generator-plugin.ts

hi,
I pulled in the router into an existing webpack based project. When trying to build the project, webpack was hanging indefinitely as it was a development mode run.
I tracked the problem down to a chokidar watcher that is registered independent of the webpack command used.
This pr fixes that problem by restricting the watcher to only be registered when webpack [watchMode](https://webpack.js.org/api/compiler-hooks/#watching) is enabled.
Thanks,
Valentin

fix(router-plugin): avoid blocking webpack build command

---

docs/router/framework/react/quick-start.md
docs/router/framework/solid/quick-start.md

docs: improves react/solid quick-start docs

---

packages/router-vite-plugin/README.md

fix the uptdated link for file base routing

---

packages/start-plugin-core/src/start-server-routes-plugin/plugin.ts

fix(start-plugin-core): remove backslashes from declaration import

---

packages/react-router/src/route.tsx
packages/router-core/src/index.ts
packages/router-core/src/route.ts
packages/solid-router/src/route.tsx

fix: type errors

---

packages/start-plugin-core/src/plugin.ts

fixes #4285
fixes #4195
fixes #4182

fix: exclude virtual modules from optimizeDeps

---

packages/router-core/src/router.ts

fix: do not start a view transition when invalidating

---

docs/start/framework/react/server-routes.md

Update server-routes.md to add missing /api/ in route mapping

---

examples/react/start-basic/src/utils/loggingMiddleware.tsx

Duration calculation error in example code

---

packages/router-generator/src/generator.ts

fix: swap caches also when not writing route tree file

---

packages/server-functions-plugin/src/index.ts
packages/start-server-core/package.json
packages/start-server-core/src/createStartHandler.ts
packages/start-server-core/src/server-functions-handler.ts
packages/start-server-core/src/tanstack-start.d.ts
pnpm-lock.yaml

also use filter for server-functions-plug
also fix types

 fix: provide dummy server function manifest to client env

---

e2e/react-start/basic-auth/src/routes/__root.tsx
e2e/react-start/clerk-basic/src/routes/__root.tsx
examples/react/start-basic-auth/src/routes/__root.tsx
examples/react/start-clerk-basic/src/routes/__root.tsx
examples/react/start-supabase-basic/src/routes/__root.tsx
examples/react/start-workos/src/routes/__root.tsx

As described here: https://tanstack.com/router/latest/docs/eslint/create-route-property-order

fix: move beforeLoad property before head property when creating route

---

docs/router/api/file-based-routing.md

Fix typo in file-based-routing.md

---

packages/router-generator/src/generator.ts

fix: preserve file owner and permissions when rewriting file in generator

---

examples/react/start-basic/src/routes/api/users.ts
packages/directive-functions-plugin/package.json
packages/router-plugin/package.json
packages/server-functions-plugin/package.json
packages/start-plugin-core/src/compilers.ts
pnpm-lock.yaml

fix: correctly handle multiple imports of `@tanstack/react-start/server`

---

docs/router/framework/react/api/router/RouterType.md
packages/router-core/src/router.ts

feat: add `forcePending` to `router.invalidate()`

---

packages/react-router/src/ScriptOnce.tsx
packages/react-router/src/scroll-restoration.tsx
packages/solid-router/src/ScriptOnce.tsx
packages/solid-router/src/scroll-restoration.tsx

several people asked about it on discord, sometimes it is annoying to wade through these logs
https://github.com/TanStack/router/pull/4600 needed to be merged first

fix: remove debug log

---

docs/start/framework/react/static-prerendering.md
packages/start-plugin-core/src/nitro-plugin/plugin.ts

fix: allow prerender if no pages specified

---

docs/start/framework/react/server-routes.md

Blocked by: https://github.com/TanStack/tanstack.com/pull/430

Remove todo from Server Routes docs

---

packages/router-plugin/src/core/router-composed-plugin.ts

From: https://discord.com/channels/719702312431386674/1393551176040976384

fix(router-plugin): composed plugin to consider options from json config

---

packages/react-router/tests/not-found.test.tsx
packages/router-core/src/path.ts
packages/router-core/src/router.ts

fix: re-enable fuzzy matching to allow notFoundMode: fuzzy

---

docs/router/framework/react/api/router/RouterType.md

docs: update matchRoutes props

---

e2e/react-router/basic-scroll-restoration/src/main.tsx
e2e/react-router/basic-scroll-restoration/tests/app.spec.ts
e2e/react-start/scroll-restoration/public/script.js
e2e/react-start/scroll-restoration/public/script2.js
packages/router-core/src/scroll-restoration.ts

fix: scroll to top if no scroll restoration entry exists

---

e2e/react-router/scroll-restoration-sandbox-vite/tests/app.spec.ts
packages/react-router/src/scroll-restoration.tsx
packages/router-core/src/scroll-restoration.ts
packages/solid-router/src/scroll-restoration.tsx

fix: scroll to top with hash history

---

e2e/react-start/spa-mode/package.json
e2e/react-start/spa-mode/vite.config.ts
e2e/solid-start/spa-mode/package.json
e2e/solid-start/spa-mode/vite.config.ts
packages/router-core/src/router.ts
packages/start-plugin-core/src/nitro-plugin/plugin.ts
packages/start-plugin-core/src/nitro-plugin/prerender.ts
packages/start-plugin-core/src/plugin.ts
packages/start-plugin-core/src/schema.ts
packages/start-server-core/src/createStartHandler.ts

fix: prerending with SPA mode enabled renders all routes

---

docs/router/framework/react/guide/document-head-management.md

RouteOptions.scripts is supposed to be a function, not an array. ask me how i know

Fix code example typo in document-head-management.md

---

docs/router/framework/react/guide/deferred-data-loading.md
docs/router/framework/react/guide/external-data-loading.md

Updated old link + typo in docs

docs(router): update URL for Query

---

packages/router-generator/src/config.ts
packages/router-generator/src/generator.ts

fix: do not create temp subdirectories for router generator

---

examples/react/start-material-ui/vite.config.ts

examples: @mui/material example re-add ssr.noExternal to vite config

---

packages/react-router/src/useBlocker.tsx
packages/router-core/src/router.ts
packages/solid-router/src/useBlocker.tsx
packages/start-server-core/src/createStartHandler.ts

fix: do not pre-decodeURI before passing to createMemoryHistory

---

README.md

fix: RELEASE_ALL
