TanStack/router

packages/react-location/package.json

The main npm package is missing links to repository and homepage.
As a consequence, the links are not displayed at https://www.npmjs.com/package/react-location.
Other tools like Moiva.io that rely on that information can't provide valuable information.
This PR adds the missing information

add links to repository and homepage

---

docs/src/pages/comparison.md
docs/src/pages/docs/api.md
docs/src/pages/guides/history-types-and-location.md
docs/src/pages/guides/pending-states.md
docs/src/pages/guides/route-elements.md
docs/src/pages/guides/route-loaders.md
docs/src/pages/guides/routes.md
docs/src/pages/index.js
docs/src/pages/overview.md
docs/src/pages/quick-start.md
docs/src/pages/tools/devtools.md
docs/src/pages/tools/ranked-routes.md
docs/src/pages/tools/simple-cache.md

These are just the most obvious typos and grammatical changes I could make. I went through every docs page simply ensuring that what I was reading made sense and try to spot errosr.
---
Sidenote: I also noticed 4 empty markdown links:
Line **186** and line **190** in `guides/routes.md`
But I had an issue running docs locally and did not want to make a change that I could not verify works.

Fix typos and grammar issues in docs Home and Supporting pages

---

docs/src/pages/guides/pending-states.md
docs/src/pages/guides/route-loaders.md

- Add `async` to `pendingElement` callback on Pending States page
- Fix a dead link on Route Loaders page

Documentation fixes

---

packages/react-location/src/index.tsx

The rejectLoader call inside of reject was causing the loader promise to never finish.  Removing it makes the error elements work, as well as the default error page in cases where there are no error elements

fix: remove rejectLoader call inside of reject function

---

packages/react-location/src/index.tsx

This would fix #162  which also caught me off guard. I'm not sure if you should even need to set `pendingMs` if you set `pendingElement`, but I think if you set `pendingMs` to 0, you'd want it to always enter the pending state immediately.

Enter pending state if pendingMs is set to 0 ms

---

examples/basic/public/index.html
examples/kitchen-sink/public/index.html
examples/with-react-query/README.md
examples/with-react-query/public/index.html
examples/with-simple-cache/public/index.html

Just something I found in the code while looking at old pr's. It seems like that it should be npm on the places I've changed it.
Happy new year!

docs(npm/yarn commands): change yarn to npm command in docs

---

docs/src/pages/guides/routes.md

A route defined as '/' with a parent of dashboard will match /dashboard

fix route match description

---

docs/src/pages/guides/routes.md

Replaces a mistaken sing-quote with a back-tick for formatting purposes

fix Routes documentation typo

---

rollup.config.ts

After [#780ae4](https://github.com/TanStack/react-location/commit/780ae4072e9e150d987bbd1d3ef30ace3078d5e5), rollup started outputting the UMD bundle as `/build/umd/index.production.js` instead of `/build/umd/index.production.min.js`. This breaks build tools (Vite, Parcel, etc.) that use the `browser` value from each packages `package.json`.
I figured the correct output would be `/build/umd/index.production.min.js`, but we might want to update each package's `browser` value instead to point to the new `/build/umd/index.production.js`.
I was going through this issue in a project using Parcel v2. I tested this change by applying this change, running `yarn run build` and `yarn run linkAll`, and linking the libraries locally. My test project did use all packages, only `react-location` and …

fix: rollup umd output name

---

packages/react-location/src/index.tsx

This change will prevent a `<Link />` element from navigating if the disabled prop is true,
The route will still prefetch on hover when disabled which I could also disable if requested.
Fixes #230

fix: make disabled prop work correctly on Link

---

docs/src/pages/guides/history-types-and-location.md

I was trying to use the initial URL for `createMemoryHistory` from the examples and it was not working. I looked through the history package docs and this is the proper way for setting the `initialEntries` to set a default URL.

Fix initial entries example for createMemoryHistory

---

examples/with-simple-cache/package.json
examples/with-simple-cache/src/index.tsx

The code sandbox widget was throwing errors due to missing dependency in the package JSON file in this Demo URL.
```
https://react-location.tanstack.com/examples/with-simple-cache
```
This PR fixes that issue and also, updated the path for the homepage route to `/home` since the demo page was throwing errors due to duplicate keys.

Fix with-cache example project with missing dependency and duplicate route key issue

---

.browserslistrc

Hi @tannerlinsley, thank you for making nice libraries!
fix #227 
After 780ae4072e9e150d987bbd1d3ef30ace3078d5e5, this library depends on `regeneratorRuntime` but does not include it.
No target is specified for @babel/preset-env,
[the default configuration](https://babeljs.io/docs/en/options#no-targets) is applied and async functions are converted to `regeneratorRuntime`.
So my suggestion is to add `.browserslistrc` (not includes IE) and deploy async functions. 
Config file in this PR is based on [react-router configuration](https://github.com/remix-run/react-router/blob/7dca9dc38c837ed94796325b1e0582aa72a9313f/.browserslistrc).

chore: add browserslist config

---

docs/src/pages/guides/routes.md

There is a cool feature I found that is kind of hidden in the API reference documentation.
If you want to match by search params and you have two routes that only differ by a search param, you need to supply a unique id to each route.

Update Search Matching Documentation

---

docs/src/pages/docs/api.md

In react-location [api document](https://react-location.tanstack.com/docs/api#usesearch) with `useSearch` hook.
there is wrong typo in example code.
AS-IS
```ts
type MyLocationGenerics = MakeGenerics<{
Search: {
pagination?: {
index?: number
size?: number
}
filters?: {
name?: string
}
desc?: boolean
}
}>
>
```
TO-BE
```ts
type MyLocationGenerics = MakeGenerics<{
Search: {
pagination?: {
index?: number
size?: number
}
filters?: {
name?: string
}
desc?: boolean
}
}>
```

fix: fixed api useSearch MyLocationGenerics typo

---

packages/router-core/src/createRoutes.test.ts
packages/router-core/src/index.ts

I have added the typescript types for gradual autocomplete of the paths as mentioned in Matt's discord
Now when autocompleting on `route.link` it will suggest relative paths

working gradual autocomplete for relative paths

---

docs/src/pages/guides/custom-search-param-serialization.md

Update: In https://github.com/TanStack/router/commit/59cd694ecadd9ea626d0284cced1adc2c6ac3ef1#diff-e9e4886c0ad5e55485f3f74b95980d5f1271e4d360a6be9c7bc96f5e81fd4c5aR83-R99 you added the custom encoder/decoder but did not use the inside the Zipson example, which is what this PR fixes.
~~Zipson provides it's own parse/stringify methods, which are correctly imported in the example. However, when the example was added, instead of using `parse` the code said 'btoa' which is likely a copy-paste-error, see https://github.com/TanStack/router/commit/6dd728355b7a4b3be112b7eb897bac06b48fa65b#diff-e9e4886c0ad5e55485f3f74b95980d5f1271e4d360a6be9c7bc96f5e81fd4c5aR42-R58. And later in https://github.com/TanStack/router/commit/59cd694ecadd9ea626d0284cced1adc2c6ac3ef1#diff-e9e4886c0ad5e55485f3f74b95980d5f12 …

Docs: Cleanup Zipson example

---

docs/guide/actions.md
docs/guide/caching.md
docs/guide/links.md
docs/guide/loaders.md
docs/guide/preloading.md
docs/guide/route-matches.md
docs/guide/router.md
docs/guide/routes.md

A couple of the documentation pages already have TODO placeholders but others are currently 404ing due to a missing markdown file. This PR fills in TODO placeholders for each guide that returns a 404.
https://tanstack.com/router/v1/docs/guide/router
https://tanstack.com/router/v1/docs/guide/links
https://tanstack.com/router/v1/docs/guide/routes
https://tanstack.com/router/v1/docs/guide/route-matches
https://tanstack.com/router/v1/docs/guide/loaders
https://tanstack.com/router/v1/docs/guide/actions
https://tanstack.com/router/v1/docs/guide/caching
https://tanstack.com/router/v1/docs/guide/preloading

Docs: Add missing docs pages

---

packages/react-location/src/index.tsx

Fixes #255
- We set the `RouteMatch` status after loading the elements and (optional) loader
- The loader can also set the status
- Thus, we only set the `resolved` status for `RouteMatch`'es without loaders, to prevent overriding the status set by the loader
I guess you could rework this logic many ways but i thought this was the easiest to follow.

fix: render errorElement when route loader is rejected

---

packages/react-router/src/index.tsx

This error currently logs out as this example:
`Did you mean to 'useMatch(/manage/:resource, { strict: false })' or 'useRoute(/manage/:resource)' instead?`
Both examples are missing quotation marks to be valid TS.

include quotes in invariant error message

---

packages/react-router/src/index.tsx

The problem seems to be the fault of `startTransition` from React 18.
I applied a plaster fix to check whether that method exists and if not to go and execute `handleClick` directly.

Link component throws when clicked on React < 18

---

.github/ISSUE_TEMPLATE/bug_report.yml

continuation bugfix of #436
without this, github thinks the link is local and trys to navigate to non-existing page

fix: add `https://` to bug report

---

packages/react-router/src/index.tsx
packages/router-core/src/router.ts

- restores `router.history` in the public API or router-core
- restores usePrompt block / unblock behavior

fix: restore router.history and usePrompt behavior

---

packages/router-cli/src/generator.ts

This PR fixes the backslash import when generating routes on windows, replace ```\``` to ```/```
https://github.com/TanStack/router/issues/465

fix(router-cli generator): fix generated import

---

package.json
packages/react-router-devtools/package.json
packages/react-router/package.json
pnpm-lock.yaml

Inside of a pnpm workspace, other packages in the same workspace should be referenced in `package.json` via a `workspace:` version.
This PR adds fixes this in the repo and changes `workspace:*` to `workspace:^`, which will publish to the `^x.x.x` version number scheme most common in JS projects, as opposed to an exact `x.x.x` version

Referencing pnpm workspace packages incorrectly

---

packages/router-cli/src/transformCode.ts

Using posix style path for the routeConfig import statement in the transformed code. [This PR](https://github.com/TanStack/router/pull/469) corrected this issue in some areas but the transformed code is still affected.

Update the routeConfig import on windows.

---

packages/react-router/src/index.tsx

The `useNavigate` hook currently returns a function. Inside this returned function, the `useRouter` hook is used. Since the returned function itself is not a hook, a violation of the react hook rules is triggered.
```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
You might have mismatching versions of React and the renderer (such as React DOM)
You might be breaking the Rules of Hooks
You might have more than one copy of React in the same app See for tips about how to debug and fix this problem.
```
Moving the `useRouter` call outside the return statement should mitigate this issue.

Fix useNavigate hook

---

docs/guide/route-paths.md

As [seen in the Issues](https://github.com/TanStack/router/issues/496#issuecomment-1386695452), there is possibility of confusion in the way that non-index routes render both when terminal *and when intermediate* in the whole URL path, and how this can cause children to be missing if the parent lacks an `<Outlet/>`.

Clarify missing-outlet -> missing-children concept

---

docs/comparison.md

Updated the documentation's Next.JS link: https://tanstack.com/router/v1/docs/comparison

docs: update nextjs link

---

packages/router/src/router.ts

Following on from #523, this PR ensures that errors thrown in `beforeLoad` and its error handler (either `onBeforeLoadError` or `onError`) are propagated to the nearest `errorComponent`.
Updated diagram from the previous PR (again assuming no preloading to keep things simple):
```mermaid
%%{
init: {
'theme': 'base',
'themeVariables': {
'secondaryColor': 'white',
'tertiaryColor': '#fff'
}
},
}%%
graph LR
subgraph Legend
direction LR
e1(( )) --->|Throw error| e2(( ))
er1(( )) --->|Throw error or return| er2(( ))
r1(( )) --->|Throw redirect| r2(( ))
h1(( )) --->|Happy path| h2(( ))
end
A[Load]
B[Render \n component]
C[Navigate]
D(beforeLoad)
E(onBeforeLoadError \n or onError)
F(validateSearch)
G(onValidateSearchError \n or onError)
H(onLoad)
I(onLoadError \n or onError)
J[Render nearest \n …
```

Propagate beforeLoad errors to nearest errorComponent

---

packages/solid-router/src/index.tsx
pnpm-lock.yaml
scripts/config.ts

Posted two issues in the solid repo for suspense and error boundaries that we need to be resolved. In the meantime I've wrapped error boundary children with a div to resolve this.
https://github.com/solidjs/solid/issues/1542
https://github.com/solidjs/solid/issues/1543

Adding wrappers around the error boundaries for temporary patch

---

docs/guide/routes.md

ReactRouter have only a props `routeTree` not `routeConfig` either we do 
```ts
const router = new ReactRouter({routeTree:routeConfig})
```
or
```ts
const router = new ReactRouter({routeTree})
```

chore(docs): update routeConfig to routeTree

---

docs/guide/custom-search-param-serialization.md

JSURL was last updated in 2016 https://github.com/Sage/jsurl.
JSURL2 looks like a more active fork that is maintained https://github.com/wmertens/jsurl2.
It looks like [the PR](https://github.com/Sage/jsurl/pull/17) to publish an "official" v2 got stale in 2018.

search-param-serialization: Reference jsurl2

---

docs/config.json

It caused the error in documentation site.

Fix trailing comma in JSON file

---

examples/react/kitchen-sink-multi-file/src/routes/dashboard/dashboard.tsx

The kitchen-sink-multi-file example was showing following error when I was checking it out.
The fix was to write the correct import path.

fix: import in kitchen-sink-multi-file example

---

packages/router/src/react.tsx

Due to usage of `type ReactNode = any` it is not possible to correctly infer `isActive` argument type in Links with function as children.
I changed types to use `React.ReactNode` instead of `any`, and removed `React.AnchorHTMLAttributes<HTMLAnchorElement>` that were doubled and resulted in overriding `children`.
outcome:

fix: Link children types

---

packages/router/src/history.ts
packages/router/src/router.ts

I stumbled across the same problems that can be observed in https://github.com/TanStack/router/issues/542.
Found out that `parseLocation` was using `substring` and feeding it `-1` as the last parameter - which doesn't do what you'd expect it to. Replacing `substring` with `slice` fixes the hash-parsing.
I also observed that `#buildLocation` was prepending the returned hash-property with `#` even though the hash value already had the `#` prefix. This caused problems later on. Solved it by not prepending the `#`, but I'm unsure if this is the correct approach to the problem (?). Might be that the `#` prefix shouldn't have been in the `this.state.latestLocation.hash` value at all? In that case, the following might be the culprit:
https://github.com/TanStack/router/blob/7d3bfbfe3942220931c68f9 …

fix: hash values was incorrectly parsed in browser history mode

---

packages/router/src/react.tsx

This PR fix `useSearch` code that destructure the opts that maybe undefined

fix(useSearch): undefined params

---

packages/router/__tests__/createRoutes.test.ts

With #594 feature, a bug is introduced due to a const redeclaration.
Two routes with the same name `testRoute` are defined.
This bug brokes the ci because it brokes the tests
The two declarations are merged into a single one, preserving both the tests.
All tests now pass

fix: merge testRoute declarations into a single one

---

packages/actions/src/index.ts

Hello 👋
I see that `ActionClient` was reworked to be more in line with `LoaderClient`. The initialization uses the `getActions` to iterate over all actions and add them to `ActionClient` instance. However, the `Action#init` method doesn't return the action itself currently - causing errors when trying to access the action later with `useAction({key: 'foo_bar'})`.
This PR adds return to the `Action#init` method. 
Here you can see that result is used in `ActionClient#init` method:
https://github.com/TanStack/router/blob/6277e92a6f5ea94749802526794dfffa4ba5bedc/packages/actions/src/index.ts#L78
And here `Loader#init` for comparison:
https://github.com/TanStack/router/blob/6277e92a6f5ea94749802526794dfffa4ba5bedc/packages/loaders/src/index.ts#L314

fix: return action from init

---

packages/router/src/history.ts

fix: transposed href parts in browser history

---

examples/react/kitchen-sink-multi-file/src/router.tsx
examples/react/kitchen-sink-multi-file/src/routerContext.ts
examples/react/kitchen-sink-multi-file/src/routes/root.tsx

Without this change I get a blank page with the error `Uncaught ReferenceError: Cannot access 'routerContext' before initialization at root.tsx`. Here's a StackBlitz of the latest commit showing the issue: https://stackblitz.com/github/tanstack/router/tree/5547d5f0f3f142ce0a64047d476bc0f59d11f15b/examples/react/kitchen-sink-multi-file
Turns out it's because there's a circular dependency between `router.tsx` and `routes/root.tsx`. To fix this I've extracted `routerCounter` into its own file.

examples: fix routerContext circular dependency

---

packages/router/src/qss.ts

When parsing search params, strings are coerced to numbers at the whims of Javascript. This caused some weird conversions, like whitespace(s) being converted to `0`.
The new code checks if there is a detail loss before coercing, and doesn't convert if the detail is lost. This makes it possible to invert the conversion with zod or something else, because the converted number can be simply converted back to string without any loss of detail.
Should fix #537

fix(search-params): prevent detail loss when decoding search params

---

packages/router-core/src/searchParams.ts

This PR makes two changes.  I think these are better as the default behavior, but this could need reviewing.
- When stringifying arrays, individual elements are stringified first instead of the whole array. For example, `{ test: [1, 2, "a"] }` will be stringified as `?test=1&test=2&test=a` instead of `?test=[1,2,"a"]`
- When a string is already parseable, it will be stringified again, so that original value is returned when it is parsed again. This was an issue for strings like `'"test"'`, where when you tried to parse it was converted to `'test'` instead of `'"test"'`. This could be the issue described in #654.

fix(search-params): handle arrays and parseable strings when stringifying

---

packages/store/__tests__/index.test.tsx
packages/store/package.json
packages/store/vitest.config.ts

This PR works to add initial tests for TanStack Store, as an early method of helping me understand the store codebase and rationale.
The initial tests written include:
> This PR does not implement tests for the priority, as I could not figure out what intended behavior is supposed to be for that yet

Add store tests

---

docs/guide/custom-search-param-serialization.md

Added an example on how to use `parseSearch` and `stringifySearch` without the `parseSearchWith` and `stringifySearchWith` utilities.

docs: Add example for parseSearch and stringifySearch

---

packages/react-router/src/react.tsx

Addresses #722 and also fixes the `any` typing for `useMatchRoute` that I noticed while working on this.
The root of the problem seems to be that `rollup-plugin-dts` sees `RegisteredRouter` as `AnyRouter` while generating types, so any types using it get compiled down into `any` and `unknown`. The trick appears to be to define dynamic types that are set to `RegisteredRouter` by default, which tricks `dts` into leaving it alone.
For `useMatchRoute` because `const router = useRouter()` comes out typed as `AnyRouter` (since `useRouter` returns type `RegisteredRouter`), the `.matchRoute` call returns `any`. Therefore we have to explicitly type the return value to be the same as `Router.matchRoute`.
In `useMatchRoute` I also changed the type of `TFrom` to `RoutePaths<TRouteTree>` instead of …

Fix types for useNavigate and useMatchRoute

---

docs/guide/navigation.md

While browsing the source code for the `<Link>` component, I stumbled upon the fact that you can propagate the `isActive` prop to children if you provide a function for children. This seemed useful enough to document because it turned out to be the exact problem I was trying to solve, and couldn't find an official way to do so other than making my own `Link` component.

document passing Link isActive to children

---

.gitignore
docs/guide/custom-search-param-serialization.md
docs/guide/navigation.md
examples/react/file-based-routes/package.json
examples/react/file-based-routes/src/routeTree.gen.ts
packages/react-router/src/react.tsx
packages/router-cli/src/generator.ts
pnpm-lock.yaml

I searched `force-pushed in:#router-github-logs` on discord to get a list of all force pushes committed recently, but I only reviewed the ones since 8/29. Clicking on "compare changes" will take you to github showing the diff ([example](https://github.com/TanStack/router/compare/22365f00d5db...a8cd7cdb8302)), from there you can get the two git shas of "before" and "after". With those I opened the git log ([example](https://github.com/TanStack/router/commits/a8cd7cdb8302)) for each commit to see what commits were removed.
08/29/2023 2:38 PM `f83aac3`
- `529adea` [release: v0.0.1-beta.171](https://github.com/TanStack/router/commit/529adea5e6a73ab7783c47ad679ddb7cc31673aa)
08/29/2023 6:26 PM `d3c135b`
- `0f1e9ab` [release: v0.0.1-beta.172](https://github.com/TanStack/router/commit/0f1e9abe3a9 …

Fix force push removing commits

---

packages/router-cli/src/generator.ts

Running `tsr generate` with a route ending in `$` (a splat/wildcard/catch-all route) causes code in the route to be duplicated. If you run `tsr watch` it will endlessly duplicate the code, causing resource exhaustion of cpu and disk.
The underlying cause is that `$` has a special meaning when used in the replacement string for `.replace` and `.replaceAll` calls. Specifically `$'` means "replace this with everything after the matched string". Since splat routes end in `$` and the next character is `'` to represent the end of the routePath string, together it tells `.replace` to copy everything after the match, which is the entirety of the remainder of the file. This behavior is documented at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#spec …

Fix router-cli duplicating code for splat routes

---

packages/router-cli/src/generator.ts

When there are multiple nested layouts it is possible for the generator to not nest sub paths correctly.

Fixing Nesting Issues with multiple layouts

---

packages/router-cli/src/generator.ts

Hi 👋
Previously router-cli would ignore routeFilePrefix for `__root.tsx`. Assuming routeFilePrefix is set to `~`, a `~__root.tsx` would result in two import statements in routeTree.gen.ts:
- `import { route as rootRoute } from "./routes/~__root"` and
- `import { route as rootRoute } from "./routes/__root"`
This PR updates the import generation behaviour so that a `~__root.tsx` will only result in one import:
- `import { route as rootRoute } from "./routes/~__root"`
Which is inline with the behaviour described in the docs.

fix: routePathID now obeys routeFilePrefix

---

examples/react/basic-react-query-file-based/package.json
examples/react/location-masking/package.json

duplicate package name leads to the following error when trying to run `npm run dev` inside on any of the examples:
````
Error: must not have multiple workspaces with the same name
package 'tanstack-router-react-example-basic' has conflicts in the following paths:
/Users/user/source/tanstack/router/examples/react/basic
/Users/user/source/tanstack/router/examples/react/location-masking
at getError (/Users/user/.nvm/versions/node/v18.16.1/lib/node_modules/npm/node_modules/@npmcli/map-workspaces/lib/index.js:66:24)
at mapWorkspaces (/Users/user/.nvm/versions/node/v18.16.1/lib/node_modules/npm/node_modules/@npmcli/map-workspaces/lib/index.js:146:11)
at async Config.loadLocalPrefix (/Users/user/.nvm/versions/node/v18.16.1/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:677:28)
at …
```

fix: correct package name for example

---

packages/react-router/src/router.ts

Move changes to loadMatches
See #842 
handleErrorAndRedirect gets it own AbortController.
Then we refresh the AbortController on each route. In a new fresh case, each Route already has its own AbortController.

Update router.ts to fix AbortController

---

packages/react-router/src/router.ts

I know this is a niche issue but bear with me.
When using `@tanstack/react-router` in a monorepo setup and:
1. having `@types/node` installed at the root for build scripts
2. disabling `@types/node` in `packages/*/tsconfig.json` (i.e., `"types": []`) for react stuff
`@tanstack/react-router`'s use of the `NodeJS` namespace pollutes the monorepo's packages' global scope with Node's globals (e.g., `process`, etc.).
I hope this PR will fix that.

fix: prefer global `setTimeout`'s return type

---

packages/react-router/src/link.tsx
packages/react-router/src/routeInfo.ts
packages/react-router/src/utils.ts

fix: allow search routes to define search params that differ in types

---

docs/guide/data-loading.md

Hello, 
just fixed a small dead link in the docs. 
There is also a [dead link here](https://github.com/TanStack/router/blob/beta/docs/guide/external-data-loading.md?plain=1#L18). From what I can tell, tanstack/loaders is no longer a library and instead seems to be built into the router?
Should this be removed if so?

Fix link to external data loading

---

CONTRIBUTING.md
docs/guide/custom-search-param-serialization.md
docs/guide/data-loading.md
docs/guide/external-data-loading.md
docs/guide/route-masking.md
docs/guide/route-matching.md
docs/guide/routes.md
docs/guide/ssr.md

Hello,
while reading the doc I've noticed that some of the internal links are not working
1. Go on a section with a link to another docs section: E.g.:
https://tanstack.com/router/v1/docs/guide/route-matching#pathless-route-matching
2. Click on "pathless routes" link
3. 404 page is shown
<details>
<summary>Here a complete list (from VS code find inside `docs` folder)</summary>
```
docs/guide/custom-search-param-serialization.md:
8  
9: To do so, [use `Router`'s `parseSearch` and `stringifySearch` options](../docs/api#search-param-parsing-and-serialization):
10  
35  
36: Additionally, you can [use the `parseSearchWith` and `stringifySearchWith` utilities](../docs/api#search-param-parsing-and-serialization) to parse and serialize the search values specifically.
37 …
```

docs: fix internal links

---

examples/react/kitchen-sink-file-based/src/routes/expensive/-components/Expensive.tsx
examples/react/kitchen-sink-file-based/src/routes/expensive/index.tsx
packages/react-router/src/Matches.tsx

There's probably something I completely missed, but this seems to fix the issues I reported in #881.
Tried to modify the generator in the CLI to make the paths match the final IDs of the routes, but ran into issues since the underscores seem to get used in the TS magic and didn't feel comfortable changing those types.
Also made the route matching first try to match the routeId as given and fallback to the opts.from without a `/` as last char.
Also added an example of RouteApi being used in a lazy-loaded component.

Update logic to retrieve matching routes

---

packages/react-router/src/RouterProvider.tsx
packages/react-router/src/link.tsx
packages/react-router/src/useNavigate.tsx
packages/react-router/src/utils.ts

Given the following example:
```tsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import {
Outlet,
RouterProvider,
Route,
Router,
rootRouteWithContext,
useNavigate,
} from '@tanstack/react-router'
import { z } from 'zod'
const rootRoute = rootRouteWithContext()({
component: () => <Outlet />,
})
const routeWithSearchAndPath = new Route({
getParentRoute: () => rootRoute,
path: '/routeWithSearchAndPath/$id',
validateSearch: z.object({
foo: z.number().catch(1),
filter: z.string().optional().catch(''),
}),
component: () => {
return null
},
})
const routeWithoutSearchOrPath = new Route({
getParentRoute: () => rootRoute,
path: '/routeWithoutSearchOrPath',
component: () => null,
})
const routeWithSearch = new Route({
getParentRoute: () => rootRoute,
path: '/routeWithSearch', …
```

fix: do not use intersection for search and path params

---

examples/react/kitchen-sink/src/main.tsx
packages/react-router/src/RouterProvider.tsx
packages/react-router/src/link.tsx
packages/react-router/src/useNavigate.tsx

in loader.navigate / router.preload
also updated kitchen sink example
fixes #908

fix: fix "Type 'string' is not assignable to type 'undefined'"

---

examples/react/basic-file-based/src/routeTree.gen.ts
examples/react/basic-file-based/src/routes/_layout.tsx
examples/react/basic-file-based/src/routes/_layout/_layout-2.tsx
examples/react/basic-file-based/src/routes/_layout/_layout-2/layout-a.tsx
examples/react/basic-file-based/src/routes/_layout/_layout-2/layout-b.tsx
packages/react-router/src/fileRoute.ts

fix: type safe paths when using nested layout routes in file-based routing

---

docs/api/router-vite-plugin.md

The current links to the router-cli in the [Route Vite Plugin](https://tanstack.com/router/v1/docs/api/router-vite-plugin) are not working.

Fix links to router-cli in router-vite-plugin

---

packages/router-cli/src/generator.ts

https://nodejs.org/api/fs.html#fspromisesreaddirpath-options
Roughly speaking, should be faster in most cases.

readdir with withFileTypes: true

---

packages/react-router/src/router.ts

`pendingConponent` is not shown when `pendingMs` is 0.
Is that a bug or intended behavior?
I am using `Number.EPSILON` in the meantime.

fix `pendingComponent` not shown when `pendingMs` is 0

---

packages/react-router/src/Matches.tsx
packages/react-router/src/useParams.tsx
packages/react-router/src/useSearch.tsx
packages/react-router/src/utils.ts

also fix typing in select function of useSearch, useParams, useMatch etc.
fixes #1007

fix: omit `RootSearchSchema` from search param type

---

packages/router-vite-plugin/src/index.ts

Hot reload is not working properly on windows, `file` contains forward slashes, whereas `path.join(...)` contains backslashes.
One way to fix that is to normalize the file path before comparing the two.

fix: hot reload not working on windows

---

examples/react/basic-ssr-file-based/package.json
examples/react/basic-ssr-streaming-file-based/package.json
examples/react/vinxi-basic-ssr-streaming/package.json
examples/react/vinxi-basic-ssr/package.json
examples/react/vinxi-basic/package.json
examples/react/wip-with-bling/package.json
package.json
packages/react-cross-context/package.json
packages/react-router-server/package.json
packages/react-router/package.json
packages/react-router/src/router.ts
packages/router-devtools/package.json
packages/router-generator/package.json
pnpm-lock.yaml

- Used `@manypkg/cli` and `sherif` to find and fix (most) reported monorepo errors
- Fixed complaints regarding peerDeps missing from devDeps
- Removed `@tanstack/store` (re-exported from `@tanstack/react-store`)
- Removed unused dependencies from `@tanstack/react-router-server`

refactor: Sync monorepo dependency versions, remove unnecessary deps

---

examples/react/basic-default-search-params/package.json
packages/react-router/package.json
pnpm-lock.yaml

Zod was installed at the root-level, but was not a dependency of the `basic-default-search-params` example.

chore: Add zod to example and as devDep of react-router

---

packages/router-devtools/src/devtools.tsx

The dev tools respect the project's direction whether It's `ltr` or `rtl`
If the direction was `rtl`, the panel's layout will result in the following image
Make the panel's direction consistent by setting Its direction to `ltr`
That would make the layout the same in both directions

fix: Ensure consistent dev tools panel direction in RTL projects

---

packages/react-router/src/RouterProvider.tsx

Without this HMR of routes just doesn't work for code base routing.
I think the example should be updated to provide better HMR pattern, and least have something like:
```tsx
// App.tsx
export function App() {
return <RouterProvider router={router} />;
}
// main.tsx
createRoot(document.getElementById('app')!).render(<App />);
```
Also the current setup for file base routing is lying to the Refresh runtime by using export with capital letter that are not React component. This leads to broken HMR update when updating the props of the exported Route. This seems to be an issue way deeper in the architecture so I can't really fix it here.

Handle router prop update in RouterProvider

---

packages/react-router/src/Matches.tsx
packages/react-router/src/useParams.tsx
packages/react-router/src/useSearch.tsx
packages/react-router/src/utils.ts

type path / search params as a partial intersection in `useMatch`, `useMatches`, `useParentMatches`, `useParams` and `useSearch`

feat: add option `experimental_returnIntersection`

---

docs/guide/navigation.md

- fixes a typo in the docs for the `ToOptions` interface in the [navigation page](https://tanstack.com/router/v1/docs/guide/navigation#tooptions-interface).

fix: typo on navigation.md

---

packages/router-generator/src/config.ts
packages/router-vite-plugin/src/index.ts

Hey,
I noticed that the vite-plugin was not using `getConfig` of `router-generator`. Therefore the disableTypes logic with the ts|tsx replacement in the `generatedRoutTree`-File did not work.
This PR fixes the issue.
best regards

Make use of router-generator's getConfig function at router-vite-plugin

---

packages/react-router/src/RouterProvider.tsx

I was having problems with the `buildLocation` function which was giving me inconsistent type errors when compared to the `navigate` function and the `Link` component. After some investigation it became clear that the root cause of the problem is a simple mistake in the `BuildLocationFn` type definition, which is missing some generics..... maybe someone forgot to add them.
Making a comparison with the `NavigationFn` type, which is right above:
```tsx
export type NavigateFn<TRouteTree extends AnyRoute> = <
TFrom extends RoutePaths<TRouteTree> | string = string,
TTo extends string = '',
TMaskFrom extends RoutePaths<TRouteTree> | string = TFrom,
TMaskTo extends string = '',
>(
opts: NavigateOptions<TRouteTree, TFrom, TTo, TMaskFrom, TMaskTo>,
) => Promise<void>
```
`BuildLocationFn` works …

fix: typsafety of BuildLocationFn missing Generics

---

packages/react-router/src/lazyRouteComponent.tsx

Fixes #1077 
- Video before fix: https://d.pr/v/IYi6II/wd5rvcvkBl
- Video working after fix: https://d.pr/v/r3qnuk/7TSXXTOfUz
It's a very weird thing to fix, so really not sure how we test this properly in the repo.
Also, I think window.location.reload isn't the right answer when in-memory router is used, since in this case the context won't be preserved on refresh.
**Todos**

Add 404 handler for lazyRouteComponent

---

examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.users.tsx

Fixed kitchen sink broken example by importing missing creteFileRoute.

docs: fix missing import createFileRoute in dashboard.users.tsx

---

packages/react-router/src/router.ts

Currently any usage of Router is displayed as deprecated, eg. even in parameter definitions such as `function myFn(router: Router, ...) { ... }`.
I believe the intention was to only deprecate the constructor so move the comment there instead.

Fix location of `new Router` @deprecated comment

---

docs/framework/react/api/router/matchRouteComponent.md
packages/react-router/src/Matches.tsx

do not require to specify path params

fix: `MatchRoute` now uses same props as `useMatchRoute`

---

packages/router-generator/src/generator.ts

Fixes #1110
See #1110.
Prefixes route path variables with a `_` if the leading character is numeric, e.g. turning `500IndexRouteImport ` into `_500IndexRouteImport `.
From my testing, this seems to be the only change required to fix the issue. And feel free to change the prefixed character to something more suitable!

fix: fix route variable generation for paths with leading digits

---

packages/router-generator/src/generator.ts

The fix added in https://github.com/TanStack/router/pull/1111 doesn't actually get applied since the [replace on line 549](https://github.com/TanStack/router/blob/cd1b62f16cd35e601c32710049b4b7497cb1dc59/packages/router-generator/src/generator.ts#L549) removes any non-alpanumeric characters again. 🙈
This PR moves it to after the final replace and replaces the prefixed `_` with a `R` (for Route) in case the underscore removal is intentional for other reasons. Feel free to change it back if it's safe 👍

fix: ensure generated routes with leading digits get prefixed correctly

---

package.json
pnpm-lock.yaml

Current `execSync('pnpm install')` error is unintelligible. It also can't be replicated locally for whatever reason. This update will help debug the cause.

ci: Improve TanStack Config publish console error

---

package.json
packages/react-router-server/vite.config.ts
pnpm-lock.yaml

`vite-plugin-replace` was last updated >3 years ago. `@rollup/plugin-replace` is maintained, and fully compatible with Vite. The `@tanstack/react-router-server` build output is unchanged by this PR.

chore: Replace `vite-plugin-replace` with `@rollup/plugin-replace`

---

packages/router-vite-plugin/src/index.ts

fix: handle absolute routesDirectory path in Vite plugin

---

docs/framework/react/devtools.md

When including the lazy devtools component into the root route as described in the docs I received this error. 
It might be nice to mention that this should be wrapped in a suspense component. If there is a better way of handling this I'm open to tweaking the docs.

docs: add suspense note for lazy devtools component

---

packages/react-router/src/link.tsx

Pretty important one here, still possible to preload a disabled link

When link is disabled, disable all events that could lead to preload

---

packages/router-generator/src/generator.ts

Ensure proper usage of singular or plural form for the word 'routes' following generation of the route tree.

fix: correct usage of singular or plural in log message

---

docs/framework/react/guide/file-based-routing.md
packages/router-generator/src/config.ts
packages/router-generator/src/generator.ts

Hey !
Thanks for the great work with all the TanStack packages.
I'm trying to use `@tanstack/router-vite-plugin` in a project where I'm using `"moduleResolution": "NodeNext",` and i'm unable to use the `bundler` module resolution in my monorepo, I have packages shared between my backend and my frontend code.
Best.

Option to add files extensions

---

docs/framework/react/guide/route-trees.md

There was missing `.tsx` extension in flat route tree (notifications)

docs: Added missing .tsx extension in flat based routes

---

docs/framework/react/api/router/NotFoundRouteClass.md
docs/framework/react/guide/code-splitting.md
docs/framework/react/guide/file-based-routing.md
docs/framework/react/guide/not-found-errors.md
docs/framework/react/guide/route-masking.md

Remove .md suffix from guide links

---

packages/router-devtools/src/devtools.tsx

I want to use `TanStackRouterDevtoolsPanel` in my app because i have custom trigger button, but if i don't want to implement the resize functionality myself and i have to pass `()=>{}` to `handleDragStart`, which i want to avoid.

Declare `handleDragStart` as optional

---

.github/workflows/ci.yml
.github/workflows/pr.yml
.gitignore
.nx/workflows/dynamic-changesets.yaml
examples/react/kitchen-sink-file-based/src/routes/expensive/index.lazy.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/expensive/index.lazy.tsx
nx.json

See here: https://github.com/TanStack/query/pull/6863

ci: Use Nx Agents

---

docs/framework/react/guide/data-loading.md

Previously, there was a wrong type of a backtick which caused weird formatting.
Before:
Now:

Fix formatting in Data Loading guide

---

examples/react/basic-react-query-file-based/src/routes/__root.tsx

Without the space, the header with links looks squashed and feels like there are only 2 links:
With the space, the `Layout` link is separated as it should be:

Add a missing space in header of basic-react-query-file-based example

---

docs/config.json
docs/framework/react/decisions-on-dx.md
docs/framework/react/dx-design-decisions.md

Prompted from this [discord thread](https://discord.com/channels/719702312431386674/1210411302405672980), this page covers why the DX decisions that have been made TSR are what they are.
It covers:
1. Why the router's configuration is done the way that it is.
2. Why typescript module declaration is used for propagating the types across a project.
3. Why is file-based routing preferred over code-based routing.
I did my best to write it in such a way that it makes it easy for more items to be added onto this list in the future.

docs: new doc page on the dx design decisions

---

docs/framework/react/guide/external-data-loading.md

Just gave a codebase a once-over for anything regarding Tanstack Query that used anything that wouldn't be available in v5.
Didn't touch anything under `examples/react/wip-*`.

docs: fix `queryKey` to be compliant with the current tanstack-query v5 syntax

---

docs/framework/react/decisions-on-dx.md

Removed the '.md' portion from the links, which was causing the incorrect redirect.

docs: fix links in Decisions on DX page

---

packages/react-router/src/RouterProvider.tsx
packages/react-router/src/fileRoute.ts
packages/react-router/src/link.tsx
packages/react-router/src/route.ts
packages/react-router/src/routeInfo.ts
packages/react-router/src/router.ts
packages/react-router/src/useNavigate.tsx

- Use template literal types to autocomplete relative paths. This eliminates recursion depth limits and is faster than splitting the union into tuples
- Only remove trailing and leading slashes instead of cleaning the whole path. I'm hoping that this is OK as its more performant
- Reduce instantiations by using a more concise way of writing `ParseRoutes`
- navigate now has the same performance improvements as useNavigate
- Make `TPath`, `TContext` and `TAllContext` invariant as this reduced extra checking
- Resolving the full path for relative paths wasn't always including '/' at the beginning
- Checking the resolved path wasn't working due to the resolved path including '/' at the end
- The documentation suggests that the default for `TFrom` should be '/'. This makes the logic simpler …

perf: improve typescript performance of relative pathing and larger route trees

---

CONTRIBUTING.md
README.md

I cloned the repo as the StackBlitz examples where a bit slow and got confused a bit when the `pnpm build` command did not work as I am unfamiliar with `nx`.
I updated the CONTRIBUTING.md guide to reflect that `pnpm build:all` should be run on initial clone.
May I suggest adding more info about running examples in the main README.md? A simple link to the CONTRIBUTING section like "To run examples, see CONTRIBUTING.md"

fix contributing guide to explicilty mention build:all command

---

docs/framework/react/guide/file-based-routing.md
examples/react/kitchen-sink-file-based/src/routes/(this-folder-is-not-in-the-url)/route-group.tsx
packages/react-router/src/fileRoute.ts
packages/router-generator/src/config.ts
packages/router-generator/src/generator.ts

since we need to handle the path replacements in typescript as well, we cannot let the user configure the route group pattern

fix: correct typing for route groups

---

docs/framework/react/guide/deferred-data-loading.md

Encountered a lack of async keyword resulting in TypeScript error: `TS1308: 'await' expressions are only allowed within async functions and at the top levels of modules.`

docs: make loader function async in deferred-data-loading guide

---

.prettierignore
README.md
docs/framework/react/api/router/createRootRouteWithContextFunction.md
docs/framework/react/api/router/useParamsHook.md
docs/framework/react/decisions-on-dx.md
docs/framework/react/devtools.md
docs/framework/react/guide/code-based-routing.md
docs/framework/react/guide/data-mutations.md
docs/framework/react/guide/deferred-data-loading.md
docs/framework/react/guide/file-based-routing.md
docs/framework/react/guide/history-types.md
docs/framework/react/guide/not-found-errors.md
docs/framework/react/guide/path-params.md
docs/framework/react/guide/route-trees.md
docs/framework/react/guide/router-context.md
docs/framework/react/guide/search-params.md
docs/framework/react/quick-start.md
packages/react-router-server/src/client.tsx
packages/react-router-server/src/server-fns/fetcher.tsx
packages/react-router-server/src/server-fns/handler.tsx
packages/react-router/src/Matches.tsx
packages/react-router/src/RouterProvider.tsx
packages/react-router/src/awaited.tsx
packages/react-router/src/fileRoute.ts
packages/react-router/src/link.tsx
packages/react-router/src/not-found.tsx
packages/react-router/src/redirects.ts
packages/react-router/src/route.ts
packages/react-router/src/router.ts
packages/router-devtools/src/devtools.tsx

- Reworks not-found errors and handling to better support SSR, including the ability to configure a default not-found component from the router
- Reworks redirect errors and handling to work for SSR
- Reworks error rendering to work for SSR
- Allows loaders to return never (for throwing redirects)
- Improves error handling and status code management for SSR
- Fixes a few edge cases where hovering or preloading a link would navigate to it

fix: ssr improvements

---

docs/framework/react/guide/file-based-routing.md
packages/router-generator/src/config.ts
packages/router-generator/src/generator.ts
packages/router-generator/src/utils.ts

Proposal to have a property on the config object to optionally disable logging. This would be relevant for my use-case, because I am experimenting with creating my own-stack on top of TanStack Router, and the logging of the route generation is messing with my logging.
- Adds `disableLogging` property to the config
- Adds `logging` function to utils
- Adds docs to document it

feat: disableLogging

---

packages/react-router/src/link.tsx

We should allow './' and '../' but to opt out of type safety

fix: allow '../' and './' without 'from' but lose type saftety

---

packages/router-generator/src/generator.ts

I fully acknowledge that this looks jank... there's no escaping this fact.
Most of it stems from having to short-circuit the `handleNode` function.
Fixes #1150

fix: incorrect route generation for nested layout routes

---

packages/router-generator/src/generator.ts

* fix: invalid generation of the route `id`s for layout routes in a nested folder (without a `route.tsx`) definition.
* fix: unintended spaces are being added into the initial *on-save* template.
* fix: child layout routes of already nested layouts not being attached correctly to their parents.
```
src/routes
index.tsx
nested/
_layout-a.tsx
_layout-a/
_layout-b.tsx <- parent will be `_layout-a.tsx`
_layout-b/
foo.tsx
```
closes #1279

fix(router-generator): invalid formation of `id`s and attaching of child layout routes 

---

docs/framework/react/guide/authenticated-routes.md

This extra `/react` was causing the Stackblitz to try and import a non existing path.
Checked the rest of codebase for similar errors, and couldn't find any other.

docs: fixed broken authenticated routes example url

---

packages/react-router/src/Matches.tsx

Fixes `notFound` errors not being deserialized on the client, leading to a failed `invariant` call. Reproduced [here](https://codesandbox.io/p/github/iDarkLightning/tsr-not-found-err/main?import=true). 
GH Repo of reproduction [here](https://github.com/iDarkLightning/tsr-not-found-err)

fix: deserialize notFound errors

---

packages/react-router/src/RouterProvider.tsx
packages/react-router/src/router.ts

Should fix: #1268 
With this fix, it should update the url search params according to the validateSearch zod schema so the visible url should match the router search state (except if masked is activated).
Update on` packages/react-router/src/RouterProvider.tsx` is a "revert" from changes made between `1.18.3` & `1.18.4`.
I don't know why this was deleted, maybe it's part of something I miss. If it's the case, ignore this PR.
If you need more precisions, let me know.

(fix) routers - update url search params according to validate search

---

packages/react-router/src/router.ts

We currently add `meta` `links` and `scripts` on the client even if the route is redirected or not found. This causes hydration errors, because the server does not add those properties. 
(Aside from that it also just doesn't make sense to load assets for a route that was not found and can potentially reveal unwanted info)

fix: don't hydrate assets for notFound or redirected matches

---

examples/react/basic/src/main.tsx
packages/react-router/src/link.tsx

Fixes #1302 by omitting the children property from `HTMLProps` when merging with `LinkProps`. Hopefully this fix isn't naive, this is one of my first OSS contributions.
I've also added some "function as child" usage to the basic example to act as a test, as I know this project doesn't have a proper test setup as of yet.

Fix type error when passing a function to Link's children

---

packages/react-router/src/RouterProvider.tsx

Fixes router url syncing for non-existent routes

fix: add `to` path when syncing url

---

examples/react/basic/src/main.tsx
packages/react-router/src/link.tsx

Fixes a bug where [destructing `LinkProps` into the props for a `Link` causes a type error](https://stackblitz.com/edit/tanstack-router-qmueor?file=src%2Fmain.tsx).
Similar to #1307, this omits the `preload` prop when merging `HTMLProps` and `LinkProps`.
I've also added a test to `examples/react/basic/src/main.tsx` with the intention of moving it to a more appropriate location once a testing framework is setup.

fix: Type error when passing props to `Link` via destructed `LinkProps`.

---

packages/react-router/src/link.tsx
packages/react-router/src/routeInfo.ts

- `TFrom` was being defaulted to `RoutePaths` due to the generic constraint. Causing performance issues.
- Use `RoutesByPath` instead of `Extract` for `RouteByPath`. This improves performance where `Link` has unique props and cannot be cached.
Ran diagnostics in `large-file-based`
Before:
```
Files:                         590
Lines of Library:            38118
Lines of Definitions:        77176
Lines of TypeScript:         12777
Identifiers:                113150
Symbols:                    376438
Types:                       81173
Instantiations:            4239852
Memory used:               403967K
Assignability cache size:   525762
Identity cache size:          3721
Subtype cache …
```

perf: improve performance of Link when navigating to unique routes

---

packages/react-router/src/link.tsx
packages/react-router/src/routeInfo.ts

- `Extract` would get a union of all routes when `string`. Keep the performance benefits but just return all routes if it is defaulted to a string
- I'm not sure if `ParamOptions` was handling if `TToParams` being a union of all params correctly as I was recieving issues where `search` was required where it should not have been

fix: allow 'to' to be a string

---

packages/react-router/src/link.tsx
packages/react-router/src/routeInfo.ts

- Allow `..` and `string` for `Link` but revert to all params union in this case

fix: allow '..' aswell as string for Link

---

packages/react-router/package.json
packages/react-router/src/routeInfo.ts
packages/react-router/tests/link.test-d.tsx

I've added some basic type tests for `Link`.
- Only testing public interface like `Link` and not internal types. We should be able to refactor the internal types and `Link`'s behavior should be the same
- I've avoided nesting in the tests. I personally find nesting hard to read and I don't mind repetition in tests.
- When I write a test case name I usually try to answer the following:  What scenario is being tested? What do I expect the result to be?

tests: add basic type tests for Link

---

docs/framework/react/api/router.md
docs/framework/react/api/router/RouteApiClass.md
docs/framework/react/api/router/getRouteApiFunction.md
docs/framework/react/api/router/useLoaderDepsHook.md
docs/framework/react/api/router/useParamsHook.md
docs/framework/react/api/router/useRouteContextHook.md
docs/framework/react/api/router/useRouterHook.md
docs/framework/react/api/router/useRouterStateHook.md
docs/framework/react/api/router/useSearchHook.md

Adding the missing documentation for the following hooks as documented in #1231.
The reference pages are being added for:
- useLoaderDeps
- useRouteContext
- useRouter
- useRouterState
- useSearch
Adding the *useNavigate* hook into the `RouteApi` reference page as one of the *typed hooks* being returned as implemented in #1350.

docs: add more missing reference pages

---

docs/framework/react/api/router/useMatchHook.md
packages/react-router/src/Matches.tsx

allows any currently rendered match to be retrieved

fix: loosen strict check in `useMatch`

---

packages/react-router/src/Matches.tsx

fix: do not use CatchBoundary if neither route nor router default error component is configured

---

docs/framework/react/guide/external-data-loading.md
docs/framework/react/guide/navigation.md

Removed references in the docs to TanStack Loaders (`@tanstack/loaders`) since we don't publish this package anymore for use with Router, and have the user rely on either the built-in loaders or external libraries like TanStack Query.

docs: remove references to `@tanstack/loaders`

---

docs/framework/react/guide/route-trees.md

Tiny PR on the docs to remove where a `__404.tsx` page is mentioned since it's not actually the right way of setting this up.
I find it a bit misleading. Maybe it was an old (removed) way of doing it?

docs: remove __404 mentions

---

packages/react-router/src/router.ts

The default pending component was popping up in routes without loader in the case when `pendingMs` [was evaluated as a number <= 0](https://github.com/TanStack/router/blob/main/packages/react-router/src/router.ts#L1239-L1240).
Since [these were met](https://github.com/TanStack/router/blob/main/packages/react-router/src/router.ts#L1499-L1501) in case @TkDodo outlined and the [`pendingPromise`](https://github.com/TanStack/router/blob/main/packages/react-router/src/router.ts#L1506) is indeed a promise in the [<= 0 number case](https://github.com/TanStack/router/blob/main/packages/react-router/src/router.ts#L1243), we observed the pending state.
Checking if route actually has a loader should fix it.
fixes #1349

fix: show pending component for routes with a loader

---

packages/react-router/src/link.tsx

because if it's named `Link`, the world explodes
refs #1271

fix: rename component created by createLink

---

docs/framework/react/guide/file-based-routing.md
packages/router-generator/src/config.ts
packages/router-generator/src/generator.ts

Accepts a `semicolon` property as part of the config that is used in the `router-generator` to format the generated `routeTree.gen.ts` with or without semicolons.
The *default* for the `semicolon` configuration property will be `false` (as it is currently).
Closes #1375

feat(router-generator): add option to format with semicolons in the generated route-tree

---

docs/framework/react/api/router.md
docs/framework/react/api/router/createLazyFileRouteFunction.md
docs/framework/react/api/router/createLazyRouteFunction.md

docs: add reference pages for `createLazyFileRoute` and `createLazyRoute`

---

docs/framework/react/api/router/FileRouteClass.md
packages/react-router/src/fileRoute.ts
packages/react-router/src/route.ts
packages/react-router/tests/fileRoute.test.ts
packages/react-router/tests/route.test.ts

As per our documentation, the `Route` and `LazyRoute` classes should have all the same typed-hook as the `RouteApi` class. However, with the addition of the `useNavigate` hook to the `RouteApi` class, we forgot to implement the hook onto the `Route` and `LazyRoute` classes as well.
Closes #1384

feat(react-router): implement the typed `useNavigate` hook onto the `Route` and `LazyRoute` class

---

packages/router-vite-plugin/src/index.ts

Something I've noticed, as stated in [this comment](https://github.com/TanStack/router/issues/1312#issuecomment-1999304792), is that the `router-vite-plugin` doesn't actually perform the whole route-tree generation process on file create and delete events.
* On create: You need to create the file, and then save it, to have the plugin actually do anything.
* On delete: You need to delete the file, and then go to another file and hit *save*, to have the plugin do anything.
This change uses the `watchChange` hook to trigger the route-tree generation process based on `create`, `update`, and `delete` events.

feat(router-vite-plugin): trigger the route-tree generation using `watchChange` hook

---

packages/react-router/src/link.tsx

When customising `Link` using `createLink` some props are set to undefined or an empty object.
When deconstructing these into the component they overwrite any props set by the component (as intended, if the props were actually set by the consumer).
eg the className set in the example below is overwritten with undefined from the props.
```
const MyStyledRouterLink = createLink(MyStyledLink);
function MyStyledLink({ children, ...props }: React.ComponentProps<"a">) {
return (
<a className="foo-bar" {...props}>
{children}
</a>
);
}
```
This PR contains a new example which can be removed if desired once the issue & fixed are confirmed.

fix: prevent props being populated with undefined or empty values

---

docs/framework/react/guide/code-based-routing.md
docs/framework/react/guide/route-matching.md

Hey! I'd like to suggest three changes which I think can improve the reading flow in the docs.
Code Based was pointing to File based saying "consider the same route tree" but there's no route tree on that page, it's on Route Trees & Nesting.
Same for the NotFound explanation, it's no longer in Route Matching but has a dedicated page so it's probably better to redirect the reader there.

docs: improve links to not found pages

---

packages/react-router-server/src/client/Meta.tsx
packages/react-router-server/src/client/Scripts.tsx

The props/attrs being spread into the `<Asset>` component of the `@tanstack/react-router-server` package contains a `key` attribute which when spread goes against how React expects that attribute to be used.
This sets the key to the asset component itself at render.
Could look at further optimization to not rely on the array index position, rather to be calculated based on the individual identifiable values.
Closes #1138

fix(react-router-server): do not spread a `key` prop inside the `<Asset>` component

---

docs/framework/react/quick-start.md

A developer following the Quick Start as it is currently written will run into an error when they create the first file, `src/routes/__root.tsx`:
```
Cannot find module '@tanstack/router-devtools' or its corresponding type declarations.ts(2307)
```
This is because the Quick Start does not instruct the reader to install this package anywhere in the guide. Many developers will understand that the package is missing from their project, and will install it on their own, but the lack of explicitness could discourage those with less experience or those for whom English is not their native language.

Update quick-start.md to include installation of devtools

---

packages/react-router/src/link.tsx

Closes #457 
This fix is applied to the `useLinkProps` hook, to use the initialized history instance to then `router.history.createHref` the actual `href` being returned by the hook.

fix(react-router): using the initialized history instance for creating the href on the Link component

---

docs/framework/react/guide/search-params.md

Self explaining. Fixing a wrong link.

docs: broken link to "using search params in loaders" in data-loading.md from search-params.md

---

packages/react-router/src/qss.ts
packages/react-router/tests/qss.test.ts

Updates the ﻿decode function to address parsing issues with querystrings with values containing trailing equal signs.
Previously, query strings like ﻿`token=foo=` were parsed incorrectly as ﻿`{ token: 'foo' }` instead of `﻿{ token: 'foo=' }`.
Closes #1404.

fix(react-router): incorrectly splitting the key-values pairs from the querystring

---

.github/ISSUE_TEMPLATE/bug_report.yml

The current one points you to something back in the beta versions.

Update bug_report template with latest Stackblitz links

---

packages/react-router/src/fileRoute.ts
packages/react-router/src/utils.ts

- made `Replace` tail-recursive
- cache type in FileRoutePath
- remove unused type and outdated comments

fix: type optimizations

---

packages/react-router/src/fileRoute.ts
packages/react-router/src/route.ts
packages/react-router/src/utils.ts

We need to avoid `TFullSearchParams` from being eagerly evaluated. This happened for a number of reasons.
- Generic constraints on `TFullSearchParams`. We need to get rid of these.
- Do not use `Omit` for `Assign` 
- Do not use `Expand`

perf: improve performance of search params merging

---

docs/framework/react/decisions-on-dx.md
docs/framework/react/quick-start.md

Investigation into the broken links found by @MarcoB-Ec lead me to discover these were broken in the top-level docs as well.

docs: fix broken links on top-level guides

---

docs/framework/react/api/router/RouteOptionsType.md
packages/react-router/src/route.ts

As we've now moved on to using `throw redirect(...)` for navigating a user to a different route in both the `beforeLoad` and `loader` callbacks, having the `navigate` function being present as an argument is not needed anymore.
Keeping the `navigate` function as an argument in these callbacks is no longer *necessary* and it is not *preload mutation safe*.

deprecate: `navigate` function as an argument in the `beforeLoad` and `loader` callbacks

---

packages/react-router-server/src/server/index.tsx
packages/react-router-server/src/server/transformStreamWithRouter.tsx

Add support for transforming ReadableStream instances to better support runtimes such as Bun/Deno.

feat: implement transformReadableStreamWithRouter

---

packages/react-router/src/Matches.tsx
packages/react-router/src/fileRoute.ts
packages/react-router/src/index.tsx
packages/react-router/src/link.tsx
packages/react-router/src/route.ts
packages/react-router/src/routeInfo.ts
packages/react-router/src/router.ts
packages/react-router/src/useParams.tsx
packages/react-router/src/utils.ts
packages/react-router/tests/link.test-d.tsx
packages/react-router/tests/route.test-d.tsx

Type checking large code bases with many `Route`'s and `Link`'s can get quite sluggish. This PR introduces a number of performance optimizations I've discovered while profiling on the large file based example. The purpose of this PR is to improve suggestion times for such code bases and build times
On main the following diagnostics are present for the example large file based
```
> tsc --extendedDiagnostics
Files:                         589
Lines of Library:            38118
Lines of Definitions:        77132
Lines of TypeScript:         12777
Identifiers:                113478
Symbols:                    351283
Types:                       62925
Instantiations:            1541766 …
```

perf: improve performance of Link and routes

---

docs/framework/react/guide/authenticated-routes.md

In the v1 and latest docs "Authenticated Routes with Context"  in the [Authenticated Routes Guide](https://tanstack.com/router/v1/docs/framework/react/guide/authenticated-routes) page is broken.
When I click goes to 404 page:
The correct link to the guide is: https://tanstack.com/router/v1/docs/framework/react/examples/authenticated-routes-context
The path was wrong, since all docs should be relative to `docs/` path I fixed by changing 
TO:
```md
[Authenticated Routes with Context example](./examples/authenticated-routes-context)
```
FROM:
```md
[Authenticated Routes with Context example](../../examples/authenticated-routes-context)
```

fix: broken "Authenticated Routes with Context" example link

---

packages/react-router/src/link.tsx
packages/react-router/src/routeInfo.ts
packages/react-router/tests/link.test-d.tsx

- Introduce `RouteLeaves` type to only autocomplete leaves
- We have to change `CheckPath` as well (yuck, I can't think of a better way)
- Add some type tests to cover only leaves

fix: only allow leaf nodes as `to` suggestions

---

docs/framework/react/guide/file-based-routing.md

docs: add a callout in the file-based routing options about not conflicting with the naming conventions

---

packages/react-router/src/Matches.tsx
packages/react-router/tests/Matches.test-d.tsx

Silly mistake by me! I've added a type test to cover it.
fixes #1533

fix: `to` should autocomplete for `MatchRoute`

---

packages/react-router/src/link.tsx
packages/react-router/tests/link.test.tsx

fix: persisting the 'disabled' prop for custom link elements using `createLink`

---

packages/react-router/tests/redirects.test.ts
packages/react-router/tests/router.test.ts

Add fixes and tests for `router.navigate` when using the `params: (prevParams) => newParams` option (with no extra `to` or `from` option).
Thanks to @SeanCassiere for the suggestion to patch `router.ts`
Fixes #1525
Should also fix https://github.com/TanStack/tanstack.com/issues/218

fix(react-router): changing path params without specifying the `to` destination

---

packages/react-router/src/router.ts

Don't skip navigation if `replace` is true or state has changed, even if the URL is unchanged.

Navigate on state change

---

packages/react-router/src/router.ts

Fixes #1540 
The current implementation doesn't push any promises into the `matchPromises` [array](https://github.com/TanStack/router/blob/a4a5b5e56879c7e27107bc9ac6408ce7c15207a6/packages/react-router/src/router.ts#L1582) and as such, the `parentMatchPromise` is always `undefined` in the loader.
This change now pushes the routes into the `matchPromises` array restoring its outer shell to what it was prior to Tanner's [commit](https://github.com/TanStack/router/commit/d09db60415b4a6e8b32ec771f53015666a5c52e2#diff-2ac234f610fa0e0c2146252c10a5266af9c5b6d0b63659a0fa4c9f2c4472596a) in 1.28.2.
Not sure if there's a reason why the current implementation doesn't make use of the `matchPromises` array, but this fix restores the lost functionality.

fix(react-router): incorrectly always returning `undefined` as `parentMatchPromise` in the loader in the child route

---

packages/history/src/index.ts

This change only affects memory history.
When using the `history.back`, it decrements the `index` by `-1`.
This is correct, since calling `history.forward` would require the `index` to be incremented by `+1` and would require an `entries` value to be present.
However, this then causes a scenario where calling `history.pushState` would cause the `entries` array to have an extra item with the `index` lagging behind by one.
This change affects the `history.pushState`, whereby assigns the `index` a number based on `entries.length - 1` or `0`.
Fixes #1555

fix(history): index and entries for pushState using memoryHistory could fall out of sync

---

packages/router-vite-plugin/src/index.ts

fixes #1550.
Based on the issue, I was experiencing issues with the vite plugin generation not working when using a non-standard vite `root` configuration. This was caused by a mismatch between most of the code using `./` or `process.cwd()` as the relative root, and this line using `vite.root`.
I don't think vite's `root` config is strictly necessary here, because the TSR configuration already allows you to configure your `routesDirectory` and `generatedRouteTree` if using a non-standard directory structure.

fix(router-vite-plugin): use `cwd` instead of `vite.root`

---

packages/react-router/src/router.ts
packages/react-router/src/utils.ts
packages/react-router/tests/redirects.test.ts
packages/react-router/tests/utils.test.ts

#1548 didn't account for layout routes as pointed out in #1560.
FIxes #1560

fix(react-router): when navigating without `to` the layout segments are not being stripped out

---

examples/react/basic-ssr-file-based/server.js
examples/react/basic-ssr-streaming-file-based/server.js
examples/react/wip-with-bling/server.js

The server for the "Basic + SSR" (and the wip-with-bling) example is specifiying the wrong file name that gets built into the dist folder.
To reproduce:
1. Open the Stackblitz project: https://tanstack.com/router/latest/docs/framework/react/examples/basic-ssr-file-based
2. `npm i`
3. `npm run build`
4. `npm run serve`
Produces the following error:
```properties
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/projects/wmaivvaxx.github/dist/server/entry-server.tsx' imported from /home/projects/wmaivvaxx.github/server.js
at __node_internal_captureLargerStackTrace2 (https://wmaivvaxxgithub-vsdf.w-staticblitz.com/builtins.575e820e.js:101:5528)
at new NodeError (https://wmaivvaxxgithub-vsdf.w-staticblitz.com/builtins.575e820e.js:101:4214)
at finalizeResolution …
```

docs(examples): set correct correct server entry-point for production for "basic-ssr"

---

packages/react-router/src/utils.ts

Unifies the behaviour of the "onResolved" event being emitted regardless of whether or not `React.StrictMode` is enabled.
Fixes #1566 #1569

fix(react-router): "onResolved" event not being emitted when React.StrictMode is enabled

---

docs/framework/react/guide/router-context.md

Big fix incoming :smile: 
Adding what looks to be a missing comma in a `todos.tsx` example.
Thanks for all your work on TanStack Router and the docs!

docs: add missing comma to from an example in the router-context guide

---

packages/react-router/tests/fileRoute.test.ts

The test for checking if the same hooks are defined when using the createFileRoute function wasn't actually doing its job.

test(react-router): resolving an incorrect configuration checking the route-bound hooks on `createFileRoute`

---

docs/framework/react/guide/route-matching.md

Fixed a broken hyperlink as reported in this discussion: https://github.com/TanStack/router/discussions/1580

docs: broken hyperlink on the "route-matching" guide

---

packages/react-router/src/router.ts
packages/react-router/src/utils.ts
packages/react-router/tests/redirects.test.ts
packages/react-router/tests/utils.test.ts

Layout/pathless routes are denoted by an `id` property.
In file-based routing, an underscore is prefixed to this `id`, but it shouldn't be required.
So the approach for resolving the destination route when navigating without providing the `from` or `to` values needs to be changed to account for this.

fix(react-router): implicit navigation for layout routes without a prefixed underscore id 

---

docs/framework/react/quick-start.md

I face issue in `src/app.tsx` file it might be `src/main.tsx`. Because of vite root file is `src/main.tsx`. Also `index.html` file has 'root' named id element but you are get 'app' id in your `src/app.tsx` file. I update this. By default vite make her project in main.tsx root file and 'root' for her main HTML element.

Update root file name and update root ID

---

packages/react-router/src/link.tsx
packages/react-router/tests/Matches.test-d.tsx
packages/react-router/tests/link.test-d.tsx
packages/react-router/tests/redirects.test.-d.tsx
packages/react-router/tests/useNavigate.test-d.tsx

If `from` is not provided then we should not show relative paths at all!

fix: do not allow relative pathing without `from`

---

packages/react-router/src/Matches.tsx
packages/react-router/src/link.tsx
packages/react-router/src/route.ts

This does not work with React 19 types.
https://react.dev/blog/2024/04/25/react-19-upgrade-guide#the-jsx-namespace-in-typescript

fix: do not use global `JSX` namespace

---

packages/router-generator/src/generator.ts
packages/router-generator/tests/generator/flat/routeTree.expected.ts
packages/router-generator/tests/generator/nested/routeTree.expected.ts

Trailing slashes should only be there if the index route has to be uniquely identified by it.
fixes #1596

fix(router-generator): generator should not infer trailing slash is not necessary for index routes

---

docs/framework/react/guide/external-data-loading.md

This will fix the example with useSuspenseQuery for the Router loader. You cannot just write `const posts = useSuspenseQuery(...)` but have to resolve the data property as so `const {data: {posts}} = useSuspenseQuery(...)`

fix: Syntax error in example with loader and useSuspenseQuery

---

packages/react-router/src/index.tsx
packages/react-router/src/link.tsx
packages/react-router/src/routeInfo.ts
packages/react-router/src/useNavigate.tsx
packages/react-router/tests/link.test-d.tsx
packages/react-router/tests/useNavigate.test-d.tsx

`from` technically allowed any `string` aslong as the resolved route was a valid route. Now It checks if `from` is also a valid route by itself.
This caused subtle problems when users had trailing slashes etc, the resolved route was correct but `from` was not.

fix: do not allow any string in `from`

---

packages/react-router/src/router.ts

When the user sets a `defaultGcTime` on the router or a `gcTime` on a route to the value of `0`, the current eager garbage collection we've got going on ends up setting the route-context to `undefined`.
This normally wouldn't matter on direct navigation, however, when redirects come into play this results in the route trying to execute its options (`beforeLoad`, `loader`, `component`, etc) without its processed route context being available. The current setup looks to perform garbage collection both before and after a `this.loadMatches` has been called in `router.load`.
This change makes it so that garbage collection is done after the `this.loadMatches` call has resolved.
This is part of the fix for #1531.

fix(react-router): do not over-eagerly garbage collect

---

packages/react-router/src/router.ts

Side-effects like URL updates due to default search params being set or redirects can cause scenarios where the route context can become undefined when using `StrictMode`.

fix(react-router): route context being undefined in `StrictMode` on initial render

---

examples/react/start-basic-rsc/app/routes/posts.tsx
examples/react/start-basic-rsc/app/server-components.tsx
packages/react-router/src/router.ts

fix(react-router): only update the route-context during `beforeLoad`

---

packages/react-router/package.json
packages/react-router/src/router.ts
packages/react-router/tests/link.test.tsx
packages/react-router/vite.config.ts
pnpm-lock.yaml

Again quite high level to test navigation and not internals. I will add some more but wanted to know if you guys are ok with basic high level tests like this

tests(react-router): add some basic runtime tests for `Link`

---

docs/framework/react/guide/navigation-blocking.md

According to the [signature](https://github.com/TanStack/router/blob/05941e5ef2b7d2776e885cf473fdcc3970548b22/packages/react-router/src/useBlocker.tsx#L7) the blocking function has `BlockerFn` type and not `() => string`

docs: Update `useBlocker` function signature

---

examples/react/kitchen-sink-react-query/src/mockTodos.ts

Fix https://github.com/TanStack/router/issues/1651

docs(examples): inline the `PickAsRequired` type in the "kitchen-sink-react-query" example

---

docs/framework/react/api/router.md
docs/framework/react/api/router/useBlockerHook.md
docs/framework/react/guide/navigation-blocking.md
examples/react/navigation-blocking/src/main.tsx
packages/react-router/src/useBlocker.tsx
packages/react-router/tests/useBlocker.test.tsx

We were talking about this on discord, trying to find a handy way to display custom UI when blocking navigation.
I adapted a bit @freshgiammi's first draft and expanded it to the `Blocker` component to also have `allow`/`deny` in its children.
I also updated the example to validate it works as expected.
Basically we get these two functions to allow the user to show some custom UI (a modal?) when blocking the navigation and giving full control if resuming or blocking it.
If the API makes sense I'm happy to also update the docs.
cc @schiller-manuel

feat(react-router): improve the blocker functionality for use with custom UI

---

examples/react/start-basic/app/routes/deferred.tsx
packages/router-devtools/package.json

this makes sure we don't get specific versions pulled in transitively (by using `:^` instead of `:*`). If you use the router-devtools, you must also use the router itself.

fix: make router a peerDependency of the devtools

---

.github/workflows/pr.yml
.gitignore
examples/react/start-basic/.gitignore
examples/react/start-basic/package.json
examples/react/start-basic/playwright.config.ts
examples/react/start-basic/tests/app.spec.ts
package.json
pnpm-lock.yaml

Add CI workflow on top of original PR. Can someone approve the workflow? I want to check if the CI changes are working properly.
From original PR: https://github.com/TanStack/router/pull/1641
___
This adds some playwright tests to start-basic to ensure that it's working correctly.
pnpm run test:playwright runs the tests locally
pnpm run test:playwright:replay runs the tests with the Replay browser
To view the replays, join the [TanStack router team](https://app.replay.io/team/invitation?code=d47aa539-f09b-4ec4-aadb-c8f75a0a3dca). Here's an example [replay](https://app.replay.io/recording/navigating-nested-layouts--8a420666-2faf-46da-a029-6cdf7d5b6caa?commentId=&focusWindow=eyJiZWdpbiI6eyJwb2ludCI6IjAiLCJ0aW1lIjowfSwiZW5kIjp7InBvaW50IjoiMzI0NTE4NTUzODkzNzMzNjI0NzcxNjk1OTgyMzU5MzQ3MiIsInRpbW …

test: add playwright testing with CI to start-basic

---

packages/react-router/src/useBlocker.tsx

Open this PR as @schiller-manuel encouraged based on my bug comment in  https://github.com/TanStack/router/pull/1649#discussion_r1614737330.
Since this is my first contribution to this repo, I only strive to make this dead simple.
I manually tested this code in my own project to see it is now working as expected. I checked the PR #1649 to see if I can amend a test suite. But I found it is tricky to add one because the promise is now only a transient instance. 
c.c. @Balastrong

fix(react-router): only instantiate the confirmation promise when required in the `useBlocker` hook

---

packages/react-router/src/index.tsx
packages/react-router/src/link.tsx
packages/react-router/src/route.ts
packages/react-router/src/routeInfo.ts
packages/react-router/src/utils.ts
packages/react-router/tests/link.test-d.tsx

`Link`, `useNavigate` and `redirect` now merge unions for `search` and `params` under the following circumstances:
- When `from` is not used, previous `search` and `params` is a merged type
- When `from` and `to` is not used `search` and `params` is a merged type
- When `from` is not used and `to` is `.` or `..`
- Introduced a few optimizations for merging unions
- Introduced more correct optional/required behaviour for `params` and `search`

feat: merge unions for `search` and `params` for `Link` when `from` and `to` are loose

---

packages/react-router/src/link.tsx
packages/react-router/src/router.ts
packages/react-router/src/useNavigate.tsx
packages/react-router/tests/link.test.tsx
packages/react-router/tests/useNavigate.test.tsx

When `from` included a `path` which had `params` it was being ignored when the location was being built. Same with a layout route.

fix: `from` was being ignored when the pathname included params or a pathless route

---

packages/react-router/tests/routeContext.test.tsx

This is just the start to making sure that route context is correctly tested.
Route context should be checked at 3 distinct points:
* In the `beforeLoad` callback function.
* In the `loader` callback function.
* In the `component` rendered on the screen.
The idea here is that each scenario context scenario we come up with should be checked at all three points to make sure the route context experience is consistent at all levels.
Currently, these tests check for the following:
* Context available at the root route.
* Context available at the index route.
* Context modified at the root route, is correctly available at the index route.
This can be used as a base for building the tests to fix the context issues we are currently facing.

test(react-router): check the route context at `beforeLoad`, `loader`, and `component`

---

packages/react-router/tests/routeContext.test.tsx

This change checks the availability of the route context being correct on the first load.
This does not check the route context availability of the route context after navigation.

test(react-router): check the availability of the route context after a redirect on the first load

---

docs/framework/react/guide/route-masking.md

docs: spelling mistakes on the route-masking guide

---

packages/react-router/src/index.tsx
packages/react-router/src/link.tsx
packages/react-router/src/route.ts
packages/react-router/src/routeInfo.ts
packages/react-router/src/useSearch.tsx
packages/react-router/tests/link.test-d.tsx
packages/react-router/tests/useSearch.test-d.tsx

- remove root search schema as it doesn't seem to be needed
- remove unused type parameters for route options
- added tests to cover index routes and root search schema

perf(react-router): remove root search schema type and unused type parameters from route options

---

packages/react-router/src/link.tsx
packages/react-router/src/router.ts
packages/react-router/src/useNavigate.tsx
packages/react-router/tests/link.test.tsx
packages/react-router/tests/useNavigate.test.tsx

- Use flatRoutes so we can select branches even if they have index routes
- Do not override `from` redirect preloads. Users should specify this manually
- Ignore `from` in declarative route masks when building the location
- Add tests to cover bugs encountered

fix(react-router): take `from` into account when navigating with `params` or layouts

---

docs/framework/react/devtools.md
packages/router-devtools/src/Explorer.tsx
packages/router-devtools/src/context.ts
packages/router-devtools/src/devtools.tsx

Closes #1709 
TanStackRouterDevtools before:
TanStackRouterDevtoolsPanel before:
TanStackRouterDevtools after:
TanStackRouterDevtoolsPanel after:

feat(router-devtools): add shadowDOMTarget option to TanStackRouterDevtools and TanStackRouterDevtoolsPanel (#1709)

---

examples/react/large-file-based/src/routes/__root.tsx
examples/react/large-file-based/src/routes/search/route.tsx
examples/react/large-file-based/src/routes/search/searchPlaceholder.tsx
packages/react-router/src/utils.ts

When there are no overlapping keys when merging `search`, `params` or `context` from the parent `Omit` is not necessary, we can use a plain intersection. 
Lowers instantiations a bit more
Before:
```
> tsc --extendedDiagnostics
Files:                         644
Lines of Library:            38411
Lines of Definitions:        82801
Lines of TypeScript:         19754
Identifiers:                134792
Symbols:                    327437
Types:                      115995
Instantiations:             829877
Memory used:               398942K
Assignability cache size:    49740
Identity cache size:          8548
Subtype cache size:           2426
Strict subtype cache size:     413
I/O Read …
```

perf(react-router): only Omit in Assign when there are overlapping keys

---

docs/framework/react/guide/ssr.md

Fix conflicts with local declaration of 'createRouter' and correct import path for 'routeTree.gen'
- Resolved naming conflict by renaming the local 'createRouter' function.
- Added missing './' in the import path for 'routeTree.gen'.

docs: fix some mistakes in the example of the SSR guide

---

packages/router-vite-plugin/src/compilers.ts
packages/router-vite-plugin/tests/snapshots/createServerFn.tsx
packages/router-vite-plugin/tests/snapshots/createServerFn@split.tsx
packages/router-vite-plugin/tests/test-files/createServerFn.tsx

Wrap identifiers/call expressions that are passed as the 2nd parameter to createServerFn with a function expression whose body is prepended with the "use server" directive.
This allows for functions that are passed to createServerFn to be wrapped with other functions that serve as middleware.
router-vite-plugin/tests/test-files/createServerFn.tsx has a Zod middleware function example which has the "use server" directive properly prepended.

feat(router-vite-plugin): wrap "use server" over callexprs/identifiers for createServerFn

---

packages/react-router/src/router.ts
packages/react-router/tests/link.test.tsx

When pending has not been set for matchRoute we should determine the base location based on if the router is loading or not.
- If the router is loading then use the previous location like `Link`
- If the router is not loading then we can safely use the latest location.
This allows the user to conditionally render a `Link` with `from` without any errors

fix(react-router): match route location when pending has not been set

---

docs/framework/react/guide/code-splitting.md
docs/framework/react/guide/file-based-routing.md

docs: add documentation on the `experimental.enableCodeSplitting` feature

---

packages/react-router/src/path.ts
packages/react-router/tests/path.test.ts

Previous implementation did not cover cases of partial match and cases with basepath matched later within the path.
Reworked version removes basepath only from the beginning of pathname and only in case it fully matches path segment.
Giving the basename is `/app`
| input | old | new |
|------:|:----|:-----|
| `/application` | `lication` | `/application` |
| `/app/project/applications` | `/projectlications` | `/project/applications` |
| `/app/app/app` | `` | `/app/app` |
fix: #1779

fix: proper basename removal handling

---

packages/react-router/src/path.ts
packages/react-router/src/router.ts
packages/react-router/tests/link.test.tsx

re-created PR https://github.com/TanStack/router/pull/1784 since we have a CI issue (builds do not work in case of a branch not being inside this repo)

fix: linking with from prop and a param containing slash

---

packages/router-devtools/package.json

Found this since our Playwright E2E test was quite flaky. Traced to this import not being correctly resolved, since the package.json for the `@tanstack/router-devtools` package didn't use the `./` prefix for the pathing of the `main`, `types`, and `module` fields 😅.
This doesn't completely resolve our E2E test being flaky, but at least it brings the error count down to 1.
This is the next problem to resolve: https://cloud.nx.app/runs/IrBZdWTyNV

fix(router-devtools): prefix`./` to the pathing for `main`, `types`, and `module` fields in the package.json

---

packages/router-plugin/src/compilers.ts
packages/router-plugin/tests/code-splitter/snapshots/function-declaration.tsx
packages/router-plugin/tests/code-splitter/snapshots/imported-default-component-destructured-loader.tsx
packages/router-plugin/tests/code-splitter/snapshots/imported-default-component.tsx
packages/router-plugin/tests/code-splitter/snapshots/imported.tsx

fix(router-plugin): removing trailing import string literals with no references for `experimental.enableCodesplitting`

---

packages/router-plugin/src/compilers.ts
packages/router-plugin/tests/code-splitter/snapshots/destructured-react-memo-imported-component.tsx
packages/router-plugin/tests/code-splitter/snapshots/destructured-react-memo-imported-component@split.tsx
packages/router-plugin/tests/code-splitter/snapshots/react-memo-component.tsx
packages/router-plugin/tests/code-splitter/snapshots/react-memo-component@split.tsx
packages/router-plugin/tests/code-splitter/snapshots/react-memo-imported-component.tsx
packages/router-plugin/tests/code-splitter/snapshots/react-memo-imported-component@split.tsx
packages/router-plugin/tests/code-splitter/test-files/destructured-react-memo-imported-component.tsx
packages/router-plugin/tests/code-splitter/test-files/react-memo-component.tsx
packages/router-plugin/tests/code-splitter/test-files/react-memo-imported-component.tsx

It's 4:00 AM here, I really should be sleeping...
fixes #1801

fix(router-plugin): `experimental.enableCodeSplitting` - allow the use of inlined wrappers for the route options when splitting nodes

---

docs/framework/react/guide/type-safety.md

When using TanStack Query or other client side caches, you might want to use `loader` to only prefetch data. In this case it is more performance for TS to never infer the complex type returned from `ensureQueryData`. Just to be clear, we're talking about this:
```tsx
loader: (opts) => opts.context.queryClient.ensureQueryData(searchQueryOptions),
```
vs this
```tsx
loader: (opts) => {
opts.context.queryClient.ensureQueryData(searchQueryOptions)
},
```
The second is more performant because the complex type is never inferred
I've profiled this with the large file based example and the difference can be quite large. 3.1s to type check the route tree vs 2.1s

docs: add TS performance guidance with prefetching

---

packages/start/src/server-handler/handler.tsx

When using a form like so:
```jsx
export const handleForm = createServerFn('POST', async (formData: FormData, ctx) => {
});
<form action={handleForm.url} method="post" encType={"multipart/form-data"}/>
```
The form action would not be passed to the server handler appropriately. This PR fixes this behavior to work as-intended

fix: handle formdata correctly from form action

---

.prettierignore

Change pretty much only affects local-development, as in CI these `.output` directories wouldn't exist.

chore(workspace): prettier to ignore the `.vercel` output directories

---

packages/start/src/config/index.ts

In TanStack Form, I need a way to disable the React dev refresh transform for internal packages in the monorepo.
This allows us to have a configuration file like so:
```tsx
import { defineConfig } from '@tanstack/start/config'
import tsConfigPaths from 'vite-tsconfig-paths'
export default defineConfig({
vite: {
plugins: () => [
tsConfigPaths({
projects: ['./tsconfig.json'],
}),
],
},
react: {
exclude: [/packages/],
}
})
```
Which solves my issue in the monorepo.

fix: add option to include and exclude properties from React plugin

---

examples/react/start-basic-react-query/package.json
examples/react/start-basic-react-query/playwright.config.ts

Targetting `rsc` branch.
@tannerlinsley There were two port conflicts. One was dev server itself between two example projects. Another was the internal playwright plugin server. I'm filing an issue internally, so we don't need env workaround I added.
Tests are still failing on an unrelated error. Here's an example run: https://cloud.nx.app/runs/Cv51FZLMhi 
I guess `createStartHandler` has been changed to something else?

Use different port on example apps

---

.github/workflows/pr.yml
examples/react/start-basic/package.json
package.json

`build:example` wasn't building right dep. This PR builds all of the packages before starting the tests.

ci: fix the workflow for running the e2e test on the "start-basic" example

---

packages/router-plugin/src/demo-rspack-code-splitter.ts
packages/router-plugin/src/rspack.ts

Since unplugin takes away too much control over child compilers transform, the easiest solution is to just add the loader directly through rspack compiler and skip unplugin apis for the time bring
The transform hook doesn't implement the test regex. So using transform has an impact on other compilation targets and there's no way to scope it down that I could see at a glance.

fix: use chunk compiler directly to add module transform loader

---

packages/start/src/config/index.ts

This PR fixes an issue with TanStack Start's Config subpackage not working properly on Windows.
This is because `import.meta.url` looks like the following on macOS:
```
file:///Users/something
```
And the following on Windows:
```
file:///C:/Users/something
```
Node's `fileURLToPath` appears to work for both Windows and macOS properly (I've tested both).

fix: Start config now loads properly on Windows

---

docs/framework/react/guide/custom-search-param-serialization.md

Howdy! 
When using Zipson per this original example I had unexpected results. The URL produced was actually larger than the base-64 encoding example. I believe it was because `decodeURIComponent` and `encodeURIComponent` were being ran twice (ie: once in the lambda passed to `parseSearchWith` and once inside `decodeFromBinary`). Removing the duplicate function call seemed to do the trick. 
If anyone wants to try to reproduce it, copy-pasting from this change should be enough. 
Thanks!

docs: remove the unnecessary encode and decode `URIComponent` calls in the zipson example of the "custom search param serialization" guide

---

examples/react/authenticated-routes/package.json
examples/react/authenticated-routes/vite.config.js
examples/react/basic-file-based-codesplitting/package.json
examples/react/basic-file-based-codesplitting/vite.config.js
examples/react/basic-file-based/package.json
examples/react/basic-file-based/vite.config.js
examples/react/basic-react-query-file-based/package.json
examples/react/basic-react-query-file-based/vite.config.js
examples/react/basic-ssr-file-based/package.json
examples/react/basic-ssr-file-based/vite.config.js
examples/react/basic-ssr-streaming-file-based/package.json
examples/react/basic-ssr-streaming-file-based/vite.config.js
examples/react/kitchen-sink-file-based/package.json
examples/react/kitchen-sink-file-based/vite.config.js
examples/react/kitchen-sink-react-query-file-based/package.json
examples/react/kitchen-sink-react-query-file-based/vite.config.js
examples/react/large-file-based/package.json
examples/react/large-file-based/vite.config.js
examples/react/quickstart-file-based/package.json
examples/react/quickstart-file-based/vite.config.js
examples/react/start-basic-react-query/package.json
examples/react/start-basic-rsc/package.json
examples/react/start-basic/package.json
examples/react/start-trellaux/package.json
pnpm-lock.yaml

Should have done this when I released the unplugin version of the Router plugin.

chore(examples): move from `@tanstack/router-vite-plugin` to `@tanstack/router-plugin`

---

docs/framework/react/guide/server-functions.md

> This PR builds on top of #1857, we might want to merge that one first.
This PR documents usage of `createServerFn` from TanStack Start. Like the other PR, this one is intentionally not added to the sidebar, as it's unclear how public we want these draft documents.

docs: add initial documentation for createServerFn

---

.prettierignore

Since we cache our builds, running our `pnpm test:format` command in `test:ci` and `test:pr` tends to sometimes fail.

style(workspace): more patterns for prettier to ignore

---

packages/start/src/client/index.tsx

In TanStack Form, it would be helpful to have this type exported in a way that's easier to access so that I can move our `createServerFn` into userland.

fix: export FetchFnCtx type for library usage

---

nx.json
packages/history/vite.config.ts

- Renamed `public` to `production` to match [Nx docs](https://nx.dev/reference/inputs)
- `build` will not be invalidated when only tests change
- `test:build` now has the right cache inputs
- `test:sherif` only depends on `package.json` files

ci: Improve Nx inputs

---

packages/react-router/src/route.ts
packages/react-router/src/router.ts
packages/start/src/client/serialization.tsx

The route `meta()` callback currently receives _all_ matches, _this route's_ path params, and _this route's_ loader data. Although you can of course write a given route's meta callback to retrieve its own full match object from the array using a hardcoded `id`, you can't bootstrap that in a helper for arbitrary routes using the params given to the callback.
This PR adds the given route's own match to the parameter object, separate from the list of all matches. My own situation involves using a search param in the page title.

feat: Add this route's match to route `meta()` params

---

.github/renovate.json
examples/react/start-basic-counter/package.json
examples/react/start-basic-react-query/package.json
examples/react/start-basic-rsc/package.json
examples/react/start-basic/package.json
examples/react/start-trellaux/package.json
pnpm-lock.yaml

Removes `"eslint-plugin-unicorn"` and `"npm-run-all"`, which are both only present in examples, and are not used.

chore(deps): remove unused dev dependencies

---

packages/react-router/src/scroll-restoration.tsx

From #1944.
The default `getKey` returns `undefined` on the initial load since `location.state.key` wouldn't have been set.
Fixes #1944

fix(react-router): scroll-restoration not being persisted on initial load

---

packages/react-router/src/route.ts
packages/react-router/src/router.ts
packages/react-router/tests/route.test-d.tsx
packages/react-router/tests/router.test-d.tsx

When `addChildren` was called, we lost the type of `RootRoute` and there could no longer infer `RouterContext`.
Fixes #1943 
Fixes #1926

fix(react-router): when children are added to the route tree, the inference of RouterContext is lost

---

docs/framework/react/api/router/useMatchHook.md
packages/react-router/src/useMatch.tsx
packages/react-router/tests/useMatch.test-d.tsx
packages/react-router/tests/useMatch.test.tsx

in this case, `matchRoute` will return undefined

feat(react-router): allow `useMatch` to not throw if match was not found

---

packages/router-devtools/package.json
pnpm-lock.yaml

`date-fns` is specified in dependencies, but not used

fix(router-devtools): remove date-fns

---

packages/react-router/src/path.ts
packages/react-router/tests/router.test.tsx

fix(react-router): URI path segments segments should match on equality regardless of their encoding state

---

examples/react/start-basic-react-query/app/routes/deferred.tsx
examples/react/start-basic-react-query/app/routes/posts.$postId.tsx
examples/react/start-basic-react-query/app/routes/posts.tsx
examples/react/start-basic-react-query/app/routes/posts_.$postId.deep.tsx

Use ensureQuery for loaders so that if the data is not stale it won't need to be refetched.
As suggested in https://github.com/TanStack/router/pull/1883/files#r1667101376

examples: Use ensureQuery in start-basic-react-query

---

packages/react-router/tests/createLazyRoute.test.tsx
packages/react-router/tests/link.test.tsx
packages/react-router/tests/loaders.test.tsx
packages/react-router/tests/redirect.test.tsx
packages/react-router/tests/router.test.tsx
packages/react-router/tests/setupTests.tsx
packages/react-router/tests/useMatch.test.tsx
packages/react-router/vite.config.ts

Part of #1976 
✅ These files no longer throw `act` warnings.
- `loaders.test.tsx`
- `createLazyRoute.test.tsx`
- `router.test.tsx`
- `useMatch.test.tsx`
⚠️ These files have been migrated over, but still emit the `act` warnings.
- `link.test.tsx`
- `redirect.test.tsx`

test(react-router): reducing the `React.act` warnings during unit tests

---

docs/framework/react/guide/not-found-errors.md

docs: remove the `component` as a supported throw area for the `notFound` utility

---

packages/router-cli/src/index.ts
packages/router-cli/src/watch.ts
packages/router-generator/src/config.ts
packages/router-plugin/src/code-splitter.ts
packages/router-plugin/src/config.ts
packages/router-plugin/src/router-generator.ts
packages/start/src/config/index.ts

The flags under the key of `experimental` need to be parsed by the router-generator, for it to work when using a `tsr.config.json` file instead of having to inline the config with the bundler plugin.

fix(router-generator): parse the experimental flags at the generator

---

packages/start/src/config/index.ts

<details><summary>Vercel</summary>
<p>
😊 We already know this works since tanstack.com is deployed on Vercel.
</p>
</details> 
<details><summary>Netlify</summary>
https://start-basic-netlify.netlify.app
</details> 
<details><summary>Static</summary>
<p>
The build output is correct.
Also, directly visiting URLs (initial load) that use a `createServerFn` call works, like going to `/posts/1`.
However, you cannot navigate to a that uses a `createServerFn` call, after the page has loaded. Then an exception is thrown in the UI.
</p>
</details> 
<details><summary>Node</summary>
<p>
Functionally, everything in the Router and the `createServerFn` calls seem to be working.
You'll need to create a node server that uses the listener from the build output. Snippet below.
```js
// …
```

fix(start): expose "netlify" and "vercel" as target deployment presets

---

docs/framework/react/guide/tanstack-start.md

This is the minimum I found I needed to get to teh page rendering, the server actions working, and a `tsc --noEmit` passing.
There's still a `[plugin:vite:resolve] Module "fs" has been externalized...` warning and visiting the page causes
```
Warning: A notFoundError was encountered on the route with ID "__root__", but a notFoundComponent option was not configured, nor was a router level defaultNotFoundComponent configured. Consider configuring at least one of these to avoid TanStack Router's overly generic defaultNotFoundComponent (<div>Not Found<div>)
```

Add details to getting started with Start.

---

packages/react-router/src/path.ts
packages/react-router/tests/link.test.tsx
packages/react-router/tests/path.test.ts

fix(react-router): retain path parameters that are falsy but still valid 

---

scripts/publish.js

For whatever reason, https://github.com/TanStack/router/commit/2c94fa0ee8f54f7039649f5e7e2c3e74087df5f1 did not trigger a package to be published.
Looking at our `publish` script, we don't seem to have the `@tanstack/react-router-with-query` as a package to be published.

build(react-router-with-query): add `@tanstack/react-router-with-query` to the publish list

---

packages/react-router/src/route.ts

The flag `unmaskOnReload` is already handled in `createRouter({routeMasks})` but wasn't exposed from `createRouteMask`.

feat: expose unmaskOnReload on createRouteMask

---

packages/react-router/src/link.tsx
packages/react-router/tests/link.test-d.tsx

There is an issue in the types where `from` is an index route but there is no `to` or the resolve path is the same as `from`. It means that
`<Link from='/posts/' />` always requires a `search` param because the resolved route is incorrect and returns `never`

fix(react-router): when navigating from a index the types should resolve to a valid route

---

packages/react-router/src/link.tsx
packages/react-router/src/utils.ts

The previous interface for the internal `useIntersectionObserver` hook didn't account for the fact that the two important parts of the hook was to accept a `ref` and a `callback`. This also lets the `intersectionObserverOptions` and `options` truly be _optional_.

refactor: better API surface for the internal `useIntersectionObserver` hook

---

packages/react-router/src/fileRoute.ts

Resolves #1978 
`createFileRoute` didn't correctly resolve and enforce `staticData` even when it should. The return type for this function was always compiled down with typescript instead of using the "live" types. During the library build, the `StaticDataRouteOption` was empty, and it resulted in the `staticData` being always optional.

fix(react-router): resolve staticData in createFileRoute

---

packages/router-devtools/src/devtools.tsx

Masked path is shown right after the real path but it seems they're the same string. I suggest moving the masked path to the right.
**Current**
**Proposed**

feat(devtools): align right masked path

---

packages/react-router/src/link.tsx
packages/react-router/tests/link.test-d.tsx

fix(react-router): `activeProps` and `inactiveProps` on `Link` to accept data-attributes

---

packages/react-router/src/Match.tsx
packages/react-router/tests/router.test.tsx

Resolves #2085 
Since the `matchId` is a unique string formed to represent the current match, when using it as a key to stabilize the route component, the `matchId` caused the page component to be remounted even on the smallest changes to a route. Whilst, rendering is expected, remounting certainly is not.
Using the `routeId` here stabilizes the component across many more renders, since it remains static.

fix(react-router): use `routeId` to stabilize the memoized route component to prevent from remounting when on the same route

---

docs/framework/react/api/router/RouteOptionsType.md

We haven't had the `context` and `location` arguments present as `loaderDeps` options, so this corrects this error in Router's documentation.
The reason we don't have `location` as an argument of `loaderDeps` is quite simple. If the `location` changes, the loader would anyways have to be refired (or retrieved from a cache using something like Query). The scenario in which this wouldn't be the case, is if you wanted to prevent this from happening when search params change. This is why only `search` is provided as its own argument.
The reason we don't have `context` as an argument of `loaderDeps` is because, when the root context has been changed, the user is expected to call `router.invalidate()`. This `invalidate` call discards all cached data and re-evaluates the entire route-tree. As …

docs: remove the invalid `context` and `location` arguments from being shown as available in the `loaderDeps`

---

packages/react-router/src/router.ts
packages/react-router/tests/router.test.tsx

This affected anyone trying to use the `basic-ssr-file-based` example as a starting point.

fix(react-router): set a default `transformer` during router instantiation

---

packages/start/src/server/defaultStreamHandler.tsx

transformStreamWithRouter was previously being used when the runtime is detected to support web streams (i.e. ReadableStream).
transformReadableStreamWithRouter should be used instead inside of defaultStreamHandler.

fix(start): use appropriate stream transform for renderToReadableStream

---

packages/start/src/config/index.ts

Tested deployment with Bun and marked the Bun deployment preset as tested. Marked all newly included presets as untested.

fix(start): include all available nitro presets

---

packages/react-router/src/fileRoute.ts

this removal was introduced by #1253, however in the meantime the generator was modified

fix(react-router): do not remove route groups from lazy file route ids

---

docs/framework/react/api/router/RouteOptionsType.md

docs: correct the documentation on the expected behaviour of `Router.onError`

---

docs/config.json

The `start-basic-rsc` example is in a working condition since TSR's RSC story hasn't been flushed out yet. For the time being, we'll be hiding this option from the website.
Closes #2126

docs: hide the `start-basic-rsc` example from the website

---

docs/framework/react/api/router/useBlockerHook.md

Fixing only minor typos in the router useBlockerHook basic usage `BlockerFn`
[Basic usage](https://tanstack.com/router/latest/docs/framework/react/api/router/useBlockerHook#basic-usage)

docs(useBlockerHook) fix minor typo in useBlockerHook docs

---

packages/router-generator/src/config.ts
packages/router-plugin/src/router-generator.ts

This affects users that have their `root` set to something other than the default, whereby the plugin's watcher functionality stops working.
Fixes #2030

fix(router-generator): resolving the `routesDirectory` and `generatedRouteTree` when the `configDirectory` is set

---

packages/router-generator/src/generator.ts

We handled the scaffolding of "routes" and "lazy routes", but never the "root route". This change adds that functionality with the option to handle having virtual root routes in future if need be.

fix(router-generator): scaffolding the initial content for the root route

---

packages/react-router/src/Transitioner.tsx
packages/start/src/client/Meta.tsx

I’m trying to use `react-test-renderer` to render a component that uses router hooks or components like `Meta`. It seems like `react-test-renderer` is always executing `useLayoutEffect` and `useEffect`. Since I don’t have a global `window` or `document` object during my test run, some components fail when using `document` without checking if it exist.
See also discussion https://github.com/TanStack/router/discussions/2109.

fix(react-router,start): ensure document is only used when available

---

examples/react/quickstart-rspack-file-based/package.json
packages/router-plugin/package.json
packages/router-plugin/src/code-splitter.ts
pnpm-lock.yaml

In terms of the peerDeps, this would technically be considered a breaking change, since we are moving rspack's required deps level from `>=0.5.x` to `>=1.0.0`. However, since rspack was pre 1.0 with the bulk of their now being stable in `1.0`, this is being pushed through.
---
router-plugin
- upgrade `unplugin` from "1.11.0" to "1.12.2".
- remove `vite` as a development dependency.
- bump peer dependency requirement for `@rsbuild/core` to a minimum of `1.0.0`.
quickstart-rspack-file-based
- upgrade `@rsbuiild/core` and `@rsbuild/plugin-react` to `1.0.1-beta-15`

fix(router-plugin): plugin functionality for rspack `1.x.x`

---

docs/framework/react/guide/router-context.md

- Update router-context doc. Processing accumulated routes with the useRouterState hook.
- https://github.com/TanStack/router/issues/2101
- https://github.com/TanStack/router/issues/2144

doc(accumulated-route-context): useRouterState to listen reactive state change

---

packages/react-router/src/router.ts

fix(react-router): restore previous `matchRoutes` signature

---

docs/framework/react/guide/code-splitting.md
docs/framework/react/guide/file-based-routing.md
examples/react/with-trpc-react-query/app.config.js
examples/react/with-trpc/app.config.js
packages/router-generator/src/config.ts
packages/router-plugin/src/core/router-code-splitter-plugin.ts
packages/start/src/config/index.ts

This change marks the development work done under the `experimental.enableCodeSplitting` flag as "stable". As such, the flag will no longer be marked as "experimental".
The flag is also being renamed to "autoCodeSplitting", as it better denotes the functionality of what can be expected when using the flag.
The "code-splitting" guide in TSR's documentation has also been updated to reflect this change.

refactor(router-generator,router-plugin,start): mark `experimental.enableCodeSplitting` functionality as stable with the name `autoCodeSplitting`

---

packages/start/src/client/serialization.tsx

When a route is matched to be unsuccessful such that no loader data is available, the meta function still gets called with undefined loader data. Given that the type signature of the meta function assumes that loader data is always to be defined, a change was made to only call the meta function when a match is successful.

fix(start): load meta only on successful hydration

---

docs/framework/react/start/authentication.md
docs/framework/react/start/databases.md
docs/framework/react/start/getting-started.md
docs/framework/react/start/hosting.md
docs/framework/react/start/observability.md

The Start documentation had some comments which weren't properly commented out and it had top-level headings that conflicted with what the website generated.

docs(start): markdown to follow the website flow

---

examples/react/start-basic/app/routes/deferred.tsx
examples/react/start-basic/tests/app.spec.ts
packages/start/src/client/serialization.tsx

When wrapping a `createServerFn` call that returns something more complex than a number or string (ie: an Object or an Array), it fails on the client since the `transformer` uses `JSON.parse` which expects a string input (but can also gracefully handle a number input as well).
This fails on the client without the changes being applied in this PR.
```tsx
import { Await, createFileRoute, defer } from '@tanstack/react-router'
import { createServerFn } from '@tanstack/start'
import { Suspense, useState } from 'react'
const serverObject = createServerFn('GET', async () => {
await new Promise((r) => setTimeout(r, 1000))
return {
foo: 'bar',
}
})
export const Route = createFileRoute('/deferred')({
loader: () => {
return {
deferredObject: defer(serverObject()),
}
},
component: Deferred,
}) …
```

fix(start): deferred `createServerFn` calls fails on the client

---

packages/react-router/src/fileRoute.ts
packages/react-router/src/route.ts
packages/react-router/src/router.ts
packages/react-router/src/utils.ts

This just optimizes the types a bit after the `context` and other merges. Mainly less type parameters continuing on the tread of reducing them

perf(react-router): reduce type parameters of route definitions

---

packages/react-router/src/link.tsx
packages/react-router/src/routeInfo.ts
packages/react-router/tests/Matches.test-d.tsx
packages/react-router/tests/link.test-d.tsx
packages/react-router/tests/redirects.test-d.tsx
packages/react-router/tests/route.test-d.tsx
packages/react-router/tests/useNavigate.test-d.tsx

Due to the trailing slashes setting there were some left over annoyances with relative pathing.
Firstly was possible to use `./` or `../` when trailing slashes was set to `never` but the route resolved to `never` because we handled this properly.
Secondly suggestions for relative routing were triggered when the user typed `..` for parent paths but triggered for './` for current paths
fixes #1838

fix: enforce trailing slashes better and general relative pathing imrovements

---

docs/framework/react/guide/file-based-routing.md
docs/framework/react/guide/routing-concepts.md

Was just reading the new docs (thank you!!) and saw a few things missing in the rendered markdown:

Minor fixes to markdown docs

---

packages/react-router/src/fileRoute.ts

fix(react-router): remove groups when using `createLazyFileRoute`

---

packages/react-router/src/router.ts
packages/react-router/tests/link.test.tsx

In the current version of the router, the error boundary is reset at the beginning of the loading phase of the new matching routes. This is a problem because the currently rendered routes can re-render while the new ones ar being in the loading process. If this is the case, the re-render will trigger the error boundary again and will void the reset.
I believe the reset should happen only after the new routes have finished loading. In this way, the reset will be in sync with the matched routes.
I don't know if this fix might have some side effects, but on our project it seems to work. If you think that this fix is not ok or you have a better solution, I would be happy to try it out.
Here is the issue I am referring to: https://github.com/TanStack/router/issues/2162
fixes #2162
fixes #2043

fix(react-router): reset error boundary after the new matches are ready

---

docs/framework/react/guide/route-trees.md
docs/framework/react/guide/routing-concepts.md

This PR fixes broken hyperlinks in `docs/framework/react/guide/route-trees.md` and `docs/framework/react/guide/routing-concepts.md`.
- `route-trees.md`: route tree examples no longer exist in this page, so the hyperlinks should point to the full documentation for each route type. ([page link](https://tanstack.com/router/latest/docs/framework/react/guide/route-trees#route-tree-configuration))
- `routing-concepts.md`: there is a typo that leads to a 404 page. ([page link](https://tanstack.com/router/latest/docs/framework/react/guide/routing-concepts))

docs(react): fix broken links in route-trees.md and routing-concepts.md

---

docs/framework/react/guide/route-trees.md

This PR adds the missing `.md` file extension to the markdown links in `route-trees.md`.
As per this [PR](https://github.com/TanStack/tanstack.com/pull/255) native markdown relative paths only work in tanstack/tanstack.com with the `.md` file extension. 
My apologies for not checking this in my previous PR.

docs(react): add missing .md extension to link paths in route-trees.md

---

packages/react-router/src/router.ts
packages/react-router/tests/link.test.tsx

Hi, I tried fixing this issue #2008. If route had preload: 'intent' enabled, the pendingComponent would not show, UI just waited for promise to end, and then it would switch route. I found out, that triggerOnReady() in router.ts weren't used if route had beforeLoadPromise or loaderPromise to await for.
https://github.com/user-attachments/assets/960609ad-1e4f-4cf9-a376-ad32f16e3e2a
https://github.com/user-attachments/assets/7701b0ba-4def-42a9-b543-89f26e9003bb

fix(react-router): `pendingComponent` not rendering with preload='intent'

---

packages/react-router/src/Matches.tsx
packages/react-router/src/route.ts
packages/react-router/src/router.ts
packages/react-router/tests/route.test-d.tsx

this will allow typesafe access to the matches so something like this can be done:
```tsx
beforeLoad: (c) => {
const leafMatch = c.matches[c.matches.length - 1];
if (leafMatch.fullPath === '/dashboard/invoices/$invoiceId') {
if (leafMatch.params.invoiceId === '1') {
// do something
}
}
```

feat: pass `matches` into `context()` and `beforeLoad()`

---

packages/start/src/client-runtime/fetcher.tsx

This change, has the error being thrown by the client fetcher be a JSON object instead of a plain string. This makes it so, that when its consumed on the client it'll have the error content stored in an object.
```jsonc
{
"message": "Response failed with a status 500",
"body": { "foo": "bar" } // this is the actual error content
}
```
closes #2238

refactor(start): return JSON response when 'content-type' matches

---

packages/react-router/tests/route.test.tsx

Test to reinforce #1529.
Closes #1529

test(react-router): `onEnter` should have the router context defined

---

packages/react-router/src/link.tsx

There was a regression in instantiations which affected overall check time with the new language service improvements. This PR reduces it back down.
Before
```
> tsc --extendedDiagnostics
Files:                         683
Lines of Library:            41276
Lines of Definitions:        86370
Lines of TypeScript:         24510
Identifiers:                144216
Symbols:                    338892
Types:                      113449
Instantiations:            1040616
Memory used:               368084K
Assignability cache size:    86626
Identity cache size:          8937
Subtype cache size:           2830
Strict subtype cache size:      10
I/O Read time:               0.09s
Parse time: …
```

perf(react-router): reduce instantiations for relative routing after language service performance

---

docs/framework/react/installation.md
package.json
pnpm-lock.yaml

- The test script for `typescript55` was pointed at `5.6.2`.
- Also, calling out the rolling typescript support mentioned here: https://discord.com/channels/719702312431386674/1282765477021618236

chore: correctly set the typescript test version to 5.5.2

---

docs/framework/react/guide/external-data-loading.md

"client" should have been "queryClient"

docs: correcting a variable reference in external-data-loading.md

---

packages/react-router/package.json

There is no package called `@tanstack/react-generator` so I guess it is meant to be `@tanstack/router-generator`.

fix(react-router): Correct typo in optional peerDependenciesMeta

---

packages/router-plugin/src/core/router-code-splitter-plugin.ts

use `path.normalize` to normalize the path.
It should convert `G:/Programs/Node.js/reproduce-vite-code-splitting` to `G:\Programs\Node.js\reproduce-vite-code-splitting` in windows.
It fix #2364 and maybe fix #2167 too.
Here is a CI run log using this patch: https://github.com/greenhat616/reproduce-vite-code-splitting/actions/runs/10928570228/job/30337286182
The build in windows works as expect via this patch

fix(router-plugin): normalize file path in `fileIsInRoutesDirectory` to ensure windows compatibility

---

docs/config.json
docs/framework/react/start/path-aliases.md

From https://discord.com/channels/719702312431386674/1285056967588581498

docs(start): guide on configuring path aliases

---

e2e/start/basic-auth/package.json
e2e/start/basic-react-query/package.json
e2e/start/basic/package.json
e2e/start/clerk-basic/package.json
examples/react/start-basic-auth/package.json
examples/react/start-basic-react-query/package.json
examples/react/start-basic/package.json
examples/react/start-clerk-basic/package.json
examples/react/start-convex-trellaux/package.json
examples/react/start-trellaux/package.json
pnpm-lock.yaml

Hi.
This PR removes the redundant `@vitejs/plugin-react` from dependencies, as it's already in devDependencies at package.json in some starter examples.

chore(deps): remove duplicate `@vitejs/plugin-react` from dependencies

---

packages/react-router/package.json
packages/react-router/tests/link.bench.tsx

Related to #2359, I set up a basic performance testing of the Link component and its simplified versions, using vitest `bench` functionality.

test(react-router): set up performance testing for Link

---

packages/start/src/config/index.ts

Ok so this PR follows some discussions from the Tanstack discord. For deploying Tanstack start to cloudflare, one must add some additional configs, which were not available in the config.
Current implementation copies `HTTPSOptions` from `@vinxi/listhen` because the type is not portable and the build fails. Ideally the implementation shouldn't do such things, so I'm open to suggestions.
With this change, the Tanstack start config is more aligned with the Solid start one:))
(P.S. this is my first OSS contribution, hello to everyone)

fix(start): extend `defineConfig` server options with VinxiAppOptions.server

---

packages/router-plugin/src/core/router-generator-plugin.ts

The chokidar watcher in `router-plugin` is supposed to be looking only for newly created files in webpack/rspack apps. By default, it considers all files as "new" when starting the dev server, causing the generator to run multiple times, and slowing down the actual startup of the app.
There's a question if we want to always run the generator at least once when starting the dev server 🤔

fix(router-plugin): ignore initial files

---

docs/framework/react/overview.md

Fixes a typo: `guaranty` to `guarantee`.

docs: fix typo w/ guarantee

---

docs/framework/react/guide/routing-concepts.md

Removing a dot in a sentence (maybe it should've been a comma?) and create a lead for the list of uses for a pathless route.

docs: update pathless route wording

---

docs/framework/react/guide/routing-concepts.md

Fixes `Pathless Routes` link on the table-of-contents.

docs: fix pathless route link

---

packages/react-router/src/index.tsx
packages/react-router/src/link.tsx

fix: allow composite and `createLink`

---

docs/framework/react/guide/navigation.md

remove outdated hint for omitting `to` prop.

fix outdated navigation hint inside the docs

---

docs/framework/react/guide/deferred-data-loading.md

As Tanner [mentioned](https://x.com/tannerlinsley/status/1841844004755013994), Suspense is unnecessary, as Await has a built in suspense boundary

Examples: remove unnecessary <Suspense>

---

packages/react-router/src/router.ts

this flag is required for router typings to work properly. if it is not enabled, strange errors can occur.

fix(react-router): check if `strictNullChecks` are enabled

---

packages/router-arktype-adapter/package.json
pnpm-lock.yaml

We should not check < 5.3 TS because ArkType does not check for it either

chore: upgrade arktype

---

examples/react/with-framer-motion/package.json
examples/react/with-framer-motion/tsconfig.json
pnpm-lock.yaml

set `skipLibCheck: true` to get rid of the following error:
```
../../../node_modules/.pnpm/framer-motion@11.11.1_@emotion+is-prop-valid@0.8.8_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/framer-motion/dist/index.d.ts:3844:5 - error TS2416: Property 'attachTimeline' in type 'GroupPlaybackControls' is not assignable to the same property in base type 'AnimationPlaybackControls'.
Type '(timeline: any, fallback: (animation: AnimationPlaybackControls) => VoidFunction) => () => void' is not assignable to type '(timeline: ProgressTimeline, fallback?: ((animation: AnimationPlaybackControls) => VoidFunction) | undefined) => VoidFunction'.
Types of parameters 'fallback' and 'fallback' are incompatible.
Type '((animation: AnimationPlaybackControls) => VoidFunction) | undefined' is not …
```

examples: upgrade framer-motion

---

docs/framework/react/start/getting-started.md

Must be enabled for app/router.tsx->createRouter()
_app/router.tsx line: 7_
```
Argument of type 
'{ routeTree: RootRoute<undefined, {}, AnyContext, AnyContext, {}, undefined, RootRouteChildren, FileRouteTypes>; }'
is not assignable to parameter of type '"strictNullChecks must be enabled in tsconfig.json"'.ts(2345)
```

docs(start): enable strictNullChecks

---

packages/react-router/src/router.ts
packages/react-router/tests/router.test.tsx

fix(react-router): reset `invalid` status of route after loader ran again

---

docs/config.json
docs/framework/react/api/router.md
docs/framework/react/api/router/linkOptions.md
docs/framework/react/guide/link-options.md
examples/react/kitchen-sink-file-based/src/routes/dashboard.tsx
examples/react/large-file-based/src/routes/linkProps.tsx
packages/react-router/src/index.tsx
packages/react-router/src/link.tsx
packages/react-router/tests/link.test-d.tsx

`linkOptions` is a new function which is similar to TanStack Query's `queryOptions` in naming. Similar to `queryOptions` it does not change the input in anyway but it provides type safety of object literals intended to be passed to `Link`, `navigate` or `redirect`.
For example, consider the following from one of our examples
```tsx
function DashboardComponent() {
return (
<>
<div className="flex items-center border-b">
<h2 className="text-xl p-2">Dashboard</h2>
</div>
<div className="flex flex-wrap divide-x">
{(
[
['/dashboard', 'Summary', true],
['/dashboard/invoices', 'Invoices'],
['/dashboard/users', 'Users'],
] as const
).map(([to, label, exact]) => {
return (
<Link
key={to}
to={to}
activeOptions={{ exact }}
activeProps={{ className: `font-bold` }}
className="p-2"
>
{label}
</Link>
) …
```

feat: add `linkOptions` for re-usable props

---

packages/react-router/src/path.ts
packages/react-router/tests/path.test.ts

In micro-frontend applications, host app will inject `basepath` to micro app. When the host app is navigating to its own route, the mounted micro apps will monitor and trigger redirect as well without respecting the `basepath`.

fix(react-router): fix matchPathname with basepath

---

packages/start/src/config/index.ts

Specifying experimental options for Vinxi get overridden by the `asyncContext: true` option.
This PR lets the experimental options such as Web Sockets be enabled.

fix(start): allow specifying vinxi experimental options

---

packages/react-router/src/router.ts

fix(react-router): do not copy `id` from lazy route over to non-lazy route

---

docs/eslint/create-route-property-order.md
packages/eslint-plugin-router/src/rules/create-route-property-order/constants.ts
packages/react-router/src/route.ts
packages/react-router/src/router.ts
packages/react-router/tests/route.test-d.tsx
packages/react-router/tests/routeContext.test.tsx

also do not pass search params into `context`, only `loaderDeps` (in analogy to `loader`)

fix(react-router): only execute context when params or loader deps change

---

packages/create-router/templates/bundler/rspack/rsbuild.config.ts

When no template is set, rspack uses their own template for build and the dev server. rspack default template uses root as div id, and no tailwind, causes first dev load to be blank.
https://rsbuild.dev/guide/basic/html-template
mountId could be set, but then a seperate index.html template is required. with
```html
<div id="<%= mountId %>"></div>
```

fix(create-router): Specify html template used by rspack

---

docs/framework/react/installation.md

docs: add missing spaces for comments in the installation guide

---

packages/react-router/src/router.ts

- refactor `matchRoutes` by moving the actual route matching into a separate function that can be called when only the routes are needed
- if `to` is available, use it for constant time route lookup

perf(react-router): improve location building performance

---

packages/react-router/src/RouterProvider.tsx
packages/react-router/src/link.tsx
packages/react-router/src/router.ts

fix(react-router): populate result of `validateSearch` into URL when navigating

---

packages/history/tests/parseHref.test.ts
packages/react-router/src/router.ts
packages/react-router/tests/redirect.test.tsx

fix(react-router): correctly handle hashes in `redirect`

---

docs/framework/react/guide/search-params.md

I noticed that there's an import missing for "retainSearchParams" inside the Search Params documentation page. 
**Before:** 
```ts
import { createFileRoute } from '@tanstack/react-router'
```
**After:**
```ts
import { createFileRoute, retainSearchParams } from '@tanstack/react-router'
```

docs: add missing import for `retainSearchParams`

---

examples/react/start-convex-trellaux/convex/_generated/api.d.ts
examples/react/start-convex-trellaux/convex/_generated/api.js
examples/react/start-convex-trellaux/convex/_generated/dataModel.d.ts
examples/react/start-convex-trellaux/convex/_generated/server.d.ts
examples/react/start-convex-trellaux/convex/_generated/server.js

Convex now uses prettierignore directives for generated files, update this so anyone running this locally isn't confused.

Update Convex codegen

---

docs/framework/react/comparison.md

Next.js' nested layouts are still far from being considered true first-class nested routes.
https://github.com/vercel/next.js/issues/44793#issuecomment-1634211402

docs: update nested routes comparison

---

examples/react/start-convex-trellaux/package.json
pnpm-lock.yaml

Bump convex version to ensure VITE_ prefix will be used for CONVEX_URL. This broke because the convex CLI looked for `vite` in dependencies and devDependencies but that's no longer a dependency.

Bump convex version to get VITE_ envvar prefix

---

docs/framework/react/guide/navigation.md
packages/react-router/src/link.tsx
packages/react-router/src/router.ts
packages/react-router/src/utils.ts
packages/react-router/tests/link.test.tsx
packages/react-router/tests/utils.test.ts

implements the feature requested in #2566

feat(react-router): allow to explicitly check if a search prop is not set

---

packages/react-router/src/utils.ts
packages/react-router/tests/link.test.tsx
packages/react-router/tests/utils.test.ts

Small follow-up to #2592, as I noticed that it doesn't quite seem to work as I think would be expected - it does correctly _exclude_ the route when the parameter exists, however it doesn't _match_ the route when it doesn't. In other words, there's currently no way for `explicitUndefined` links to ever match a route. This PR fixes that.

fix(react-router): fix explicitUndefined links never matching

---

examples/react/start-convex-trellaux/.env.local.example
examples/react/start-convex-trellaux/.stackblitzrc
examples/react/start-convex-trellaux/app/routeTree.gen.ts
examples/react/start-convex-trellaux/convex/crons.ts

Custom StackBlitz dev command that uses a shared backend. This makes https://tanstack.com/router/v1/docs/framework/react/examples/start-convex-trellaux usable.
Clear this shared table every 20 minutes.

examples: use a shared Convex backend for StackBlitz

---

examples/react/start-convex-trellaux/.stackblitzrc

https://github.com/TanStack/router/pull/2606 didn't work, maybe the problem was the trailing comma? I'll try to test this first.

examples: no trailing comma in stackblitzrc

---

docs/framework/react/start/getting-started.md

- remove non-null assertion from client entry, throw if element cannot be found
- add namespace to fs import
- add type attribute to button
just some thoughts that my linter had ;)

docs(start): update the getting-started guide's template

---

packages/react-router/src/link.tsx

fix(react-router): do not refer to deprecated global `JSX` namespace

---

packages/react-router/src/path.ts
packages/react-router/src/router.ts
packages/react-router/tests/path.test.ts

fix(react-router): basepath case sensitivity during path resolution

---

docs/framework/react/api/router/stripSearchParamsFunction.md

Also dropped the `The`, hope that's fine 😇

docs(react-router): fix typo in stripSearchParamsFunction.md

---

docs/framework/react/api/router/LinkOptionsType.md
docs/framework/react/api/router/RouterOptionsType.md
docs/framework/react/guide/preloading.md
packages/react-router/src/link.tsx
packages/react-router/src/router.ts
packages/react-router/tests/link.test.tsx

This is the last preloading strategy which was left to implement.
This option makes it so that a preload will be fired off as soon as the Link component is rendered into the DOM. Once fired, it won't ever fire again unless the component is destroyed.

feat(react-router): add `preload='render'` support

---

packages/start/src/config/index.ts

This PR fixes the `Could not auto-determine entry point from rollupOptions or HTML files, and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.` warning.

fix(start): Could not auto-determine entry point

---

packages/react-router/src/Transitioner.tsx

fix(react-router): correctly set `pathChanged` in router events

---

packages/react-router/src/index.tsx

`React.ComponentProps<LinkComponent<'a'>>` was not bringing in the generated types for props.params, but `LinkComponentProps` does.
FWIW: My specific user case is I'm creating a wrapper component around `<Link />` that supports `href` as an alias for `to` to support some existing code. Using `createLink` was not working properly in this case.

refactor(react-router): export `LinkComponentProps` type

---

docs/framework/react/start/overview.md

I can't repro an issue here but Tanner is still seeing a height 80px, maybe this helps

docs(Start) fix Convex logo size again

---

packages/start/src/config/index.ts

Before:
After:
Related issues:
https://github.com/colinhacks/zod/issues/2491#issuecomment-1580726666

fix(start): correct input config types

---

packages/router-generator/src/filesystem/virtual/loadConfigFile.ts

```
♻️  Generating routes...
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
```

fix(router-generator): fix virtual file routes on windows

---

packages/router-generator/src/filesystem/physical/getRouteNodes.ts
packages/router-generator/src/filesystem/virtual/getRouteNodes.ts

The issues:
This also fix: https://github.com/TanStack/router/pull/2694

fix(router-generator): fix path for virtual file routes on Windows

---

docs/framework/react/guide/file-based-routing.md

Updated the wording in the TanStack Router documentation to improve clarity by removing redundant text.

docs: revise wording in TanStack Router documentation

---

docs/framework/react/api/router/RouterOptionsType.md
docs/framework/react/guide/path-params.md
packages/react-router/src/path.ts
packages/react-router/src/router.ts
packages/react-router/tests/path.test.ts
packages/react-router/tests/router.test.tsx
packages/router-generator/src/config.ts

Currently any path params with a "@" character are URI encoded. Modern browsers handle this fine and it is a common pattern (e.g. youtube.com/@exampleChannel) to have them unencoded in a path.

feat(react-router): allow unencoded characters in dynamic path segments

---

packages/react-router/src/ScriptOnce.tsx

This PR addresses an issue in ScriptOnce where console.info caused a SyntaxError due to improperly escaped special characters in the route path, particularly when using routes with splat parameters and search parameters.
**Problem**
Previously, console.info was implemented with a template literal, like so:
```ts
? `console.info(\`Injected From Server:
${children}\`)`
: ''
```
This approach led to issues when special characters (e.g., backticks or `${}`) appeared in `children`, as they were interpreted as part of the template literal, resulting in a malformed string and ultimately a `SyntaxError`.
**Solution**
The fix replaces the template literal with string concatenation using double quotes:
```ts
? "console.info('Injected From Server:\\n" + children + "');"
: ''
```
By using a standard …

fix(react-router): Fix hydration SyntaxError in ScriptOnce by changing template literal to string concatenation in console.info

---

packages/react-router/package.json
packages/react-router/src/ScriptOnce.tsx
pnpm-lock.yaml

This PR introduces an additional fix for `ScriptOnce` to handle cases where the `children `payload contains single quotes (`'`). After the previous update, which switched `console.info` to use double quotes with concatenation, an issue arose when single quotes appeared within `children`, leading to a `SyntaxError`.
**Problem**
The current implementation uses:
```ts
console.info('Injected From Server:\\n' + children + '');
```
When `children `contains single quotes, they are not escaped, which breaks the `console.info` statement and causes the application to throw a syntax error.
**Solution**
This PR escapes single quotes in `children `to ensure they do not interfere with the `console.info` syntax:
```ts
console.info('Injected From Server:\\n' + children.replace(/'/g, "\\'") + '');
``` …

fix(react-router): Fix SyntaxError in ScriptOnce by escaping single quotes in console.info

---

examples/react/kitchen-sink-file-based/src/routes/dashboard.users.tsx
examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.users.tsx
examples/react/kitchen-sink-react-query/src/main.tsx
examples/react/kitchen-sink/src/main.tsx

The current examples use the deprecated preSearchFilters prop for route creation.
This change would modify the examples to use the updated search middleware instead.

docs(router): replace deprecated preSearchFilters with search middlewares in examples

---

packages/start/src/client/createMiddleware.ts
packages/start/src/client/createServerFn.ts

Just constrains the validation generic to require it to implement AnyValidator.
This would have caught the error in https://github.com/TanStack/router/issues/2759:

improve internal middleware validation typings

---

packages/start/src/server-handler/index.tsx

Throw an error when the request method is GET and `Content-Type` header contains `multipart/form-data`.
Currently, it does the opposite - it throws an error for valid requests and accepts only `GET` with multipart content type.

fix(start): fix request method check for multipart payloads

---

packages/start/src/client/createMiddleware.ts

AnyMiddleware had a strict requirement on AnyValidator that broke middleware types with serverFn.
Was introduced in: [4d7c669](https://github.com/TanStack/router/commit/4d7c6697f444e5547cb5adae987cdd98c0da0a83)
closes: https://github.com/TanStack/router/issues/2769

fix: AnyMiddleware typings (createServerFn, with middleware)

---

e2e/start/basic/app/routes/server-fns.tsx
e2e/start/basic/tests/app.spec.ts
packages/start/src/client-runtime/fetcher.tsx
packages/start/src/client/createServerFn.ts

- Ensure context is included when serializing `FormData` on the client (serialized using default transformer and added to the `__TSR_CONTEXT` field in the payload)
- Add input type check on the server and, if it's `FormData`, extract context value from the `__TSR_CONTEXT` field before passing the actual payload to the middleware
- Add E2E test for `multipart/form-data` form submission

fix(start): Fix `FormData` handling in server functions

---

docs/framework/react/start/hosting.md

it seems like nitro and therefore vinxi rely on `node:async_context` to run. while cloudflare doesn't have support for the required API to make this work. the nitro team has started working on this on their package `unenv` in [tacked this issue](https://github.com/nitrojs/nitro/issues/1943)
until this is integrated in nitro, we need to manually point to the latest version of `unenv` in the `app.config.ts`:
```tsx
import { defineConfig } from "@tanstack/start/config";
import { cloudflare } from "unenv";
export default defineConfig({
server: {
preset: "cloudflare-pages",
unenv: cloudflare,
},
});
```
i've updated the hosting documentation to include this and also remove the build command that was attached as it's not possible to pass an unenv via the CLI
related issues: …

docs(start): update `cloudflare-pages` deployment instructions

---

docs/framework/react/guide/tanstack-start.md
docs/framework/react/start/getting-started.md
docs/framework/react/start/server-functions.md
examples/react/start-counter/app/routes/index.tsx

Since the default method is GET I think it's correct to explicitly set these examples to POST

docs(start): explicitly set POST method `updateCount` server function examples

---

packages/start/src/client/Meta.tsx
packages/start/src/client/tests/index.test.tsx

As we're already doing for meta tags as `<meta name="description" ... />` we should make sure there's only one each for meta tags with the property attribute as `<meta property="og:description" ... />`
This should also fix tanstack.com having up to 4 duplicate tags in some pages and multiple images in social previews.

fix(start): dedupe meta properties

---

docs/framework/react/quick-start.md

Hi! 
I found an unused variable (`React`) in the examples in the quick start guide, so I removed it.

docs: removal of unused import variables in the examples

---

packages/start/src/client/createServerFn.ts

Some implementations (namely Valibot) still include the value key for failure results, which is technically still correct in structural typing (since an object type is a *minimum* requirement). What can actually be relied on is that `result.issues` is undefined if the result is valid, as this is in the spec.
Currently failure results from Valibot are still treated as success - this PR flips to checking for `result.issues` instead of `result.value`.

fix(start): fix server function handling of standard schemas

---

packages/react-router/src/router.ts

see #2841 for full explanation

Copy standard schema fix to search validation

---

packages/router-generator/src/config.ts

Closes #2814 
Changes the route template in the generator from returning:
```
return 'Hello /foo/!'
```
To now return valid JSX:
```
return <div>Hello "/foo/"!</div>
```

fix(router-generator): initial route template should return JSX

---

docs/framework/react/start/server-functions.md

Currently [this example](https://tanstack.com/router/latest/docs/framework/react/start/server-functions#formdata-parameters) has a type error:
because:
At first I ended up type casting `event.target` but there's a better solution: use `event.currentTarget`.
For context: `event.currentTarget` refers to the element the event handler is attached to, while `event.target` refers to the element that fired the event. [Src](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget)

docs(start): `FormData` to use `e.currentTarget` instead of `e.target`

---

docs/framework/react/guide/data-loading.md

Add info on accessing loader data from components in the data loading page

docs(router): usage of accessing the loaderData on the data-loading guide

---

packages/start/src/client-runtime/getBaseUrl.tsx
packages/start/src/config/index.ts

From https://discord.com/channels/719702312431386674/1238170697650405547/1310860918048948224
The actual server function fetch calls weren't actually respecting the configured `routers.server.base` value, instead using the hardcoded value of `/_server`.

fix(start): use configured server base for server function fetch

---

packages/react-router/src/Matches.tsx
packages/react-router/src/route.ts
packages/start/src/client/createMiddleware.ts
packages/start/src/client/createServerFn.ts
packages/start/src/client/tests/createServerFn.test-d.tsx

This reduces instantiations of start types and some router types. Mostly middleware/server fns should type check faster after caching but also sprinkled in some variance annotations to help the language service for middleware
Before
```> tsc --extendedDiagnostics
Files:                        1175
Lines of Library:            40097
Lines of Definitions:       198118
Lines of TypeScript:         32262
Identifiers:                314481
Symbols:                    508239
Types:                      156072
Instantiations:            2714633
Memory used:               587444K
Assignability cache size:    67144
Identity cache size:         15480
Subtype cache size:          44949
Strict …
```

perf(start): improve typescript performance of start types

---

README.md

It's currently showing 7k downloads per month, while it's actually 1M per month!

chore: fix npm downloads badge

---

examples/react/router-monorepo-react-query/packages/router/package.json
examples/react/router-monorepo-simple/packages/router/package.json
packages/react-router/src/RouterProvider.tsx
packages/react-router/src/router.ts
packages/react-router/tests/router.test-d.tsx
pnpm-lock.yaml

Changes type of history in router to a generic type parameter to support advanced use cases like providing an own implementation of a `RouterHistory` or to enchance a specific `RouterHistory` with additional features.

feat(react-router): generic router history

---

docs/framework/react/installation.md
docs/framework/react/quick-start.md

This PR adds information how to use Deno for package management with TanStack Router.
(All of the following have been tested and confirmed using Deno v2.1.2)
- Adds `deno add` command to the options for package managers (now that Deno can manage NPM packages)
- Adds `deno init` command to the options for scaffolding a new project
- Adds `deno add` commands to the options for manually creating a new project

docs: Add instructions for using Deno for install and quickstart

---

packages/start/src/client/index.tsx

In a monorepo setup where middlewares and serverFn are declared in different packages. Some types have issues with inference.
Example:
```
export const authenticated = createMiddleware().server(async ({ next }) => {
const session = await getSession();
if (!session) {
throw redirect({
to: "/sign-in/$",
});
}
return await next({
context: {
session,
},
});
});
```
Reports:
```
The inferred type of 'authenticated' cannot be named without a reference to '../../../../node_modules/@tanstack/start/dist/esm/client/createMiddleware'. This is likely not portable. A type annotation is necessary.ts(2742)
```
Workaround:
```
// TODO: temporary fixes inferred types
export { type MiddlewareAfterServer } from "../../../../node_modules/@tanstack/start/dist/esm/client/createMiddleware";
export const …
```

refactor(start): export the `MiddlewareAfterServer` type

---

packages/react-router/src/router.ts

I'm getting error while running tests with jsdom 25.0.1 and vitest, but without importing:
```js
// setupTests.tsx
// if this line is missing, I'm getting error below
// import '@testing-library/jest-dom/vitest'
```
```
TypeError: Cannot read properties of undefined (reading 'supports')
at Router.update (file:///C:/Users/lislo/src/other/env-hopper/node_modules/@tanstack/react-router/src/router.ts:881:25)
at new Router (file:///C:/Users/lislo/src/other/env-hopper/node_modules/@tanstack/react-router/src/router.ts:773:10)
at Module.createRouter (file:///C:/Users/lislo/src/other/env-hopper/node_modules/@tanstack/react-router/src/router.ts:679:10)
at Module.createEhRouter (C:\Users\lislo\src\other\env-hopper\apps\frontend\src\createEhRouter.ts:15:10)
at given …
```

fix: safely access window.CSS.supports

---

packages/react-router/src/index.tsx
packages/react-router/src/validators.ts
packages/start/src/client/createMiddleware.ts
packages/start/src/client/createServerFn.ts
packages/start/src/client/index.tsx
packages/start/src/client/tests/createServerFn.test-d.tsx

Fixes #2780 
I had an idea how to fix this while making the types a bit more effecient
Before
```
> tsc --extendedDiagnostics
Files:                        1176
Lines of Library:            40097
Lines of Definitions:       198223
Lines of TypeScript:         32262
Identifiers:                314782
Symbols:                    502815
Types:                      148050
Instantiations:            2145468
Memory used:               576553K
Assignability cache size:    60760
Identity cache size:         15475
Subtype cache size:          44949
Strict subtype cache size:       9
I/O Read time:               0.19s
Parse time:                  0.94s
ResolveModule time:          0.58s …
```

fix(start): allow types to override for input and context

---

packages/react-router/src/transformer.ts
packages/start/src/client/serialization.tsx

refactor(react-router,start): use react prefixed `JSX` types

---

packages/react-router-with-query/package.json
packages/react-router/package.json
packages/router-cli/package.json
packages/valibot-adapter/package.json
packages/zod-adapter/package.json

Removes the hard locks on our packages towards other packages in the repo, thereby allowing the package versions to be free floating and letting package managers maintain a single source.
```diff
{
"dependencies": {
-		"@tanstack/react-router": "workspace:*"
+ 		"@tanstack/react-router": "workspace:^",
}
}
```
Related to https://github.com/TanStack/router/issues/2540#issuecomment-2521870993

fix: remove hard locks on related packages

---

packages/react-router/src/router.ts
packages/react-router/tests/route.test.tsx

We found that creating a route with `createRoute` would not expose links and scripts where as when creating a route with `createFileRoute` the link and script properties would exist as expected. We expect the behaviour to be the same across the board.

fix(react-router): ensure links and scripts are available on routes created with `createRoute`

---

docs/framework/react/guide/deferred-data-loading.md

docs(router): update deferred data loading guide when using external libraries

---

e2e/start/basic/app/routeTree.gen.ts
e2e/start/basic/app/routes/isomorphic-fns.tsx
e2e/start/basic/tests/base.spec.ts
packages/start-vite-plugin/src/compilers.ts
packages/start-vite-plugin/src/index.ts
packages/start-vite-plugin/tests/createIsomorphicFn/createIsomorphicFn.test.ts
packages/start-vite-plugin/tests/createIsomorphicFn/snapshots/client/createIsomorphicFnDestructured.tsx
packages/start-vite-plugin/tests/createIsomorphicFn/snapshots/client/createIsomorphicFnDestructuredRename.tsx
packages/start-vite-plugin/tests/createIsomorphicFn/snapshots/client/createIsomorphicFnStarImport.tsx
packages/start-vite-plugin/tests/createIsomorphicFn/snapshots/server/createIsomorphicFnDestructured.tsx
packages/start-vite-plugin/tests/createIsomorphicFn/snapshots/server/createIsomorphicFnDestructuredRename.tsx
packages/start-vite-plugin/tests/createIsomorphicFn/snapshots/server/createIsomorphicFnStarImport.tsx
packages/start-vite-plugin/tests/createIsomorphicFn/test-files/createIsomorphicFnDestructured.tsx
packages/start-vite-plugin/tests/createIsomorphicFn/test-files/createIsomorphicFnDestructuredRename.tsx
packages/start-vite-plugin/tests/createIsomorphicFn/test-files/createIsomorphicFnStarImport.tsx
packages/start/src/client/createIsomorphicFn.ts
packages/start/src/client/index.tsx
packages/start/src/client/tests/createIsomorphicFn.test-d.ts

see https://github.com/TanStack/router/discussions/2937 for a full brief of this idea.
Allows creating a function with different implementations for server and client.
```ts
import { getRequestURL } from "vinxi/http"
const getIsomorphicUrl = createIsomorphicFn()
.server(getRequestURL)
.client(() => new URL(window.location.href));
// server
import { getRequestURL } from "vinxi/http"
const getIsomorphicUrl = getRequestURL
// client
const getIsomorphicUrl = () => new URL(window.location.href)
```
Any implementations not provided will default to no-ops.
```ts
const serverOnlyFn = createIsomorphicFn().server(() => "foo");
// server
const serverOnlyFn = () => "foo"
// client
const serverOnlyFn = () => {}
```
Not providing any implementations is allowed, but a warning will be logged as this is …

feat(start): createIsomorphicFn

---

e2e/start/basic/app/routeTree.gen.ts
e2e/start/basic/app/routes/env-only.tsx
e2e/start/basic/tests/base.spec.ts
packages/start-vite-plugin/src/compilers.ts
packages/start-vite-plugin/src/index.ts
packages/start-vite-plugin/tests/envOnly/envOnly.test.ts
packages/start-vite-plugin/tests/envOnly/snapshots/client/envOnlyDestructured.tsx
packages/start-vite-plugin/tests/envOnly/snapshots/client/envOnlyDestructuredRename.tsx
packages/start-vite-plugin/tests/envOnly/snapshots/client/envOnlyStarImport.tsx
packages/start-vite-plugin/tests/envOnly/snapshots/server/envOnlyDestructured.tsx
packages/start-vite-plugin/tests/envOnly/snapshots/server/envOnlyDestructuredRename.tsx
packages/start-vite-plugin/tests/envOnly/snapshots/server/envOnlyStarImport.tsx
packages/start-vite-plugin/tests/envOnly/test-files/envOnlyDestructured.tsx
packages/start-vite-plugin/tests/envOnly/test-files/envOnlyDestructuredRename.tsx
packages/start-vite-plugin/tests/envOnly/test-files/envOnlyStarImport.tsx
packages/start/src/client/envOnly.ts
packages/start/src/client/index.tsx
packages/start/src/client/serverOnly.ts
packages/start/src/client/tests/envOnly.test-d.ts

fixes #2938 
fixes #2828
This makes the following changes to serverOnly:
- Changes types to allow passing any function, not just ones that don't accept any arguments (and fixes return type, as the replacement function throws instead of no-op'ing)
- Changes replacement function to actually throw an error instead of referencing a missing `invariant` function
- Extracts out function instead of passing to serverOnly in runtime
This also adds `clientOnly`, which does the same as `serverOnly` but for the client.

fix(start): fix serverOnly implementation/types, and add clientOnly counterpart

---

packages/start/package.json
packages/start/src/client/json.ts
packages/start/src/client/tests/index.test.tsx
packages/start/src/client/tests/json.test.ts
packages/start/vite.config.ts

This PR was originally meant to just be an improvement for the json() helper, but in the process of writing a unit test for it, I realised that unit tests in the @tanstack/start package were not being run.
The existing headers merging wouldn't work correctly for arrays of entries, or Headers instances, both of which were allowed by the types. This PR fixes that by contructing a Headers instance ourselves, *then* adding the Content-Type header.

fix(start): Fix json() helper merging of headers, and set up unit tests for @tanstack/start

---

packages/start-vite-plugin/src/compilers.ts
packages/start-vite-plugin/tests/createIsomorphicFn/createIsomorphicFn.test.ts
packages/start-vite-plugin/tests/envOnly/envOnly.test.ts

createServerFn checks that it's assigned to a variable because the compiled code references that variable.
createIsomorphicFn and envOnly functions don't have this restriction, so we don't actually need this check.
It also causes issues when the AST has something else before the variable, for example 
```ts
const test = serverOnly(fn) as Type
```
The parent path in this AST would be the `as` expression, not the variable declaration.

fix(start): Remove variable check for createIsomorphicFn and envOnly functions.

---

packages/router-cli/src/watch.ts
packages/router-generator/src/config.ts
packages/router-generator/src/index.ts
packages/router-plugin/src/core/constants.ts
packages/router-plugin/src/core/router-generator-plugin.ts

Removes all hard coded references to `tsr.config.json`.
This PR removes all assumptions in code related to the filename of the config file and will eventually allow for configs to be defined in other formats.

refactor: remove hardcoded references to `tsr.config.json`

---

examples/react/start-clerk-basic/app/routes/__root.tsx
examples/react/start-clerk-basic/app/routes/_authed.tsx

The current example gets the entire user object from getAuth(). This causes a serialization error, and is also inconsistent with the clerk documentation.
This pull request resolves this issue by simply changing the clerk getAuth() call to only retrieve and return the userId.

docs(start): fix serialization error in clerk auth example

---

docs/framework/react/comparison.md

As of React Router 7, [everything is in the `react-router` package](https://reactrouter.com/upgrading/v6#upgrade-to-v7), and [`react-router-dom` just re-exports `react-router` for compatibility](https://api.reactrouter.com/v7/modules/react_router_dom.html).

Update React Router 7 bundle size

---

packages/react-router/src/link.tsx

I think this is a typo.
There are many instances with `TRouter extends AnyRouter`: https://github.com/search?q=repo%3ATanStack%2Frouter+%22TRouter+extends+AnyRouter%22&type=code
There are a few other instances with `TRouter extends RegisteredRouter` which should probably be audited: https://github.com/search?q=repo%3ATanStack%2Frouter+%22TRouter+extends+RegisteredRouter%22&type=code.

fix(react-router): use correct type for TRouter generic

---

docs/framework/react/guide/navigation-blocking.md

This is something really small. I'd expect for the `reject` of the example `SaveBlocker`:
```
<SaveBlocker
confirm={() => {
modals.closeAll()
resolve(true)
}}
reject={() => {
modals.closeAll()
resolve(true)
}}
/>
```
to block the navigation instead of letting in through, as it currently does.
I also think that having the inverted shouldLeave is needlessly confusing when not using `window.confirm`.

docs: Slightly improve navigation-blocking.md to avoid confusion

---

packages/react-router/src/router.ts

fix(react-router): make sure full matches are passed into route functions

---

docs/framework/react/quick-start.md

Manually adding TanStack Router to existing Vite React project also needs @tanstack/react-router package

docs: Add install line to Manual Setup code block on Quick Start page

---

packages/react-router/src/Matches.tsx
packages/react-router/src/link.tsx
packages/react-router/src/redirects.ts
packages/react-router/src/route.ts
packages/react-router/src/useLoaderData.tsx
packages/react-router/src/useLoaderDeps.tsx
packages/react-router/src/useMatch.tsx
packages/react-router/src/useNavigate.tsx
packages/react-router/src/useParams.tsx
packages/react-router/src/useRouteContext.ts
packages/react-router/src/useSearch.tsx
packages/react-router/tests/link.bench.tsx

fix: use const type parameters

---

e2e/start/basic/app/routeTree.gen.ts
e2e/start/basic/app/routes/__root.tsx
e2e/start/basic/app/routes/scripts.tsx
e2e/start/basic/public/script.js
e2e/start/basic/public/script2.js
e2e/start/basic/tests/base.spec.ts
e2e/start/basic/tsconfig.json
packages/start/src/client/Scripts.tsx
packages/start/src/client/tests/index.test.tsx

The filtering before is like:
```ts
// ...
select: (state) => {
// Assume here:
// `[[undefined], undefined]`
const scriptsOfEachMatch = state.matches.map((match) => match.scripts)
// Filtered:
// `[[undefined]]`
const truthyScriptsOfEachMatch = scriptsOfEachMatch.filter(Boolean)
// Turns out to be:
// `[undefined]`
// which will cause `TypeError` when `undefined` gets destructured below
const truthyScripts = truthyScriptsOfEachMatch.flat(1)
return {
scripts: truthyScripts.map(({ children, ...script }) => ({ // <- TypeError: Cannot destructure property 'children' of 'undefined' as it is undefined.
// ...
})),
}
},
// ...
```
Which will cause error when specifying `scripts` like:
```ts
export const Route = createRootRoute({
head: () => ({
// ...
scripts: [undefined], // Passes type check …
```

fix(start): fixed route scripts filtering

---

packages/create-start/package.json
packages/create-start/src/modules/core/index.ts
pnpm-lock.yaml

Avoid import assert syntax that doesn't work in Node.js 22

---

packages/react-router/src/router.ts
packages/react-router/tests/routeContext.test.tsx

fix(react-router): ensure updated context in `beforeLoad` when returning same properties

---

docs/framework/react/api/router.md
docs/framework/react/api/router/useCanGoBack.md
e2e/react-router/basic-file-based/src/routes/__root.tsx
e2e/react-router/basic-file-based/src/routes/posts.$postId.tsx
e2e/react-router/basic-file-based/src/routes/posts.tsx
e2e/react-router/basic-file-based/tests/app.spec.ts
packages/history/src/index.ts
packages/react-router/src/index.tsx
packages/react-router/src/router.ts
packages/react-router/src/useCanGoBack.ts
packages/react-router/tests/router.test.tsx
packages/react-router/tests/useBlocker.test-d.tsx
packages/react-router/tests/useCanGoBack.test.tsx

feat(react-router): add useCanGoBack

---

docs/framework/react/guide/code-splitting.md

codesplitting documentation has this typo issue. Here it should comes as getParentRoute but it was wrongly typed as getParent

Typo issue - getParent Does not Exists in type RouteOptions

---

docs/framework/react/start/server-functions.md

The docs had the wrong import for `notFound`

Fix notFound import in server-function docs for @tanstack/start

---

docs/framework/react/guide/deferred-data-loading.md

See https://tanstack.com/router/latest/docs/framework/react/guide/deferred-data-loading
Typo introduced in https://github.com/TanStack/router/pull/2963

docs: fix dead link and typo in deferred data loading guide

---

docs/framework/react/api/router/RouterType.md
packages/history/src/index.ts
packages/react-router/src/link.tsx
packages/react-router/src/location.ts
packages/react-router/src/router.ts
packages/react-router/src/utils.ts

Fixes `__TSR_index` being required when navigating with custom user provided state.
fixes #3130

fix(react-router): separate internal and user provided history state

---

packages/router-generator/src/filesystem/virtual/getRouteNodes.ts

There is an issue with Virtual File Router when [config provided as as path](https://tanstack.com/router/latest/docs/framework/react/guide/virtual-file-routes#configuration-via-the-tanstackrouter-plugin).
For some reason there is an explicit default export added
an there is clearly no default export provided in original config:
```ts
import { index, rootRoute, route } from '@tanstack/virtual-file-routes';
export const routes = rootRoute('root.tsx', [
index('index.tsx'),
route('about-us', 'about-us/index.lazy.tsx'),
]);
```
---
I've found a similar [issue](https://github.com/privatenumber/tsx/issues/427) in `tsx` package repo, and looks like it has something to do with internal module resolution of NodeJS, see [minimal reproduction](https://stackblitz.com/edit/stackblitz-starters-sykrfb?fil …

fix(router-generator) use explicit routes export by default

---

e2e/start/basic/app/routes/-server-fns/serialize-formdata-fn-call.tsx
e2e/start/basic/app/routes/server-fns.tsx
e2e/start/basic/tests/base.spec.ts
packages/react-router/src/transformer.ts

fix(start): serialize `FormData` for server function input

---

packages/react-router/src/transformer.ts
packages/react-router/tests/transformer.test.tsx

Although end-to-end tests were added for #3138, I forgot to add unit tests that only checked the functionality of the transformer itself.

test(react-router): check `FormData` serialization in transformer

---

docs/framework/react/guide/code-based-routing.md

docs(router): missing character in code-splitting guide

---

e2e/start/basic/app/routes/-server-fns/serialize-formdata-fn-call.tsx
packages/react-router/src/index.tsx
packages/react-router/src/transformer.ts
packages/react-router/tests/transformer.test.tsx

Also adds Error and FormData to the allowed list of "serializable" values in Typescript, and make createTransformer more helpful with its types.

fix(start): preserve multiple values for same key in `FormData` serialization

---

docs/framework/react/installation.md

While attempting to integrate Tanstack Router into an existing React 18 project which used the legacy `render` function, I've found that Tanstack Router requires use of React 18s concurrent renderer and does not function properly when using the legacy `render` function (example error while attempting to navigate, below). Updating one of the example projects to use the legacy `render` method also results in the error below being thrown on navigation.
- See this example repo for a reproduction: https://stackblitz.com/edit/tanstack-router-6idhfm1r?file=src%2Fmain.tsx
This updates the installation docs to call out this requirement.

docs(router): require the use of React's `createRoot` function

---

docs/framework/react/api/router.md
docs/framework/react/api/router/ParsedHistoryStateType.md
docs/framework/react/api/router/ParsedLocationType.md
docs/framework/react/api/router/historyStateInterface.md

Fixes docs for `ParsedLocation` type, adds docs for `ParsedHistoryState` type and clarifies how `HistoryState` interface should be extended
`HistoryState` should be extended in the `@tanstack/react-router` package, as trying to extend it in `@tanstack/history` might error due to the way package managers like pnpm structure the `node_modules/` folder.

docs(router): fix docs related to parsed state

---

docs/framework/react/start/build-from-scratch.md

When running `npm run dev`, vinxi fails with an error.
```
ERROR  Cannot read properties of undefined (reading 'server')                             
at createDevServer (node_modules/vinxi/lib/dev-server.js:111:27)
at Object.run (node_modules/vinxi/bin/cli.mjs:186:23)
at async runCommand (node_modules/citty/dist/index.mjs:316:16)
at async runCommand (node_modules/citty/dist/index.mjs:307:11)
at async runMain (node_modules/citty/dist/index.mjs:445:7) 
ERROR  Cannot read properties of undefined (reading 'server')      
```
Copying these lines from the example projects `app.config.ts` fixes the issue.

docs: Update build-from-scratch.md

---

packages/start/src/client/tsrScript.ts

Both `controller.enqueue` and `controller.close` [throw an error if the stream has already been closed](https://streams.spec.whatwg.org/#rs-default-controller-prototype).
This could be the case because the reading side just doesn't have interest in more incoming values and has closed the stream on the reading side.
Up until now, this would cause an error to be thrown on the console once more chunks or a close request were streamed in.
This wraps `.close` and `.enqueue` in a `try..catch` block and disregards the result.
Reading the standard I don't see any possible other reasons for an error to be thrown, so this should be fine.

fix(start): discard stream controller errors when closed

---

docs/framework/react/guide/preloading.md

Corrected effect snippets in [preloading#preloading-manually](https://tanstack.com/router/latest/docs/framework/react/guide/preloading#preloading-manually):
- Wrap preload calls inside async functions since they are awaited
- Specify `router` as a dependency

docs(preloading): correct effect snippets

---

docs/framework/react/quick-start.md

Clarify when exactly will `src/routeTree.gen.ts` be generated.

docs(router): update quickstart guide on when routeTree generation occurs

---

packages/react-router/src/router.ts

fix(react-router): broken docs link on the deprecation of the NotFoundRoute API

---

docs/framework/react/guide/data-mutations.md

Tiny fix on this page, that empty space (L15) was breaking the markdown list
<details><summary>Before</summary>
</details> 
<details><summary>After</summary>
</details>

docs(router): improve data mutations libraries list readability

---

packages/react-router/src/lazyRouteComponent.tsx

Issues currently on main for `lazyRouteComponent`:
1. The placeholder `ReactNode` used "while we wait for the page to reload" is not a valid react node
```tsx
return {
default: () => null,
}
```
Based on the comment messages around, and the git history, I'm assuming this is a typo brought from when error handling was done at the module loading level instead of in-render (see https://github.com/TanStack/router/commit/e5e80afbaa30d1581cafc1cbddd5022dba646c4b). There are 2 options now:
- `return null`
- `throw new Promise(() => {})`
My vote would go towards the suspense one, because this is the least likely to flash content before the page reloads, and instead will continue the loading state already triggered by the navigation that brought us here.
2. If the component re-renders "while we …

fix(react-router): improve error handling for module loading failures in lazyRouteComponent

---

docs/eslint/create-route-property-order.md
docs/framework/react/api/router/RouteOptionsType.md
docs/framework/react/api/router/RouterOptionsType.md
packages/eslint-plugin-router/src/rules/create-route-property-order/constants.ts
packages/react-router/src/Match.tsx
packages/react-router/src/Matches.tsx
packages/react-router/src/index.tsx
packages/react-router/src/route.ts
packages/react-router/src/router.ts
packages/react-router/tests/link.bench.tsx
packages/react-router/tests/router.test.tsx
packages/router-core/src/path.ts
packages/router-core/tests/path.test.ts

feat(react-router): add `remountDeps`

---

e2e/e2e-utils/package.json

chore: simplify e2e utils by removing build step

---

packages/start-server/package.json
pnpm-lock.yaml

Fixes https://github.com/TanStack/router/issues/3298
I think it makes sense to pin this version for now to maintain consistency and avoid type errors, while waiting for Vinxi to be removed.

fix(start): Ensure h3 versions match

---

e2e/start/basic/app/components/CustomMessage.tsx
e2e/start/basic/app/routes/index.tsx
packages/start-router-manifest/src/index.ts

Refactors #2286 to fit the current packages in use to supersede #2316 & #2286
Closes #1992
Closes #2179

fix(start-router-manifest): change code snippet to ALWAYS have HMR ready in development

---

packages/react-router/src/router.ts

Reload the document with `navigate` function now builds the correct location href, in cases where hash history is used.
Similar to: https://github.com/TanStack/router/pull/1414

fix(react-router): build correct `href` when reloading the document with `Router.navigate`

---

examples/react/router-monorepo-simple-lazy/packages/app/package.json
package.json
pnpm-lock.yaml

Nx released 20.4.1 https://github.com/nrwl/nx/releases/tag/20.4.1
That includes this PR https://github.com/nrwl/nx/pull/29795
That reverts the workaround in #3271

fix(examples): upgrade nx and remove implicitDependencies

---

packages/react-router/src/route.ts
packages/react-router/src/router.ts

Route's `router` prop is always undefined as it is not initialized anywhere.
Should it be assigned in `init()`?

refactor(react-router): remove unsed `router` prop from `Route` class

---

packages/router-cli/package.json
packages/router-plugin/package.json
packages/start-api-routes/package.json
packages/start-client/package.json
packages/start-config/package.json
packages/start-router-manifest/package.json
packages/start-server-functions-client/package.json
packages/start-server-functions-fetcher/package.json
packages/start-server-functions-handler/package.json
packages/start-server-functions-server/package.json
packages/start-server-functions-ssr/package.json
packages/start-server/package.json
packages/start/package.json

For some reason, the IDE does support `exports` section when using Yarn PnP.
But it still supports the old `types` entry.
2/3rds of the packages here already have this entry declared; the newer ones do not.
Thank you for your consideration, this would help my DX a lot!

fix: use top-level `types` in package.json for use in JetBrains IDEs

---

packages/router-plugin/src/core/code-splitter/compilers.ts
packages/router-plugin/src/core/router-code-splitter-plugin.ts
packages/router-plugin/tests/code-splitter.test.ts
packages/router-plugin/tests/code-splitter/snapshots/production/arrow-function.tsx
packages/router-plugin/tests/code-splitter/snapshots/production/chinese.tsx
packages/router-plugin/tests/code-splitter/snapshots/production/destructured-react-memo-imported-component.tsx
packages/router-plugin/tests/code-splitter/snapshots/production/function-declaration.tsx
packages/router-plugin/tests/code-splitter/snapshots/production/importAttribute.tsx
packages/router-plugin/tests/code-splitter/snapshots/production/imported-default-component-destructured-loader.tsx
packages/router-plugin/tests/code-splitter/snapshots/production/imported-default-component.tsx
packages/router-plugin/tests/code-splitter/snapshots/production/imported.tsx
packages/router-plugin/tests/code-splitter/snapshots/production/inline.tsx
packages/router-plugin/tests/code-splitter/snapshots/production/random-number.tsx
packages/router-plugin/tests/code-splitter/snapshots/production/react-memo-component.tsx
packages/router-plugin/tests/code-splitter/snapshots/production/react-memo-imported-component.tsx
packages/router-plugin/tests/code-splitter/snapshots/production/retain-exports-loader.tsx
packages/router-plugin/tests/code-splitter/snapshots/production/useStateDestructure.tsx

Currently, when using `automaticCodeSplitting`, as part of compiling the "reference" route, we add a component (named `TSRDummyComponent`) to aid with the HMR trickery.
In removing this component from the production bundle, it impacts the visitor by reducing the initial js bundle that wires the route-tree.

fix(router-plugin): reduce route-tree bundle size

---

packages/router-generator/src/config.ts
packages/router-generator/src/generator.ts
packages/router-generator/src/template.ts
packages/router-generator/tests/generator.test.ts
packages/router-generator/tests/generator/custom-scaffolding/routes/foo.lazy.tsx
packages/router-generator/tests/generator/custom-scaffolding/snapshot/foo.lazy.tsx

refactor(router-generator): support for more targets

---

packages/start-config/src/index.ts

Any particular reason to exclude the vite react plugin in the ssr router? Without it, we can't make effective use of react vite options such as babel transforms. 
For example, in order to use decorators with mobx, we need to add the `@babel/plugin-proposal-decorators` babel plugin (https://mobx.js.org/enabling-decorators.html#enabling-decorators). We can do this like so:
```ts
export default defineConfig({
react: {
babel: {
plugins: [
['@babel/plugin-proposal-decorators', { version: '2023-05' }]
],
},
},
})
```
However the react vite plugin is not included in the vinxi ssr router, which means any isomporphic code that requires decorators will break. Obv decorators are just one example - applies to any babel transformations the end user might want on both client and server.

fix(start): include vite react plugin in SSR router

---

e2e/react-router/basic-file-based-code-splitting/src/routeTree.gen.ts
e2e/react-router/basic-file-based-code-splitting/src/routes/__root.tsx
e2e/react-router/basic-file-based-code-splitting/src/routes/viewport-test.tsx
e2e/react-router/basic-file-based-code-splitting/tests/preload.spec.ts

Add a playwright end-to-end test for `viewport` preloading

test(e2e): add spec for `viewport="preload"`

---

docs/router/framework/react/guide/file-based-routing.md

I noticed that `files.watcherExclude` doesn't seem to be enough from preventing the issue, while `files.readonlyInclude` indeed works fine.
I rephrased that in the docs mentioning the three settings added in #3349 to the examples.

docs(router): more recommendations for route tree file opening unexpectedly on vscode

---

packages/start-api-routes/package.json
packages/start-router-manifest/package.json
packages/start-server-functions-client/package.json
packages/start-server-functions-fetcher/package.json
packages/start-server-functions-handler/package.json
packages/start-server-functions-server/package.json
packages/start-server-functions-ssr/package.json
packages/start-server/package.json
pnpm-lock.yaml

Vite was still be duplicated for me with Yarn PnP. Not a big deal, but indicating something was not entirely accurate.
All of these packages were declaring the react plugin, which would require them to also declare vite as a peer dep.
However, in all of these cases here the plugin was only being used in the vite configs, not being imported into src.
Moving them to dev removes the need to declare the peer dep, and fix the duplication problem by consumers.
I also removed vite from a couple of packages that declared them as a peer dep, which I had added in #3318, since this is the real solution.

fix: vite peer dependencies

---

docs/router/framework/react/guide/file-based-routing.md
packages/router-generator/src/generator.ts
packages/router-generator/src/template.ts
packages/router-generator/src/utils.ts

This PR adds a new configuration option (`formatter`) that allows the user to opt-out of having their route files auto formatted by Prettier.
This is useful when using a formatter other than Prettier (e.g. ESLint Stylistic, Biome, etc.)

fix(router-generator): prevent route file being auto-formatted during updates

---

packages/start-client/src/ssr-client.tsx

fix(start-client): use correct parent match when hydrating

---

packages/react-router/src/router.ts
packages/react-router/tests/navigate.test.tsx

fix(react-router): fix path param handling with relative navigation

---

packages/react-router-with-query/src/index.tsx

Added an optional 3rd argument to `routerWithQueryClient(...)` that allows the user to wrap the QueryClientProvider in a component.
This is useful when using a library that requires a Provider, and that provider creates its on queryClient, doesn't detect existing queryClients, and doesn't allow for supplying your own.
Without this functionality, the user has no ability to place the Vendor's provider above Tanstack's enshrined QCProvider. Thus, the queryClient available in the loaders references the correct (Tanstack) query client, while all hooks inside components would walk up the tree to find the the incorrect (Vendor) queryClient. This would potentially break auto-streaming with `useSuspenseQuery(...)` and de-sync hooks from loaders.
By giving an entrypoint to place a provider above …

feat: add WrapProvider to routerWithQueryClient

---

packages/start-client/src/createServerFn.ts
packages/start-client/src/tests/createServerFn.test-d.tsx

`fullResponse` introduced a small type issue when inferring the type of a server function. By default `fullResponse` should be false. And that is true at runtime but because a server function is now a inference site something like this:
```tsx
const fn = createServerFn().handler(() => 'test')
type test = ReturnType<typeof fn>
```
Would infer a union of `Promise<"test"> | Promise<FullFetcherData<undefined, "test">>`. This is because TypeScript will fallback to the constraint here (`boolean`) not the default.
This change flips the conditional so if `false` is a subset of `TFullResponse` then we can safely say the return type is `Promise<"test">` because it is possible that it is `false`

fix(start): use FetcherData by default for return type

---

packages/react-router/src/useNavigate.tsx
packages/react-router/tests/useNavigate.test.tsx

fix(react-router): only navigate once in StrictMode

---

packages/start-server-functions-ssr/src/index.tsx
packages/start-server/src/index.tsx
packages/start-server/tests/h3-wrappers.test-d.ts
packages/start-server/tsconfig.json

previously, type parameters weren't being passed through to wrapper functions, meaning things like `useSession<Data>(config)` didn't work properly.
This PR ensures the original signature is kept intact, along with providing specifically typed overloads for wrappers that need it.
breaking changes:
- getEvent returns H3Event, or throws an error if it couldn't find one. Previously it returned `any`, and didn't check whether event was truthy.

fix(start): ensure generic h3 functions remain generic, including new overloads

---

docs/router/framework/react/api/router/notFoundFunction.md

The `global` option is marked as deprecated.

docs(router): update `notFound` whole page example

---

docs/router/framework/react/guide/creating-a-router.md

The existing docs use the deprecated `notFoundRoute` rather than the new `notFoundComponent` key in the root route object.
I was going to update the code-based docs too, but I don't have that set up while I'm testing things out, so I wasn't sure if there were some differences with how that one is configured.

chore: update 404 route docs for file-based routing

---

e2e/start/server-functions/tests/server-functions.spec.ts

setup event handler before click to make sure we don't miss the event

tests: stabilize e2e test

---

docs/router/framework/react/quick-start.md

Dumb PR but this did trip me up when reading the docs and not using a quick start. On the fence if this is worthwhile or not.

docs(start): clarify that `__root.tsx` has two `_` characters

---

docs/start/framework/react/middleware.md
examples/react/start-basic/app/global-middleware.ts
examples/react/start-basic/app/server-functions.ts
examples/react/start-basic/app/utils/loggingMiddleware.tsx
packages/start-config/src/index.ts
packages/start-config/src/schema.ts
packages/start-plugin/src/index.ts

Fixes global middleware via a new `app/global-middleware.ts` file (configurable path) that is side-loaded automatically into the client and server-fn environment to ensure registerGlobalMiddleware will run in both environments
Fixes #3315

fix: global middleware

---

packages/solid-router/package.json
packages/solid-router/tsconfig.build.json

Looked at what Tanstack form does and this seems to fix part of the SSR issue. Doesn't solve the whole thing but gets us partially there.
https://github.com/TanStack/form/blob/main/packages/solid-form/tsconfig.build.json
Fixes part of the problem discussed here
https://github.com/TanStack/router/issues/3521

fix: solid-router for ssr

---

docs/router/framework/react/guide/routing-concepts.md

Saw this thread: https://x.com/mitsuhiko/status/1893686348571152745 and experienced some 404's myself. Ran into these tonight (and figured I ought to get my feet wet contributing to these docs if I can, since I can see myself wanting to help add a lot more where possible/needed).
CONTRIBUTING.md mentions:
> Be sure that internal links are written always relative to docs folder. E.g. ./guide/data-loading
These links lack a `/guide`, the URLs 404 in prod here: https://tanstack.com/router/latest/docs/framework/react/guide/routing-concepts
(maybe the real question is whether 2 ToC's are needed at the top of the file, but I suppose maybe that's better left up to the maintainers)

docs(router): remove unnecessary inline TOC in routing concepts guide

---

docs/start/framework/react/static-prerendering.md

currently the snippet is all gray (one color)

docs(start): missing syntax snippet from static-prerendering guide

---

docs/router/framework/react/guide/code-splitting.md
docs/router/framework/react/migrate-from-react-location.md
docs/router/framework/react/quick-start.md
docs/router/framework/react/routing/installation-with-vite.md

the plugin imported from `@vitejs/plugin-react` is called `react`, not `viteReact`.

docs(react-router): update import from `viteReact` to `react`

---

e2e/react-start/clerk-basic/package.json
examples/react/start-clerk-basic/package.json
pnpm-lock.yaml

This PR bumps `@clerk/tanstack-start` version to [0.11.0](https://github.com/clerk/javascript/releases/tag/%40clerk%2Ftanstack-start%400.11.0) which has a peer dependency of the updated `@tanstack/react-start` package

chore: Bump `@clerk/tanstack-start` dependencies to 0.11.0

---

examples/solid/basic-file-based/package.json
examples/solid/basic-file-based/src/routes/__root.tsx
examples/solid/basic-solid-query-file-based/package.json
examples/solid/basic-solid-query-file-based/src/routes/__root.tsx
examples/solid/basic-solid-query/package.json
examples/solid/kitchen-sink-file-based/package.json
examples/solid/kitchen-sink-file-based/src/routes/__root.tsx
examples/solid/quickstart-file-based/package.json
examples/solid/quickstart-file-based/src/routes/__root.tsx
pnpm-lock.yaml

Follow up to
- https://github.com/TanStack/router/pull/3585
@SeanCassiere the new examples import from workspace which breaks when opening them in stackblitz in the docs. 
This import the published versions, so it works
I also cleaned up references to react router devtools

docs(solid-router) fix examples that import workspace packages

---

packages/solid-router/src/link.tsx

We were getting a TypeError around this in the Tanstack Solid Start when working with it.
I am not sure if this is a proper fix as maybe something won't work as expected then?
The error we get is:
> TypeError: Cannot delete property 'disabled' of #<Object>

fix(solid-router): remove delete linkProps.disabled

---

packages/react-start-client/src/index.tsx

Example
```
import { createMiddleware } from "@tanstack/react-start";
export const middleware = createMiddleware();
```
Issue
```
The inferred type of middleware cannot be named without a reference to ../../../../node_modules/@tanstack/react-start-client/dist/esm/createServerFn . This is likely not portable. A type annotation is necessary.
```
Solution
exporting `ServerFnResponseType` resolves this.

fix(react-start-client): export `ServerFnResponseType` type

---

packages/solid-start-config/src/index.ts

It appear theres a `solid-` missing in this noExternal array
the package name is [solid-start-router-manifest](https://github.com/TanStack/router/blob/main/packages/solid-start-router-manifest/package.json)
aligning with react-start-config
- https://github.com/TanStack/router/blob/e2ac863540b3e9c009cb8c8d9f574d6cb6be28f6/packages/react-start-config/src/index.ts#L391
This fixes the dev server when using the prerelease versions

fix(solid-start-config): adjust package name in noExternal

---

docs/start/framework/react/build-from-scratch.md

Switched to pnpm but missed a second npm reference  
Initially, I only changed the first `npm` to `pnpm` and overlooked the second one, which caused an error:  
```
npm ERR! Cannot read properties of null (reading 'matches')
```
This held me up for a few minutes. To avoid similar issues, I suggest formatting commands with each command on a new line for better readability.  
Lesson learned: double-check commands before running them! :)

docs(start): fix installation script in "build-from-scratch" guide

---

packages/router-generator/src/filesystem/physical/getRouteNodes.ts
packages/router-generator/src/filesystem/virtual/getRouteNodes.ts
packages/router-generator/src/generator.ts
packages/router-generator/src/types.ts

Currently, we are tracking the different expected filesystem route types using individual boolean flags.
These are the current flags.
- `isRoot`
- `isRoute`
- `isLayout`
- `isAPIRoute`
- `isLazy`
- `isLoader` `@deprecated`
- `isComponent` `@deprecated`
- `isPendingComponent` `@deprecated`
- `isErrorComponent` `@deprecated`
This makes it possible for a route that's read from the filesystem, to get into an incorrect state either when reading the list of files or when performing updating in the core generator function.
The change being made, makes it so that a route will have a single `_fsRouteType` property attached to the route node so that it correctly describes the nature of the route when it was read from the filesystem.
| flag | `_fsRouteType` value |
|--------|--------|
| Default | …

refactor(router-generator): reduce use of `boolean` to identify file-system routes

---

packages/router-devtools/src/BaseTanStackRouterDevtoolsPanel.tsx
packages/router-devtools/src/Explorer.tsx
packages/router-devtools/src/TanStackRouterDevtools.tsx
packages/router-devtools/src/TanStackRouterDevtoolsPanel.tsx
packages/router-devtools/src/context.ts
packages/router-devtools/src/theme.tsx
packages/router-devtools/src/useStyles.tsx
packages/router-devtools/src/utils.ts

_Agnostic devtools step 1.5 of plan_
This is a follow up to below, so it'll be easier to review this diff after that is merged / rebased
- #3629 
This pr was entirely made by eslint --fix, with exception of manually adding a return type [here](https://github.com/TanStack/router/pull/3631/files#diff-c546297e16a8306a05e3da924970bcdb458d59da2794af391f6757680a1c38a1R66-R70) since the build would otherwise fail.

refactor(router-devtools): Adopt recommendations for React 19

---

packages/react-router/src/scroll-restoration.tsx
packages/solid-router/src/scroll-restoration.tsx

Fixes #3634 
Simply checking the type of `window.sessionStorage` is apparently enough to trigger `SecurityError`. To address it we use try/catch and set the var to true only if it's indeed available.

fix(react-router,solid-router): prevent crashes if sessionStorage isn't available

---

packages/history/src/index.ts
packages/history/tests/createHashHistory.test.ts

`parseLocation` in createHashHistory failed to parse search params when they appeared before the hash. This PR updates the parsing logic so that search params are correctly extracted and processed, regardless of their position.
fixes #3595

fix(history): `parseLocation` in createHashHistory to handle search params correctly

---

docs/router/framework/react/api/router/NavigateOptionsType.md

This PR adds viewTransition documentation to the NavigateOptionsType, giving users more info on how they can use the viewTransition API in Links and Navigates.
Will follow up in the next day or so with an example as well.

docs(router): add viewTransition docs in NavigateOptionsType

---

packages/react-router/src/router.ts
packages/react-router/tests/navigate.test.tsx
packages/solid-router/src/router.ts
packages/solid-router/tests/navigate.test.tsx

if `from` is not specified, it defaults to the leaf match

fix: allow relative `navigate` without `from`

---

e2e/react-router/basic-file-based/src/routes/__root.tsx
e2e/solid-router/basic-file-based/src/routes/__root.tsx
packages/react-router/src/router.ts
packages/solid-router/src/router.ts

Seems to fix the issue of `useRouterState` causing the client side navigation to break. Not sure why exactly this causes it to break but all the unit tests seem to pass without it.
Also helps unblock the devtools that @birkskyum is working on
Fixes #3639

fix: solid router crashing with useRouterState

---

packages/react-router/src/Match.tsx
packages/react-router/src/index.tsx
packages/react-router/src/redirects.ts
packages/react-router/src/router.ts
packages/router-core/src/index.ts
packages/router-core/src/redirect.ts
packages/solid-router/src/Match.tsx
packages/solid-router/src/index.tsx
packages/solid-router/src/redirects.ts
packages/solid-router/src/router.ts

Reverts TanStack/router#3662
The change appeared trivial, but apparently it broke CI (despite everything passing locally), so until I understand what went wrong I'd like to revert it.

Fix CI - Revert "refactor(react-router,solid-router): move redirect to router-core"

---

packages/react-start-plugin/src/index.ts

Fixes #3661
I tested this in my own codebase. With this change, the warnings are gone.
Rollup plugin docs specifically say that you should return `null` if you didn't transform anything. Vite follows rollup's API.

fix: transform should return null to preserve source maps. Fixes #3661

---

docs/start/framework/react/build-from-scratch.md

verbatimModuleSyntax can cause server bundles to quietly leak into client bundles via exported types. It is an easy mistake to make that can be _very_ difficult to debug.
Inspired by #3401

docs(start): Add note for verbatimModuleSyntax setting in tsconfig docs

---

docs/router/api/file-based-routing.md
docs/router/framework/react/routing/file-naming-conventions.md
package.json
packages/react-start-config/src/index.ts
packages/router-generator/src/config.ts
packages/router-generator/src/filesystem/physical/getRouteNodes.ts
packages/router-generator/src/generator.ts
packages/router-generator/tests/generator.test.ts
packages/solid-start-config/src/index.ts
packages/start-config/src/index.ts
pnpm-lock.yaml

We've gotten confusion about the default for generating the template for API routes when the user is only using TanStack Router. Since API routes, is a TanStack Start only feature, this internal flag would stop the `router-generator` from generating the API routes default template for non-Start apps.

refactor(router-generator): add internal `__enableAPIRoutesGeneration` flag

---

e2e/react-router/scroll-restoration-sandbox-vite/.gitignore
e2e/react-router/scroll-restoration-sandbox-vite/package.json
e2e/react-router/scroll-restoration-sandbox-vite/playwright.browser.config.ts
e2e/react-router/scroll-restoration-sandbox-vite/playwright.hash.config.ts
e2e/react-router/scroll-restoration-sandbox-vite/src/main.tsx
e2e/react-router/scroll-restoration-sandbox-vite/tests/app.spec.ts
e2e/react-router/scroll-restoration-sandbox-vite/tsconfig.json
e2e/solid-router/scroll-restoration-sandbox-vite/.gitignore
e2e/solid-router/scroll-restoration-sandbox-vite/package.json
e2e/solid-router/scroll-restoration-sandbox-vite/playwright.browser.config.ts
e2e/solid-router/scroll-restoration-sandbox-vite/playwright.hash.config.ts
e2e/solid-router/scroll-restoration-sandbox-vite/src/main.tsx
e2e/solid-router/scroll-restoration-sandbox-vite/src/routeTree.gen.ts
e2e/solid-router/scroll-restoration-sandbox-vite/tests/app.spec.ts
e2e/solid-router/scroll-restoration-sandbox-vite/tsconfig.json
packages/react-router/src/scroll-restoration.tsx
packages/solid-router/src/scroll-restoration.tsx

The `restoreScroll` function was directly interfacing with `window.location.hash` to get the 'hash' value, which conflicts with how hash routing functions. As such, when the hash value was retrieved, it came back as `#/page#foo` instead of just `#foo` like it would with regular browser history.
Switching it to use the `history` driver attached to the `router` instance, correctly returns the `hash` value irrespective of the type of routing being used.
Fixes #3479

fix(react-router,solid-router): scroll to element does not work for hash history

---

e2e/react-router/scroll-restoration-sandbox-vite/package.json
e2e/solid-router/scroll-restoration-sandbox-vite/package.json
packages/react-router/src/scroll-restoration.tsx
packages/solid-router/src/scroll-restoration.tsx

#3700 introduced an unintended side-effect with the scroll restoration process in TanStack Start.
This revets the code changes in `@tanstack/react-router` and `@tanstack/solid-router` and short-circuits the tests relevant test scripts introduced in the offending PR.

revert(react-router,solid-router): revert #3700

---

docs/router/framework/react/api/router/NavigateOptionsType.md
docs/router/framework/react/guide/navigation.md

This PR adds missing documentation for both the NavigationOptions type and the Navigation guide.

docs(router): improve navigation guide and NavigateOptions documentation

---

docs/router/framework/react/quick-start.md
docs/router/framework/solid/quick-start.md

This use the new create-tsrouter-app to scaffold tsrouter apps.
On this quickstart page
https://tanstack.com/router/latest/docs/framework/react/quick-start
https://tanstack.com/router/latest/docs/framework/solid/quick-start

docs(quickstart): use create-tsrouter-app for scaffolding a tsrouter app

---

packages/react-router-devtools/src/TanStackRouterDevtools.tsx
packages/router-devtools-core/src/TanStackRouterDevtoolsCore.tsx

Closes https://github.com/TanStack/router/issues/3746
With this change, setting on the DevTools the properties:
- panelProps
- closeButtonProps
- toggleButtonProps
Will propagate those values, such as `style` or `class`  correctly to the respective DOM elements.

fix(router-devtools-core): propagate toggleButtonProps properly

---

packages/react-router-devtools/src/TanStackRouterDevtools.tsx

Closes https://github.com/TanStack/router/issues/3723
The hooks rules makes it impossible to have the same conditional logic for the useRouter call as the solid-router-devtools has, so this mutes the warning to avoid flooding the browser console, because the setup here is intentional.

fix(react-router-devtools): remove console warnings from useRouter

---

packages/history/src/index.ts
packages/history/tests/createHashHistory.test.ts

This more cleanly and safely constructs a href with search parameters and prevents incorrectly adding a double slash to the start of the URL that was introduced in #3644.
Fixes #3739
Fixes #3699

fix(history): double `/` being added in hash routing

---

packages/router-core/src/Matches.ts
packages/router-core/src/link.ts
packages/router-core/src/redirect.ts

Hi,
Following up on https://github.com/TanStack/router/discussions/3790 I added some JSDoc on a few uncommented types I encountered in my project
I basically copied the text & default from the documentation except for `hashScrollIntoView` and `viewTransition` where the existing non-JSDoc comments seem good

refactor(router-core): decorate with JSDoc for `NavigateOptionProps`, `ActiveOptions`, `MatchRouteOptions` and `Redirect`

---

docs/start/framework/react/quick-start.md

Fix wrong url for start-counter example

docs(start): fix broken url to the `start-counter` example

---

packages/react-router/src/route.ts
packages/router-core/src/index.ts
packages/router-core/src/route.ts
packages/solid-router/src/route.ts

Similar to #3800 , this use base classes to contain shared methods of the solid/react-router Route in the router-core package.

refactor(router-core): move internals of Route to router-core

---

packages/react-router/src/route.ts

As part of the move to `router-core` in https://github.com/TanStack/router/pull/3803, we accidentally removed the `Symbol` declaration that was being performed in the constructor of the `Route` class. This had a downstream effect on the HMR functionality provided by `@vitejs/plugin-react`.
Fixes #3815

fix(react-router): missing `Symbol` declaration for HMR

---

e2e/react-start/basic-auth/src/components/Auth.tsx
examples/react/start-basic-auth/src/components/Auth.tsx

It should be "Email" instead of "Username"
See:

chore(examples,e2e): incorrect label value for "email"

---

e2e/react-start/clerk-basic/package.json
e2e/react-start/clerk-basic/src/routes/__root.tsx
e2e/react-start/clerk-basic/src/routes/_authed.tsx
e2e/react-start/clerk-basic/src/ssr.tsx
examples/react/start-clerk-basic/package.json
examples/react/start-clerk-basic/src/routes/__root.tsx
examples/react/start-clerk-basic/src/routes/_authed.tsx
examples/react/start-clerk-basic/src/ssr.tsx
pnpm-lock.yaml

This PR updates all `@clerk/tanstack-start` references to use the new `@clerk/tanstack-react-start` package name.
See [release](https://github.com/clerk/javascript/releases/tag/%40clerk%2Ftanstack-react-start%400.12.0)

chore(examples): Use new TanStack React Start + Clerk package name

---

docs/start/framework/react/build-from-scratch.md

There are broken links in the Tanstack Start "Build from Scratch: The Router Configuration" section.
I believe this should goes into Tanstack Router documentation.

fix(docs): Update link for the The Router Configuration: Preloading & Caching

---

docs/start/framework/react/quick-start.md

- initial cloning with degit takes 30s and more
- unnatural url, user/repo/subdir? when shared if you copy and visit the url, results in not found
- creates cache directory in "$HOME/.degit" i.e. unknown to the user (user does cd ~, and wonder can I delete .degit dir?)
- not maintained anymore, degit --help doesn't work either
- [gitpick](https://github.com/nrjdalal/gitpick) takes 2-3 secs, be that initially or any run, no cache dir, always updated to latest repository status
- can use shorter URLs like `TanStack/router/tree/main/examples/react/start-basic`, no need to prepend github.com
- natural URL, you can just copy any URL and paste it from the github repository (can copy any branch or any URL, even files)
- follows exact `git` behaviour, with extension like `-o` for overwrite
- can …

docs(start): switch from `degit` to `gitpick`

---

docs/router/framework/react/routing/file-based-routing.md

The `_pathlessLayout.tsx` should be the same name as the directory `_pathlessLayout` in order to be applied as Layout for `route-a` and `route-b` routes

docs(router): fix `_pathlessLayout` example of file-based routing

---

packages/router-devtools-core/src/FloatingTanStackRouterDevtools.tsx

closes https://github.com/TanStack/router/issues/3897
- #3897
When the devtools are closed, this removes the style attribute, including the lingering padding-bottom property

fix(router-devtools-core): remove floating panel style on close

---

docs/router/framework/react/api/router/RouterType.md

The `.matchRoute` method on the Router type page previously stated it returns a `RouteMatch` object. In reality, it returns only the route match's params.
This update corrects the return type in docs to reflect actual behavior.
Fix #3875

docs(router): correct ReturnType of `Router.matchRoute` to match the runtime output

---

docs/router/framework/react/guide/document-head-management.md

1. **Fix createRootRoute syntax**: Updated all examples in the document head management guide to use the correct `createRootRoute({...})` syntax instead of the incorrect `createRootRoute()({...})` syntax.
2. **Fix HeadContent placement**: The previous commit corrected the code example for Single-Page Applications to properly show the correct syntax for creating a root route with HeadContent.
- The incorrect syntax examples could lead to confusion for developers implementing document head management in their applications
- These fixes ensure consistency throughout the documentation and provide developers with the correct implementation patterns
- Proper documentation helps reduce support requests and improves developer experience
- Fixed 5 instances of incorrect `createRootRoute()({...})` …

Fix HeadContent docs

---

docs/router/framework/react/guide/search-params.md

In the "search params" guide, the usage of the variable `allProductsRoute` has been changed to `Route` in the code-block examples for consistency and clarity.
This makes the examples easier to follow since `Route` is used throughout the rest of the documentation.

docs(router): simplify route variable naming in search params guide

---

packages/react-router/src/Transitioner.tsx
packages/router-core/src/index.ts
packages/router-core/src/scroll-restoration.ts
packages/solid-router/src/Transitioner.tsx

Fixes #3741 
Added hash scroll handling directly in the React `Transitioner` component's `onResolved`, similar to how it's implemented in the Solid version

fix(react-router): restore scroll position onResolved

---

packages/react-router/src/route.ts

Similar to #3821, the React Symbol declaration was missing on the `RootRoute` class.
fixes #3917

fix(react-router): missing Symbol declaration for HMR in root route

---

docs/router/framework/react/guide/authenticated-routes.md

Currently the link points to https://tanstack.com/router/latest/docs/framework/examples/authenticated-routes which is 404.

docs: fix broken example link

---

packages/start-client-core/src/createServerFn.ts

This change hashes the generated filnames for the JSON blobs that used for static server function RPC calls.
So it goes from being
```
/__tsr/staticServerFnCache/app_routes_nav_posts_stub_tsx--loadPostServerFn_createServerFn_handler__-this-is-a-post-slug-.json
```
to
```
/__tsr/staticServerFnCache/00e9f7af882c994097f011e6492f2a30e8754bb0.json
```
This has an added benefit of ensuring that the `sha1` hash names are always the same in character length.

refactor(start-client-core): hash the static filenames

---

packages/react-router/src/Match.tsx

fixes https://github.com/TanStack/router/issues/3680
It seems like `resolvedLocation` does not always point to the latest location state in the ref callback; sometimes it points to the previous location and `onRendered` is not triggered.

fix(react-router): fix issue with scroll restoration

---

packages/router-core/src/redirect.ts

PR #2243 introduced a tighter type for the `TRouter` type parameter in `redirect`, making it not possible to pass a different router than the currently registered one.
This PR brings back the previous behaviour, and allows any `Router` to be passed, with a default of `RegisteredRouter`. `TTo` also needed to be changed as the first parameter became optional. 
First time contributing here, do I need to create an issue for this?

fix(router-core): Accept AnyRouter in `redirect`

---

docs/router/framework/react/guide/deferred-data-loading.md

There is a broken link to SSR page from Deferred Data Loading page
Link:
- AS-IS: https://tanstack.com/docs/framework/react/guide/ssr#streaming-ssr (which is a blank page)
- TO-BE: https://tanstack.com/router/latest/docs/framework/react/guide/ssr#streaming-ssr
Fixed by using relative link like other links in the same document, also referenced [contributing doc](https://github.com/TanStack/router/blob/af455d812f220a6df3d43dbe1610cf0d173ea092/CONTRIBUTING.md)

docs(router): Fix broken link to SSR page from Deferred Data Loading page

---

docs/start/framework/react/server-functions.md

The git link for Start server is incorrect, the correct link would be `react-start-server`, however I think that package isn't very relevant for `h3` methods which this section of docs is about. I think the `start-server-core` package is more relevant, since it has the source code for the h3 methods.

fix(docs): correct start server git link

---

examples/react/start-basic/package.json
examples/react/start-basic/src/routes/api/users.$id.ts
examples/react/start-basic/src/routes/api/users.ts
examples/react/start-basic/src/routes/users.$userId.tsx
examples/react/start-basic/src/routes/users.route.tsx
examples/react/start-basic/src/utils/posts.tsx
pnpm-lock.yaml

Replaces the usage of `redaxios` with the native `fetch` on the Basic Start example.

Replace `redaxios` with native `fetch`

---

docs/start/framework/react/learn-the-basics.md

Fixes the following in the "learn the basics" doc for Tanstack Start:
1. The example snippet for server function mutations is incomplete and does not do what the description says it does.
2. The link to the full mutation docs was a broken, non-relative link.
3. Another link in this doc was also broken and non-relative.
I'm just getting started with Tanstack Start, so my example might not contain best practices--I would like feedback before merging!
Context (from discord):
> Hi, I'm looking at https://tanstack.com/start/latest/docs/framework/react/learn-the-basics, and the example in the "Mutations" section seems to be missing a lot:
> * Missing import: `z`
> * Missing definition/import: `db`
> * Missing definition/import: `users`
> 
> It also doesn't seem to do what the description says: …

fix(docs): Complete server function mutation example and fix broken links.

---

docs/start/framework/react/build-from-scratch.md
docs/start/framework/solid/build-from-scratch.md

Since JSON doesn't allow for trailing commas.

docs(start): remove trailing commas from "build-from-scratch"

---

examples/react/view-transitions/src/main.tsx
packages/router-core/src/router.ts

Context: https://github.com/TanStack/router/discussions/4027
Changes the ViewTransitionOptions["types"] to also accept a function. This enables automatically applying different animations (for example sliding left or right) based on history navigation. When navigating via `history.back()/forward()`, it’s very common to want a "slide-left" vs "slide-right" effect based on direction.
This technically also works for `Link`s but it's not as useful there since the prop can already be dynamic. This is mostly for navigations that are triggered via other sources than links.

feat(router-core): allow dynamic `ViewTransition` types

---

packages/router-core/src/router.ts
packages/solid-router/src/Transitioner.tsx

also sets match status to 'succes' only after lazy loaded components were loaded
fixes #3556
fixes #2183
fixes #2722

fix: pending component handling for initial load

---

packages/react-start-config/src/index.ts
packages/react-start-config/src/schema.ts
packages/solid-start-config/src/index.ts
packages/solid-start-config/src/schema.ts
packages/start-config/src/index.ts
packages/start-config/src/schema.ts

Ref: https://nitro.build/deploy#zero-config-providers
Nitro will automatically fallback to `node-server` if it doesn't recognize environment of one of supported zero configuration deploy targets https://nitro.build/deploy#default-output.
Note https://github.com/nksaraf/vinxi/pull/325 was similar change done some time ago in Vinxi to allow for zero-configuration

feat: allow use of nitro zero conf

---

docs/start/framework/react/api-routes.md

Looks like the hint on how to change the default API routes prefix is wrong, please see this discussion: https://github.com/TanStack/router/discussions/4060

docs(start): fix key on changing the base path for API routes

---

packages/react-router-devtools/src/TanStackRouterDevtoolsPanel.tsx

PR https://github.com/TanStack/router/pull/3770 removed the warning for the full Devtools component, but left if for the Panel one. This PR removes the warning to align the two devtools implementations.

fix(react-router-devtools): remove useRouter warning for panel

---

docs/start/framework/react/hosting.md

There were instances of 'your' written as 'you'.

Fixed typos

---

docs/router/framework/react/routing/routing-concepts.md

This PR imroves on the documentation on the routing concepts of the router by giving an explanation and example on how to exclude files and folders from the routing logic
- Added an extra example and explanation convention that highlights the concepts to exclude files and folders from being generated as routes
This enables developes to be aware of the feature included as a core concept to exclude files and folders from the routing logic by referencing the documentation
---
I've verified that these changes:

docs(router): walkthrough on using the ignore prefix for component colocation in the routing-concepts guide

---

docs/start/config.json
docs/start/framework/react/reading-writing-file.md

Adds a tutorial showing how to build a full-stack DevJokes app with TanStack Start. Users learn to create server functions for reading and writing to files, build React components, and implement data fetching with TanStack Router.
- Server functions with `createServerFn`
- File-based data storage with Node.js `fs`
- Form handling and data validation
- Data refreshing with `router.invalidate()`
- Complete UI with Tailwind CSS
https://youtu.be/zd0rtKbtlgU
Complete code available at: https://github.com/shrutikapoor08/devjokes

Adding Tutorial for Reading and Writing a File

---

packages/directive-functions-plugin/tests/compiler.test.ts

Resolves https://github.com/TanStack/router/pull/4080#discussion_r2073871283

test(directive-functions-plugin): add yields to generators

---

docs/router/framework/react/routing/route-trees.md

Updates the wording to be more consise, limits the amount of emphasis, as well as links to file-based routing.

docs(router): update route-trees.md wording

---

packages/react-router/src/link.tsx
packages/react-router/src/route.tsx
packages/react-router/tests/routeApi.test-d.tsx
packages/solid-router/src/link.tsx
packages/solid-router/src/route.tsx
packages/solid-router/tests/routeApi.test-d.tsx

This allows `Route.Link` and `routeApi.Link` bindings instead of manual `from`.
We never used to be able to do this due to circular issues but it seems this is no longer an issue since all the changes to the types

feat: add bindings for `Route.Link` and `routeApi.Link`

---

docs/router/framework/react/guide/search-params.md

Fix heading level of the Effect/Schema Adapters section to have the right level relational level in the table of contents.

doc: Update search-params.md Effect/Schema Adapter heading

---

e2e/react-start/basic/package.json
e2e/solid-start/basic-tsr-config/package.json
e2e/solid-start/basic/package.json
e2e/solid-start/scroll-restoration/package.json
e2e/solid-start/server-functions/package.json
e2e/solid-start/website/package.json
packages/directive-functions-plugin/package.json
packages/react-start-plugin/package.json
packages/react-start/package.json
packages/server-functions-plugin/package.json
packages/solid-start-plugin/package.json
packages/solid-start/package.json
packages/start-plugin-core/package.json
packages/start-server-functions-fetcher/package.json
packages/start-server-functions-server/package.json
pnpm-lock.yaml

Currently, none of the packages (i.e `packages/*`) need `vite` bundled as a `dependency`. So its been moved to the `devDependencies` and had the version opened using `"peerDependencies": { "vite": ">=6.0.0" }`.
Additionally, `vite` has been added as a `dependency` to the Start end-to-end sandboxes.
In a later PR, `vite` will need to be added to all the TanStack Start examples (i.e. `examples/**/start-*`).

fix: declare `vite` as a `peerDependency`

---

packages/router-generator/src/generator.ts

When using `verboseFileRoutes`, the `router-generator` shouldn't try to includes routes where `export const Route` isn't present in the body of the source file.

fix(router-generator): exit conditions when using `verboseFileRoutes`

---

packages/start-server-core/src/createStartHandler.ts

Reuse the utility functions from `route-core` for the trimming of paths and joining them.

refactor(start-server-core): use utility functions from router-core

---

docs/start/framework/react/server-functions.md

I asked about stable url's for server functions and was informed that this feature is no longer planned. This PR updates the docs to reflect this.

docs(start): Remove unplanned feature from docs

---

docs/router/framework/react/guide/not-found-errors.md

This PR is to improve the not found error docs slightly, based on confusion about how they bubble up, as reflected in this thread: https://discord.com/channels/719702312431386674/1023930177224462388/threads/1303321797537828864

chore(docs): specify that not found errors are handled by the nearest parent when called within `loader`

---

e2e/react-start/basic/src/server.ts
e2e/solid-start/basic/src/server.ts
packages/react-start-plugin/src/index.ts
packages/solid-start-plugin/src/index.ts

This is a patch following https://github.com/TanStack/router/issues/4138 and https://github.com/TanStack/router/pull/4172. The virtual path should be kept intact when there isn't a custom `server.ts` entry file. Excluding the root path resolves the following error:
```
Error: Cannot find module 'D:~startdefault-server-entry' imported from '/~start/server-entry.tsx'
```
On Windows, `path.resolve(...)` returns a path with backslashes, e.g., D:\\router\\examples\\react\\start-basic\\src\\server.ts. Injecting it directly into an import statement leads to the following error. I replaced all backslashes with forward slashes and got it working on start-basic.
```
Error: Cannot find module 'D:routerexamplesreactstart-basic_srcserver.ts' imported from '/~start/server-entry.tsx'
```

fix: resolve custom `server` entry path on windows fs

---

packages/start-server-core/src/createStartHandler.ts

Adds in the same "interceptor" functionality which `undici` previously fulfilled.

feat(start-server-core): resolve relative requests to the same origin

---

packages/start-plugin-core/src/nitro/nitro-plugin.ts

Pre-rendering should be enabled, if any of the `config.pages` specify that it should be (i.e `config.pages = [{ path: '/posts', prerender: { enabled: true } }]`. However, if the user has explicitly set `config.prerender.enabled = false`, then even `config.pages` will NOT override the global `config.prerender.enabled` setting.

fix(start-plugin-core): enable pre-rendering with just `pages`

---

packages/react-router/tests/Scripts.test.tsx
packages/react-router/tests/route.test.tsx
packages/router-core/src/route.ts
packages/router-core/src/router.ts

1. execute head also when loader throws
2. execute head also when loader was not executed, but only after parent's beforeLoad ran
fixes #3657

fix: head execution

---

packages/router-devtools-core/src/TanStackRouterDevtoolsCore.tsx

containerElement prop was not passed into the DevTools instance to be handled.  containerElement allows use to use an alternate html tag to 'footer' which trips up some a11y tests

fix(router-devtools-core) adds missing containerElement prop support for TanStackRouterDevtoolsCore

---

docs/start/framework/react/databases.md

The markdown list wasn't shown properly and I noticed the signup link was broken
Before
After

docs: fix neon bullet points and url

---

packages/router-plugin/src/core/config.ts
packages/router-plugin/src/index.ts
packages/start-plugin-core/src/schema.ts

At the moment, no changes made by the user regarding these options will change what happens.
This change will hide these options from users.

refactor(start-plugin-core): omit `autoCodeSplitting` configuration option in `tsr`

---

docs/router/framework/react/api/router/RouteOptionsType.md

document migration path explicitly for https://github.com/TanStack/router/pull/1826

docs(react-router): document migration path for `parseParams` and `stringifyParams`

---

packages/react-start-server/vite.config.ts
packages/server-functions-plugin/src/index.ts
packages/solid-start-server/vite.config.ts
packages/start-plugin-core/src/index.ts
packages/start-plugin-core/src/plugin.ts
packages/start-plugin-core/src/routesManifestPlugin.ts
packages/start-plugin-core/src/start-server-routes-plugin/plugin.ts
packages/start-plugin-core/src/utils.ts
packages/start-server-core/src/createStartHandler.ts
packages/start-server-core/src/router-manifest.ts
packages/start-server-core/src/server-functions-handler.ts
packages/start-server-core/src/tanstack-start.d.ts
packages/start-server-core/vite.config.ts

Renames the following virtual modules as such to have them be both consistent and more easily readable should there be an error when importing them.
| Before | After |
|--------|--------|
| `tanstack:server-fn-manifest` | `tanstack-start-server-fn-manifest:v` |
| `tanstack:start-manifest` | `tanstack-start-router-manifest:v` |
| `tanstack:server-rotues` | `tanstack-start-server-routes-manifest:v` | 
Additionally, the [Rollup convention for resolving virtual modules](https://vite.dev/guide/api-plugin#virtual-modules-convention) is being applied to these modules.

refactor: consistent virtual module naming and resolve using Rollup conventions

---

packages/server-functions-plugin/README.md
packages/server-functions-plugin/src/index.ts
packages/start-plugin-core/src/plugin.ts

As part of the devinxi changes, the following hard-coded output path of the server functions manifest file was changed.
```diff
- const manifestFilename = 'node_modules/.tanstack-start/server-functions-manifest.json'
+ const manifestFilename = '.tanstack-start/build/server/server-functions-manifest.json'
```
This would have had breaking changes in the user DX for downstream frameworks building upon the `@tanstack/server-functions-plugin` package - (i.e. SolidStart).
---
This change makes the manifest file for `server-functions-plugin` configurable, with it being defaulted to  the old value of `node_modules/.tanstack-start/server-functions-manifest.json`.
It also sets the default for TanStack Start to `.tanstack-start/build/server/server-functions-manifest.json`.

feat(server-functions-plugin): make the manifest output path configurable

---

packages/start-plugin-core/src/plugin.ts

This is related to https://github.com/TanStack/router/pull/4179. If there isn't `@fs` in the client entry path when a custom client.tsx file exists, the browser loads the script via file:///D:/router/examples/react/start-basic/src/client.tsx, which will fail to load. Prepending `/@fs/` results in the correct request URL: http://localhost:3000/@fs/D:/router/examples/react/start-basic/src/client.tsx.
A `/` is also needed after `/@fs`, otherwise the request URL becomes http://localhost:3000/@fsD:/router/examples/react/start-basic/src/client.tsx, leading to 404.
Since `getClientEntryPath(...)` is also used at [plugin.ts#L85](https://github.com/TanStack/router/blob/alpha/packages/start-plugin-core/src/plugin.ts#L85), I am unsure of the impact of `@fs` there. Nevertheless, I didn't find issues …

fix: prepend `/@fs` when a custom client entry is detected

---

packages/router-core/src/utils.ts
packages/router-core/tests/utils.test.ts

Opening this PR for discussion, I'm very open to scope changes.
This PR tackles two problems with `defaultStructuralSharing: true`:
1. symbol properties are not taken into account for "object equality" and are not copied over when creating a new copy
2. non-enumerable properties are not taken into account for "object equality" and are not copied over when creating a new copy
Point 1. actually is causing some of our users a headache, see https://github.com/apollographql/apollo-client/issues/12619 and https://community.apollographql.com/t/preloadquery-with-tanstack-router-loader/9100 .
Users expect that they're able to pass an object with symbol properties over from a loader into components, but when having `defaultStructuralSharing` enabled, from the second object that is passed over, it …

handle Symbol properties and non-enumerable properties in `replaceEqualDeep`

---

packages/start-plugin-core/src/plugin.ts

Fixes #4243
There's a subtle difference between the [`routerImportPath`](https://github.com/TanStack/router/pull/4238/files#diff-a6e4ac58c8c6c3471a9b07a5b161709f0f70e9a761b1528d0cb7b88fdc4d15b3L48) before and [`routerFilepath`](https://github.com/TanStack/router/pull/4238/files#diff-bdd2c7efd081403fb4f53a6d4b441db0904b3e860ceff5dbd7d9721e4e0ce89aR240) after #4238. The former uses `JSON.stringify()`, which generates a path with double backslashes, while the latter uses the return value from `path.resolve()` directly, which uses a single backslash as the separator. This is similar to #4180, but for the router. Using `normalizePath()` to turn all backslashes to forward slashes fixes the import error caused by the malformed path.

fix: normalize router filepath

---

packages/start-server-core/src/createStartHandler.ts
packages/start-server-core/src/router-manifest.ts
packages/start-server-core/src/server-functions-handler.ts

otherwise other packages that import start (e.g. clerk) for which noExternal is not set will not properly transform those virtual modules during dev

fix: dynamically import virtual modules

---

packages/react-start-plugin/src/index.ts
packages/solid-start-plugin/src/index.ts
packages/start-plugin-core/src/nitro/nitro-plugin.ts
packages/start-plugin-core/src/plugin.ts
packages/start-server-core/src/server-functions-handler.ts

- Brings more of the defaults from Vinxi which limits what `createNitro` does.
- Renamed the functions and arguments for getting the entry/handlers for the "server root", "server entry", and "client entry".
- Assigns the type for the `serverFnManifest` import in-place, instead of casting later on.

refactor: rename internal functions and limit nitro defaults

---

examples/react/start-bare/src/routes/__root.tsx
examples/react/start-bare/src/routes/about.tsx
examples/react/start-bare/src/routes/index.tsx
packages/start-plugin-core/src/routesManifestPlugin.ts

This PR resolves an issue where not all CSS files needed to render a route were included in the SSR response. The root cause was that only CSS directly imported by the main route was being requested, leaving out styles from nested components.
The fix ensures CSS is now recursively imported, so all necessary styles—regardless of where they’re required—are properly included.
Before
After
I also updated the start bare example importing the counter compontent from the about page to show the error and the fix, and ensure this is not a problem in the future.
This is my first PR in this repo, im not sure if this breaks anything else but for my testing this works as expected and solves the issue!

fix(alpha): Recursively import CSS assets

---

docs/router/framework/react/routing/file-based-routing.md

The official docs do not currently demonstrate that naming a file as `route.tsx` will automatically have it treated as a layout route for that route.
i.e. 
```
| ʦ `posts.tsx`           | `/posts`                  | `<Root><Posts>`                   |
| 📂 `posts`              |                           |                                   |
| ┄ ʦ `$postId.tsx`       | `/posts/$postId`          | `<Root><Posts><Post>`             |
```
is also the same as 
```
| 📂 `posts`              |                           |                                   |
| ʦ `route.tsx`           | `/posts`                  | `<Root><Posts>`                   |
| ┄ ʦ `$postId.tsx`       | `/posts/$postId`          | `<Root><Posts><Post>`             |
```
This PR adds in a new route in the examples of the …

docs(router): add `route.tsx` in directory vs flat routing guide

---

packages/start-plugin-core/src/nitro/nitro-plugin.ts

In development, the `loadEnv` utility function is being used to load up all the environment variables into `process.env`.

feat(start-plugin-core): load all environment variables for dev

---

docs/router/framework/react/api/router/RouteOptionsType.md

The loader section of the RouteOptions Type docs page currently shows opts properties that have been removed. This PR cleans those up and updates the list to reflect what is actually available. 
**Removed:**
- `search`
- `buildLocation`
**Changed:**
- Sorted alpha to match the [loader params page](https://tanstack.com/router/latest/docs/framework/react/guide/data-loading#loader-parameters)

docs: Update RouteOptionsType doc to reflect correct Loader opts

---

packages/router-devtools-core/src/TanStackRouterDevtoolsCore.tsx

I noticed devtools not rendering correctly after a recent update.  This fix wraps the DevTools component in the shadowdom context.  
Fixes: #4064

fix: Fix devtools when using shadowdom

---

e2e/react-start/basic/src/routeTree.gen.ts
e2e/react-start/basic/src/routes/foo/$bar/$qux/_here.tsx
e2e/react-start/basic/src/routes/foo/$bar/$qux/_here/index.tsx
packages/start-plugin-core/src/start-server-routes-plugin/plugin.ts

When handling file-based route with the given layout
```
src/routes/foo
└── $bar
└── $qux
├── _here
│   └── index.tsx
└── _here.tsx
```
The current implementation of `start-server-routes-plugin` will throw an error when generating routes
```
Error: EISDIR: illegal operation on a directory, read
at Object.readFileSync (node:fs:442:20)
at handleNode (file://router/packages/start-plugin-core/dist/esm/start-server-routes-plugin/plugin.js:164:42)
at handleNode (file://router/packages/start-plugin-core/dist/esm/start-server-routes-plugin/plugin.js:195:15)
at generator (file://router/packages/start-plugin-core/dist/esm/start-server-routes-plugin/plugin.js:216:11)
at async generate (file://router/packages/start-plugin-core/dist/esm/start-server-routes-plugin/plugin.js:24:7)
at async …
```

fix(start-plugin-core): add a defensive check for node.fullPath

---

docs/router/framework/react/guide/scroll-restoration.md
packages/router-core/src/router.ts
packages/router-core/src/scroll-restoration.ts

[As discussed on Discord](https://discord.com/channels/719702312431386674/1377997863396708362/1378007230208676031), this PR adds the ability to pass functions that return HTML elements to `routerOptions.scrollToTopSelectors` in the case where `document.querySelector(selector)` doesn't cut it and we need to use more complex selectors (such as pointing to an element in a Shadow DOM)

fix: scroll to top selectors function

---

docs/router/framework/react/guide/data-mutations.md

I changed the route path to have the correct path param used on the component. Also changed the component name so it makes sense.
Before:
```tsx
const routeApi = getRouteApi('/posts/$postId/edit')
function EditPost() {
const { roomId } = routeApi.useParams()
const sendMessageMutation = useCoolMutation({
fn: sendMessage,
// Clear the mutation state when the roomId changes
// including any submission state
key: ['sendMessage', roomId],
})
// Fire off a bunch of messages
const test = () => {
sendMessageMutation.mutate({ roomId, message: 'Hello!' })
sendMessageMutation.mutate({ roomId, message: 'How are you?' })
sendMessageMutation.mutate({ roomId, message: 'Goodbye!' })
}
return (
<>
{sendMessageMutation.submissions.map((submission) => {
return (
<div>
<div>{submission.status}</div> …
```

docs(router): Use correct path param name on data mutation docs

---

packages/start-plugin-core/src/plugin.ts

this fixes the issue where a third-party dependency tries to access the router from react via the router context, but vite bundles this dependency with its own version of router and hence the router context is null.
the following error occurs then
```
useRouter must be used inside a <RouterProvider> component!
```
by only adding start packages to `noExternal` we prevent this mismatch

fix: don't add all @tanstack packages to noExternal

---

packages/react-start-client/src/index.tsx
packages/solid-start-client/src/index.tsx
packages/start-client-core/src/index.tsx

I hit a similar issue to #4001 (ts(2742)) but on pnpm, which requires exporting the types all the way to the module that gets directly imported by the application according to https://github.com/microsoft/TypeScript/issues/47663#issuecomment-1519138189.
This fix resolves this issue.

fix: export OptionalFetcher and RequiredFetcher types

---

packages/start-plugin-core/src/start-routes-manifest-plugin/plugin.ts

This wasn't working correctly on Windows.
In `filesByRouteFilePath`, the paths are formatted using `/`, but `path.join` on Windows uses `\`, which caused a mismatch. As a result, asset preloading was broken. This change fixes that issue.
That said, there might still be a problem. I added a log to check for missing files in `filesByRouteFilePath`, and I'm still seeing `not found src\routes\__root.tsx`. I don't see a corresponding key like `__root.tsx` in `filesByRouteFilePath`. However, CSS and JS files are now preloading correctly on Windows.

fix: Preload assets on windows

---

packages/react-router/package.json
scripts/llms-generate.mjs

Turns out that `vibe-rules` doesn't support ESM, only CJS. So trying again.

chore: fixing vibe-rules generation to support CJS exports as well

---

packages/router-plugin/src/core/router-generator-plugin.ts

hi,
init of config and generator was changed in 25c1369726f8550f12a3f13556e42d9cd615e7eb part of #4337.
The webpack plugin needs a fix to incorporate init changes.
Use the same init method as other plugins for webpack.
Thanks,
Valentin

fix(router-plugin): initialise generator within webpack plugin

---

packages/react-router-devtools/package.json
packages/react-router-devtools/src/TanStackRouterDevtools.tsx
pnpm-lock.yaml

We don't need to depend on solid-js to import JSX types in react-router-devtools package

fix: remove solid-js dependency from react-router-devtools

---

packages/router-generator/src/filesystem/physical/getRouteNodes.ts
packages/router-generator/src/filesystem/virtual/getRouteNodes.ts
packages/router-generator/src/generator.ts
packages/router-generator/src/types.ts
packages/router-plugin/src/core/route-autoimport-plugin.ts
packages/router-plugin/src/core/router-code-splitter-plugin.ts
packages/router-plugin/src/core/router-composed-plugin.ts
packages/router-plugin/src/core/router-generator-plugin.ts
packages/router-plugin/src/core/router-hmr-plugin.ts
packages/router-plugin/src/core/utils.ts
packages/router-plugin/src/global.d.ts

fixes #4331
also switched over to plugin hook filters, see https://rolldown.rs/guide/plugin-development#plugin-hook-filters

fix: router-plugins correctly handle virtual file routes regardless of their location

---

docs/start/framework/react/migrate-from-next-js.md

the server function and server route links were not working (missing .)

fix broken link in migrate-from-next-js.md

---

packages/start-plugin-core/src/nitro-plugin/prerender.ts

Fixes #4416
On Windows, dynamic `import()` in Node.js confuses the drive letter with the protocol. Common drive letters, such as C and D, which are not part of the [supported schemes](https://nodejs.org/api/errors.html#err_unsupported_esm_url_scheme), cause the build to fail.

fix: always include the file scheme for the server entrypoint

---

packages/router-generator/src/filesystem/physical/getRouteNodes.ts
packages/router-generator/src/filesystem/virtual/getRouteNodes.ts

Fixes https://github.com/TanStack/router/issues/4428
`path.posix.join` is not sufficient when the first argument is a path containing backslashes, for instance, joining `D:\\path` with `filename` results in `D:\\path/filename`.
**start-basic**
Before:
```
.tanstack/start/build/client-dist/.vite/manifest.json        0.38 kB │ gzip:  0.20 kB
.tanstack/start/build/client-dist/assets/app-DACsPwZv.css    7.33 kB │ gzip:  2.10 kB
.tanstack/start/build/client-dist/assets/main-C896_Nb9.js  283.11 kB │ gzip: 90.49 kB
```
After:
```
.tanstack/start/build/client-dist/.vite/manifest.json                       6.80 kB │ gzip:  0.85 kB
.tanstack/start/build/client-dist/assets/app-DACsPwZv.css                   7.33 kB │ gzip:  2.10 kB
.tanstack/start/build/client-dist/assets/posts._postId-zPBcgaYs.js …
```

fix: replace backslashes in full paths when generating route nodes

---

packages/router-core/src/router.ts

fix: only re-execute beforeLoad if previous run failed

---

e2e/react-router/basic-file-based/src/routeTree.gen.ts
e2e/react-router/basic-file-based/src/routes/search-params/default.tsx
e2e/react-router/basic-file-based/src/routes/search-params/index.tsx
e2e/react-router/basic-file-based/src/routes/search-params/route.tsx
e2e/react-router/basic-file-based/tests/search-params.spec.ts
e2e/react-start/basic/src/routeTree.gen.ts
e2e/react-start/basic/src/routes/search-params/default.tsx
e2e/react-start/basic/src/routes/search-params/index.tsx
e2e/react-start/basic/src/routes/search-params/loader-throws-redirect.tsx
e2e/react-start/basic/src/routes/search-params/route.tsx
e2e/react-start/basic/tests/search-params.spec.ts
e2e/solid-router/basic-file-based/src/routeTree.gen.ts
e2e/solid-router/basic-file-based/src/routes/search-params/default.tsx
e2e/solid-router/basic-file-based/src/routes/search-params/index.tsx
e2e/solid-router/basic-file-based/src/routes/search-params/route.tsx
e2e/solid-router/basic-file-based/tests/search-params.spec.ts
e2e/solid-start/basic/src/routeTree.gen.ts
e2e/solid-start/basic/src/routes/search-params/default.tsx
e2e/solid-start/basic/src/routes/search-params/index.tsx
e2e/solid-start/basic/src/routes/search-params/loader-throws-redirect.tsx
e2e/solid-start/basic/src/routes/search-params/route.tsx
e2e/solid-start/basic/tests/search-params.spec.ts
packages/router-core/src/redirect.ts
packages/router-core/src/router.ts

before, this was handled client-side
also added e2e tests for redirection in start and regression test for #3578

fix: if validate search rewrites search params, issue a server-side redirect

---

packages/router-plugin/src/core/router-generator-plugin.ts

fix: correctly pass 'create' event to generator for rspack/webpack

---

examples/react/start-bare/package.json
examples/react/start-basic-auth/package.json
examples/react/start-basic-react-query/package.json
examples/react/start-basic-rsc/package.json
examples/react/start-basic-static/package.json
examples/react/start-basic/package.json
examples/react/start-clerk-basic/package.json
examples/react/start-convex-trellaux/package.json
examples/react/start-counter/package.json
examples/react/start-material-ui/package.json
examples/react/start-supabase-basic/package.json
examples/react/start-tailwind-v4/package.json
examples/react/start-trellaux/package.json
examples/react/start-workos/package.json
examples/solid/start-bare/package.json
examples/solid/start-basic-static/package.json
examples/solid/start-basic/package.json
pnpm-lock.yaml

The `Vite` dependency is missing in quite a few start examples after the migration from `Vinxi`. 
This PR, 
1) Adds the latest stable version of vite to examples where it was missing.
2) moves it from a `dependency -> devDependency` in cases where it existed.
3) Fixed alphabetical order of vite dependency in one case.

Added missing `Vite` dependency to Start examples

---

docs/start/framework/react/middleware.md

The example "[Providing context to the next middleware via next](https://tanstack.com/start/latest/docs/framework/react/middleware#providing-context-to-the-next-middleware-via-next)" was missing the middleware method chaining to provide the first middleware context to the second one

docs: added missing middleware method chaining in context example

---

docs/router/framework/react/guide/document-head-management.md

This is important in the case you are doing SPA's. If you have the title tag set in the `index.html` file from Vite the component won't work as intended.

docs: Update head management instructions for SPA's

---

docs/router/eslint/create-route-property-order.md
docs/router/framework/react/api/router/createFileRouteFunction.md
docs/router/framework/react/api/router/retainSearchParamsFunction.md
docs/router/framework/react/api/router/stripSearchParamsFunction.md
docs/router/framework/react/decisions-on-dx.md
docs/router/framework/react/guide/external-data-loading.md
docs/router/framework/react/guide/router-context.md
docs/router/framework/react/migrate-from-react-location.md
docs/router/framework/react/routing/routing-concepts.md
docs/start/framework/react/migrate-from-next-js.md
docs/start/framework/react/server-routes.md
docs/start/framework/solid/build-from-scratch.md

Some of the documentation was missing the path parameter for `createFileRoute`, which is required by default.
This PR adds those paths back, and tries to make it as relevant to the surrounding context as possible.
Fixes #4372

docs: use correct syntax for createFileRoute

---

examples/react/start-supabase-basic/package.json
examples/react/start-supabase-basic/src/components/NotFound.tsx
examples/react/start-supabase-basic/src/hooks/useMutation.ts
examples/react/start-supabase-basic/src/utils/supabase.ts

- reduce use of any
- remove unnecessary @ts-ignore
- sort dependencies in package.json

examples: improve code quality of start-supabase-basic

---

packages/start-plugin-core/src/start-manifest-plugin/plugin.ts

The entry JS file is the only one using `path.join` instead of `joinURL` and that breaks if we're passing URLs (instead of paths like `/`) in Vite as `base`.

fix: use joinURL for entry routes in manifests

---

docs/start/config.json
docs/start/framework/react/tailwind-integration.md
docs/start/framework/solid/tailwind-integration.md

This PR adds a documentation page for **TanStack Start React and Solid** to set up Tailwind CSS (both v4 and v3)
As TanStack Start now uses Vite, setting up Tailwind has become easier but there's lack of documentation in many places **and there's a lot of outdated docs on many other sites**. Hence, adding a page for tailwind right here on the Start docs seems to be a better idea in my opinion.
Let me know if any changes are required

docs(guide): integrate tailwind

---

docs/router/framework/react/guide/document-head-management.md
e2e/react-start/basic/src/routes/__root.tsx
e2e/solid-start/basic/src/routes/__root.tsx
packages/react-router/src/HeadContent.tsx
packages/react-router/src/Matches.tsx
packages/react-router/tests/route.test.tsx
packages/router-core/src/Matches.ts
packages/router-core/src/route.ts
packages/router-core/src/router.ts
packages/router-core/src/ssr/ssr-client.ts
packages/solid-router/src/HeadContent.tsx
packages/solid-router/src/Matches.tsx
packages/solid-router/tests/route.test.tsx

Currently Route HeadContent don't have support to inline style tags.
After a contribution proposition made by @schiller-manuel in the Discord Group I have decided to implement this.
I also have used this in the basic example for react-start and solid-start and added style and style w/loader test cases to both modules.

feat: Add style to HeadContent

---

packages/router-core/src/path.ts
packages/router-core/tests/path.test.ts

fix: trim undefined from splat routes with no param

---

docs/router/framework/react/installation.md

Taking into consideration that "vibe coding" has a specific meaning, for some people even a negative one, I think the way this section is currently written does it a disservice. 
So I switched the "vibe coding" description to refer to "LLM assistance", because that's what this is, in essence: LLM assistance, whether you are vibe coding or not.

docs: improve wording for LLM assistance support in installation.md

---

e2e/react-start/custom-basepath/src/routeTree.gen.ts
e2e/react-start/custom-basepath/src/routes/logout.tsx
e2e/react-start/custom-basepath/tests/navigation.spec.ts
packages/start-server-functions-server/src/index.ts

Hi! This PR fixes a bug where server function urls are incorrect when the app uses a basePath.
The `createServerRpc` function (on the server) was creating URLs without the base path. However, the `createClientRpc`
function (on the client) was including it.
https://github.com/TanStack/router/blob/b9f88c5426f3221ef5b43b11df35f8ba7d61042c/packages/start-server-functions-server/src/index.ts#L18
https://github.com/TanStack/router/blob/b9f88c5426f3221ef5b43b11df35f8ba7d61042c/packages/start-server-functions-client/src/index.ts#L9-L12
For example, with a base path of '/app':
- Server URL: /_serverFn/<function_id>
- Client URL: /app/_serverFn/<function_id>
`<form action={loginFn.url} method="POST">`
hydration error:
```
<LoginPage>
<div>
<h1>
<form
+ …
```

fix(start-server-functions-server): add base path to the RPC URL

---

docs/start/framework/react/overview.md

There's absolutely no reason not to use TanStack Start for purely static sites - it works great, and it means that if you then want to transition a codebase to being dynamically SSR, it requires zero work!

docs: remove somewhat incorrect statement from docs

---

docs/start/framework/react/static-prerendering.md

It's a shame that you can't add docblocks to the source schema, but they get removed by the time it gets to a compiled `.d.ts`.

chore: Document static prerendering options

---

docs/router/framework/react/migrate-from-react-location.md

The link at for tsr.config.json found [in this section](https://tanstack.com/router/latest/docs/framework/react/migrate-from-react-location#differences-between-react-location-and-tanstack-router) points to [this page about file routing styles in the docs](https://tanstack.com/router/latest/docs/framework/react/routing/file-based-routing#options)
That doesn't seem right, when the `tsr.config.json` options are [found here](https://tanstack.com/router/latest/docs/api/file-based-routing)
I've followed the docs in the `tanstack.com` page and checked this link works as expected 😌

docs: Update tsr.config.json options link

---

packages/react-start-client/src/useServerFn.ts

Previously, `react-start-client`'s `useServerFn` would return a new handler function on every render. The handler is now wrapped in `useCallback`.
Returning a new handler function can lead to excessive re-renders. Developers usually expect hooks like this to return a stable value, so the behavior is surprising.
[Discussion in discord](https://discord.com/channels/719702312431386674/1393921652798001213/1393986769061675108) confirms we don't need to make an equivalent update to the solid client.
My first PR here, so I'm not sure if I followed conventions properly -- not sure if I need to make an issue to close here, or if this warrants an e2e or something. Just let me know :)

fix(react-start-client): useServerFn returns a stable reference

---

packages/react-router/src/Matches.tsx
packages/react-router/src/Transitioner.tsx
packages/solid-router/package.json
packages/solid-router/src/Matches.tsx
packages/solid-router/src/Transitioner.tsx
packages/solid-router/tests/server/Transitioner.test.tsx
packages/solid-router/vite.config.ts

This is exploration of the comment I posted on https://github.com/TanStack/router/pull/4574#issuecomment-3038862345.
Using `Solid.createRenderEffect` in SSR will execute the effects after the render takes place. To prevent server from doing meaningless work, we can use the `useLayoutEffect` utility function, which will make the server use `Solid.createEffect` instead, preventing such effects from being ran on server. Client side there are no differences as `Solid.createRenderEffect` is still used. This is closer to how it works in React version today.
To properly test this, we need true SSR with `environment: 'node'` and  `solidPlugin({ ssr: true })` in Vite, because:
1) `jsdom` environment provides `window`, which causes wrong branch in `useLayoutEffect` to be chosen. This is fixable by …

fix(solid-router): prevent client effects running on server

---

packages/react-router/tests/link.test.tsx
packages/solid-router/tests/link.test.tsx

This PR adds a test that would fail without https://github.com/TanStack/router/pull/4668
It doesn't test performance, but it does ensure `useIntersectionObserver` doesn't re-create an `IntersectionObserver` on every re-render. This already tests a lot of the memoization.
Dependency chain:
```
doPreload > preloadViewportIoCallback > useIntersectionObserver > useEffect
```

test(react-router) link: add re-render test for preload='viewport' IntersectionObserver

---

packages/react-router/src/link.tsx
packages/react-router/tests/link.test-d.tsx

Fixes #4673
I a bit simplified the `UseLinkReactProps` to make more use of typing from React (and this simplification just fixes the bug)
Also added a test to check that the bug is no longer reproduced

fix(react-router): preserve ref type in createLink with required interface properties

---

packages/react-router/tests/optional-path-params.test.tsx
packages/router-core/src/path.ts

otherwise matches might end up with non-unique match ids and thus rendering will turn into an endless loop
fixes #4715

fix: ensure unique match id when optional parameter is not present

---

e2e/react-start/server-functions/src/routeTree.gen.ts
e2e/react-start/server-functions/src/router.tsx
e2e/react-start/server-functions/src/routes/__root.tsx
e2e/react-start/server-functions/src/routes/index.tsx
e2e/react-start/server-functions/src/routes/middleware/client-middleware-router.tsx
e2e/react-start/server-functions/src/routes/middleware/index.tsx
e2e/react-start/server-functions/tests/server-functions.spec.ts
labeler-config.yml
package.json
packages/react-start-client/package.json
packages/router-core/src/global.ts
packages/router-core/src/index.ts
packages/router-core/src/router.ts
packages/solid-start-client/package.json
packages/start-client-core/src/createIsomorphicFn.ts
packages/start-client-core/src/createMiddleware.ts
packages/start-client-core/src/createServerFn.ts
packages/start-server-core/package.json
packages/start-server-core/src/createStartHandler.ts
packages/start-server-functions-fetcher/src/index.ts
packages/start-storage-context/README.md
packages/start-storage-context/eslint.config.js
packages/start-storage-context/package.json
packages/start-storage-context/src/async-local-storage.ts
packages/start-storage-context/src/index.tsx
packages/start-storage-context/tsconfig.json
packages/start-storage-context/vite.config.ts
pnpm-lock.yaml
scripts/publish.js

this adds a new package `@tanstack/start-storage-context` to break up a circular dependency
between start-client-core and start-server-core

feat: pass in router instance in client function middleware

---

packages/router-core/src/router.ts

We can improve perf of this function *that gets called a lot* by not grouping the entire string, and only removing the trailing slash.
The entire string is returned by `.replace()`, so we don't ned the group
```
> "/foo/bar/".replace(/\/$/, '')
'/foo/bar'
```
Doing so, we get ~6x performance out of it.
```
✓  @tanstack/router-core  tests/other.bench.ts > comparePaths 2183ms
name                       hz     min     max    mean     p75     p99    p995    p999     rme  samples
· oldComparePaths  1,300,774.12  0.0006  0.8563  0.0008  0.0008  0.0010  0.0010  0.0017  ±0.35%   650388
· newComparePaths  7,773,004.63  0.0000  0.2112  0.0001  0.0001  0.0002  0.0002  0.0004  ±0.14%  3886503   fastest
BENCH  Summary
@tanstack/router-core  newComparePaths - tests/other.bench.ts > comparePaths
5.98x …
```

refactor(router-core): improve router.comparePaths regexp performance

---

packages/router-core/src/router.ts

Following up on https://github.com/TanStack/router/pull/4747
Implementation by @schiller-manuel

refactor(router-core): improve router.comparePaths performance by not using regex

---

packages/react-router/tests/optional-path-params.test.tsx
packages/router-core/src/path.ts

fix: ensure unique matchId when optional and required param are on the same level

---

docs/start/framework/react/build-from-scratch.md

currently, @vitejs/plugin-react is referenced in the following code snippet, but isn't installed, so vscode throws a "cannot find module" error; to fix this error, i added the plugin to the previously-run command to install dev dependencies.

docs(build-from-scratch): added missing dev dependency

---

docs/router/framework/react/guide/custom-link.md

As of [React Aria Components v1.11.0](https://react-spectrum.adobe.com/releases/2025-07-22.html), we now pass through DOM events, so it's no longer necessary to use hooks to create a custom link component. You can just use `createLink` with the React Aria component directly.
[Demo](https://stackblitz.com/edit/stackblitz-starters-qc66mmzn?file=src%2FLink.tsx)

docs(react-router): update custom-link guide for react-aria

---

packages/router-core/src/router.ts

`router` > `getMatch` doesn't need to create an array to find the match by id. This function gets called a lot, so it's better if we can avoid accumulating short lived objects that need garbage collection when using it.

refactor(router-core): router getMatch doesnt create an array

---

packages/router-core/src/router.ts

Use De Morgan's contrapositive to cleanup the return condition of the `clearExpiredCache` filter function. This should be a no-op and is mathematically equivalent to what was written before, just more readable for future refactoring.

refactor(router-core): router clearExpiredCache DeMorgan's simplification

---

packages/router-core/src/router.ts

Just correcting a variable naming mistake I made in https://github.com/TanStack/router/pull/4826 because I confused `staleTime` and `gcTime`.

refactor(router-core): router clearExpiredCache variable naming mistake

---

docs/router/framework/react/how-to/arrays-objects-dates-search-params.md
docs/router/framework/react/how-to/debug-router-issues.md
docs/router/framework/react/how-to/deploy-to-production.md
docs/router/framework/react/how-to/install.md
docs/router/framework/react/how-to/integrate-chakra-ui.md
docs/router/framework/react/how-to/integrate-framer-motion.md
docs/router/framework/react/how-to/integrate-material-ui.md
docs/router/framework/react/how-to/integrate-shadcn-ui.md
docs/router/framework/react/how-to/migrate-from-react-router.md
docs/router/framework/react/how-to/navigate-with-search-params.md
docs/router/framework/react/how-to/setup-auth-providers.md
docs/router/framework/react/how-to/setup-authentication.md
docs/router/framework/react/how-to/setup-basic-search-params.md
docs/router/framework/react/how-to/setup-rbac.md
docs/router/framework/react/how-to/setup-ssr.md
docs/router/framework/react/how-to/test-file-based-routing.md
docs/router/framework/react/how-to/use-environment-variables.md
docs/router/framework/react/how-to/validate-search-params.md
docs/start/framework/react/how-to/use-environment-variables.md
docs/start/framework/react/how-to/write-isomorphic-client-server-code.md

Followup to https://github.com/TanStack/router/pull/4834#discussion_r2241509807, this PR makes sure that all the "how-to" guides for Router and Start use the correct the frontmatter + level-1 heading syntax for the best structured output on the website.

docs: add frontmatter to the "how-to" guides

---

examples/react/basic-devtools-panel/src/main.tsx
packages/router-devtools-core/src/TanStackRouterDevtoolsPanelCore.tsx

fixes #4670
It seems that style and className were not passed down to the underlying components in TanStackRouterDevtoolsPanelCore, preventing users from customizing the style of the panel

fix(router-devtools-core): allow styling of TanStackRouterDevtoolsPanel

---

docs/start/framework/react/hosting.md

This PR corrects the hosting docs for Cloudflare Workers. Seems it was a mixup of Workers & Pages before.

docs(hosting): correct Cloudflare Workers wrangler.toml

---

packages/router-generator/src/generator.ts

When upgrading to the latest version, in my Docker setup I started getting errors like:
```
Error: EXDEV: cross-device link not permitted, rename 'b13b6193-a621cd78c46b3a318f72a46c63be0ef6' -> '/app/src/app/routes/route.tsx'
```
It appears it's due to the change at https://github.com/TanStack/router/pull/4860/files#diff-a903efbcea6827ab7d7262d62ec3cc012831364e98ebcafcfa4885eeb634f91eL1092 where `getTempFileName` no longer returns includes the `path.join` with the temporary directory.
This PR brings back the `path.join`.

fix(router-generator): use the tmpDir when genearting a temporary filename

---

examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.users.route.tsx

I think opts.deps is creating confusion here because there is no loader deps there.

chore(examples): remove unnecessary opts.deps to clear confusion

---

packages/router-core/src/Matches.ts
packages/router-core/src/typePrimitives.ts
tsconfig.json

This PR proposes we use the `@internal` JSDoc tag, and `--stripInternal` typescript compiler option to remove internal keys from the public `.d.ts` files.
Docs for `stripInternal`: https://www.typescriptlang.org/tsconfig/#stripInternal
This helps ensuring internal values aren't considered as part of the *public API surface* by users, allowing us more flexibility in refactoring.
> [!WARNING]
> This PR proposes we add `stripInternal` to the entire repo, not just `router-core`. However there are already some values marked as internal that weren't added by this PR:
> - `InferStructuralSharing` in `react-router`
> - `handleHashScroll` in `router-core > scrollRestoration`
> - many `InferFoo` types in `router-core > typePrimitives`
>
> as a result of this, we might have to switch some of those …

refactor(router-core): strip internal types from public build

---

packages/solid-router/tests/link.test.tsx

Followup to #4930, this PR pulls test (added to prevent a regression in navigation) over to `solid-router`.

test(solid-router): add test from #4930

---

docs/router/framework/react/api/router/NotFoundErrorType.md

- Mark the `global` property of `NotFoundError` as deprecated
- Add a description for `headers`
- Sort the properties in order

docs(router): update NotFoundError type

---

packages/react-router/src/router.ts

In the `window` conditional block of the global assignment, `createFileRoute` was assigned twice, overwriting the first assignment and leaving `createLazyFileRoute` undefined in browser environments.
Changed the second assignment to:
```ts
(window as any).createLazyFileRoute = createLazyFileRoute
```
This matches the `globalThis` conditional block behavior and ensures `createLazyFileRoute` is correctly available.
> **Note:**  
> If this was intentional and `createFileRoute` is meant to always reference `createLazyFileRoute` in browser environments, then it might be clearer to directly assign:
> ```ts
> (window as any).createFileRoute = createLazyFileRoute
> ```
> instead of having two consecutive assignments to `createFileRoute`. 
>
> If intentional, adding a short comment explaining this …

fix(react-router): correctly assign createLazyFileRoute on window

---

packages/react-router/tests/store-updates-during-navigation.test.tsx

The `store-updates-during-navigation.test.tsx` file tests how many times `updateMatch` is called during a navigation (i.e. how many times the store is updated, and all subscribers re-run).
In this PR we clean up this test file to allow us to more easily test various navigation types. We also add a test for "redirection inside beforeLoad" whose result will be improved by https://github.com/TanStack/router/pull/4925

test(react-router): improve store-updates-during-navigation tests

---

packages/router-core/src/router.ts

Minor cleanup of `handleRedirectAndNotFound` in `router-core`. The code looked like there were 3 possible cases, but `err` is only handled if it's a redirect or a notFound.
This PR is a no-op, it's just code cleanup without any functional changes.

refactor(router-core): simplify handleRedirectAndNotFound

---

packages/solid-router/src/router.ts

_This PR applies the same fix as in [#4948](https://github.com/TanStack/router/pull/4948), but for the `solid-router` package._
In the `window` conditional block of the global assignment, `createFileRoute` was assigned twice, overwriting the first assignment and leaving `createLazyFileRoute` undefined in browser environments.
Changed the second assignment to:
```ts
(window as any).createLazyFileRoute = createLazyFileRoute
```
This matches the `globalThis` conditional block behavior and ensures `createLazyFileRoute` is correctly available.

fix(solid-router): correctly assign createLazyFileRoute on window

---

packages/react-start/src/plugin/vite.ts
packages/start-plugin-core/src/plugin.ts

This simplifies the configuration, stripping it back to the minimum that is needed.

Simplify `resolve` and `optimizeDeps` configuration

---

docs/start/framework/react/hosting.md

I was puzzled why Railway wasn't starting a server, then realized TanStack Start doesn't define the start command by default

docs(start): Add Railway instructions

---

docs/router/framework/react/routing/installation-with-esbuild.md

The integration with Esbuild page's title is reflecting as Vite.
This PR updates it to reflect as "Esbuild"

docs: Integration with Esbuild - update title to reflect "Esbuild"

---

e2e/react-router/basic-file-based/src/routeTree.gen.ts
e2e/react-router/basic-file-based/src/routes/non-nested/baz.$bazid.tsx
e2e/react-router/basic-file-based/src/routes/non-nested/baz.tsx
e2e/react-router/basic-file-based/src/routes/non-nested/baz_.$bazid.edit.tsx
e2e/react-router/basic-file-based/src/routes/non-nested/route.tsx
e2e/react-router/basic-file-based/tests/app.spec.ts
e2e/solid-router/basic-file-based/src/routeTree.gen.ts
e2e/solid-router/basic-file-based/src/routes/non-nested/baz.$bazid.tsx
e2e/solid-router/basic-file-based/src/routes/non-nested/baz.tsx
e2e/solid-router/basic-file-based/src/routes/non-nested/baz_.$bazid.edit.tsx
e2e/solid-router/basic-file-based/src/routes/non-nested/route.tsx
e2e/solid-router/basic-file-based/tests/app.spec.ts
packages/router-core/src/path.ts
packages/router-core/tests/match-by-path.test.ts
packages/router-core/tests/path.test.ts

This PR merges the latest updates to main from #5169 and #5165 into Alpha and brings with it an update to how non-nested paths are parsed.
It also adds additional  unit testing for paths and matchByPath as well as additional e2e tests for react and solid

fix(router-core): Non-nested paths - alpha
